### ISSUE TITLE
toc extension: [TOC] surrounded by tags is ignored

### ISSUE THREAD

**Issue by thread13** [Python-Markdown/markdown#100]
Here is a slightly modified example from [the wiki](http://freewisdom.org/projects/python-markdown/Table_of_Contents) :  

```
<div> [TOC] </div>

# Header 1

## Header 2
```

What we get from `markdown_py` is the following:

```
<div> [TOC] </div>

<h1 id="header-1">Header 1</h1>
<h2 id="header-2">Header 2</h2>
```

Wrapping the toc marker with some tags is sometimes useful, so it would be nice to have such a possibility.  

PS. I guess this one would be Issue 100 ; if so -- would I get any awards to celebrate this number ?  )

**Comment by thread13** [comment]
[TOC] seems to have other weird phobia as well: for example, 

```
[TOC]

<!-- comment -->

## heading 1

## heading 2
```

for the input is perfectly Ok ( the table of contents _is_ generated ), while 

```
[TOC]
<!-- comment -->

## heading 1

## heading 2
```

is not ( the `[TOC]` marker remains untouched ) ; again, 

```
<div></div>
[TOC]

<!-- comment -->

## heading 1

## heading 2
```

is fine, when 

```
<unknown></unknown>
[TOC]

<!-- comment -->

## heading 1

## heading 2
```

is not, while 

```
<unknown></unknown>

[TOC]

<!-- comment -->

## heading 1

## heading 2
```

is fine again. 

---

I suppose sth around line 60 in toc.py should be properly converted to text, but I'm not acquainted with markdown internals to say this for sure.

**Comment by waylan** [comment]
The issue is that the marker `[TOC]` must be in a paragraph all by itself. This is how the extension was designed and implemented. And it is a reasonable way to do it. For example, a `p` tag cannot contain any block level tags - so a `p` tag cannot contain a table of contents. Therefore, what actually happens is that `<p>[TOC]</p>` is replaced, not just `[TOC]`. Therefore, the blank line both before and after the marker is required.

Regarding the marker being inside HTML. As anything inside block level HTML is not processed as markdown (as per the syntax rules) then the marker would be ignored as well. 

Perhaps these restrictions of the design could have been better documented, but they are restrictions based on how markdown syntax works, not specifically this extension, so there should be no surprises here. I'm closing this wontfix.

**Comment by thread13** [comment]
I agree it may be not easy to fix, but what about "unknown" tags ? if they are considered "block-level" by default, then this seems to be wrong; shouldn't they be ignored ? 

There are some blogging services that do not support markdown, but have their own "tags", and I don't quite understand why they can't be ignored by default just as it was traditionally done by all browsers ever since.
