### ISSUE TITLE
Incorrect < and & escaping

### ISSUE THREAD

**Issue by shuhaowu** [Python-Markdown/markdown#101]
Input: 

```
in this lesson, we'll be talking about <TBD>

Give me some feedback on <What We should insert here>
```

Output:

```
<p>in this lesson, we'll be talking about <TBD></p>
<p>Give me some feedback on <What We should insert here></p>
```

The `<`s should be `&lt;`. This should be an option, as `&` escaping might not be the best thing.

**Comment by waylan** [comment]
Actually, Python Markdown does the right thing here. See the [syntax rules](http://daringfireball.net/projects/markdown/syntax#autoescape). As raw HTML is allowed in markdown text, your sample markup is seen as raw HTML and not escaped. As per the syntax rules, if you want `&lt;` rather than a literal `<` in the output, then you need to type `&lt;` in the input.

Note that with Python-Markdown's [safe-mode](http://packages.python.org/Markdown/reference.html#safe_mode), this would not be an issue. However, for standard markdown behavior, this is not a bug, so I'm closing this 'wontfix'.
