### ISSUE TITLE
Error when parsing links

### ISSUE THREAD

**Issue by giacomocaironi** [Python-Markdown/markdown#1014]
When I insert one or no quotes into a link the result is right
```bash
>>> from markdown import markdown
>>> markdown('[a](("))')
'<p><a href="(&quot;)">a</a></p>'
>>> markdown('[a]((b))')
'<p><a href="(b)">a</a></p>'
```
When I insert two quotes the result feels wrong(doesn't comply with commonmark) but is still has the same behaviour as Markdown.pl (I looked at Babelmark)
```bash
>>> from markdown import markdown
>>> markdown('[a]((""))')
'<p><a href="(" title="">a</a>)</p>'
>>> markdown('[a](("b"))')
'<p><a href="(" title="b">a</a>)</p>'
```
However when I insert curly brackets with double quotes the result differs from Markdown.pl
```bash
>>> from markdown import markdown
>>> markdown('[a]({{b(c)}})')
'<p><a href="{{b(c)}}">a</a></p>'
>>> markdown('[a]({{b("c")}})')
'<p><a href="{{b(" title="c">a</a>}})</p>'
```
Is it a bug or the desired behaviour?

**Comment by facelessuser** [comment]
The syntax is: `[Text](link "title")`, so quotes have significance.

CommonMark had many discussions to decide how they were going to handle every single scenario, so yes, they now have a spec that they follow which this parser may not as we are not CommonMark.

As for this implementation, I'm not sure how Markdown.pl handles all these cases, I know ours, when it thinks it as seen the title, appears to wrap things up. This could be adjusted if we really feel the need to. Some of these examples are quite contrived, I would need to understand how much we care about these scenarios, and what would be our stance on how to handle them before we make further changes.

**Comment by waylan** [comment]
> Some of these examples are quite contrived, I would need to understand how much we care about these scenarios, and what would be our stance on how to handle them before we make further changes.

Yes, these examples are very contrived. Personally, I don't really care if we exactly match `markdown.pl`'s behavior in every case. This is one of the reasons Gruber (creator of Markdown) is opposed to a strict spec like Commonmark.

Without a reasonable example, I'm not inclined to take any action here.

**Comment by giacomocaironi** [comment]
> If reporting a syntax bug, you must provide the minimal input which exhibits the behavior, the actual output and the output you expected

taken from <https://github.com/Python-Markdown/markdown/blob/master/docs/contributing.md>

I have a real world scenario: inserting a Jinja2 block inside a markdown link. My case is:
```
[link text]( {{ some_function("some_string") }} )
```
or
```
[link text]( {{ some_string | some_filter }} )
```
In my case I can't parse the Jinja block before parsing the file with markdown. It is not really much of a problem as I can do this:
```
<a href=" {{ some_function("some_string") }} ">link text</a>
```
but if python-markdown behaved like Markdown.pl in this case it would be nice.
But as I said is not really a big problem, just a note about this strange results

**Comment by facelessuser** [comment]
Trying to push through Jinja in a preserved manner until after the Markdown process is a difficult thing, any number of Python Markdown extensions could break that. It would make more sense to run Jinja as a preprocessor, but I understand there may be things you want that only work after 🤷.

The question is how long to spend attempting to match all the `()`. Right now, I think if you have a `""` followed by a closing `)`, it assumes that that is probably the end even though it hasn't matched all the `()`. We could favor matching all the `()` first (if possible) and backtrack to the last `"")` if we can't match any `()`. I don't have the algorithm in front of me, but this is how I vaguely remember it working. 

It's complicated. You have to decide when to give up in these situations, and how much parse time you want to spend attempting to get what you *think* the user wants.

**Comment by waylan** [comment]
Ah, Jinja syntax. Unfortunately, we do not officially support passing Jinja syntax through unaltered. There are various potential conflicts. The fact that your links work in `markdown.pl` is merely coincidental. I'm sure I could find examples that fail in `markdown.pl` as well.

I would strongly suggest reevaluating the reasons for parsing Jinja after Markdown. However, if it is really not possible, then perhaps you should explore using a third party extension to preserve Jinja syntax. I'm not aware of any existing extensions that do this, but it shouldn't be to difficult to build.

Regardless, the primary reason for the difference in behavior between Python-Markdown and `markdown.pl` is that Perl's regex lib includes support for recursive expressions and Python does not. Therefore, the regex in `markdown.pl` simply indicates that any bracket pairs can repeat internally and support is automatic. In Python, it's not possible to do that in a single regular expression. You either need to hard-code a specific number of nesting levels, or parse the nesting outside of the regex. There are a few places where we do this. However, the rules don't require us to in the URL of links, so we don't as it can really slow the parser down.

Finally, I checked this myself in Babelmark and I see that `markdown.pl`'s behavior is different between versions 1.0.1 and 1.0.2b8. Python-Markdown's behavior matches 1.0.1, which is the last official release. Version 1.0.2b8 is a beta release which was never officially adopted. In fact, some changes made in that release (which were must more drastic than this) were never reflected in the published rules. Sometimes the change in 1.0.2 is an obvious bug fix, sometimes it introduces a new bug, and sometimes it is a clear intentional change in behavior. In this case It's not clear to me if this is an intentional change in behavior or an accidental one.

Regardless, I also wondered if a reference link would work and it [turns out][1] that with a few very unusual exceptions (like Pandoc which includes its own template syntax which mostly mirrors Jinja), none of the implementations even recognize the reference link as a link. That seems to make a good case for the position that Markdown does not support including Jinja syntax within it (unless it is within a code span or block of course).

Another observation is that many implementations convert all quotes to HTML entities (`"` becomes `&quot;`). That would obviously break Jinja syntax as well. There is not any good reason for a Markdown parser to not do that. While Python-Markdown did not currently, and we have no plans to change that, there is no guarantee that we won't in the future. So yeah, I would strongly suggest reevaluating the need to run Jinja after Markdown.

[1]: https://johnmacfarlane.net/babelmark2/?normalize=1&text=%5Blink+text%5D(+%7B%7B+some_function(%22some_string%22)+%7D%7D+)%0A%0A%5Blink+text%5D%5B1%5D%0A%0A%5B1%5D%3A+%7B%7B+some_function(%22some_string%22)+%7D%7D

**Comment by giacomocaironi** [comment]
> Another observation is that many implementations convert all quotes to HTML entities (" becomes \&quot;). That would obviously break Jinja syntax as well. There is not any good reason for a Markdown parser to not do that. While Python-Markdown did not currently, and we have no plans to change that, there is no guarantee that we won't in the future

You are right, and this could be the most important point against my original idea. Anyway, I can still accomplish what I want using raw html inside markdown, so it isn't much of a problem, it would only have been cleaner.

About the order of parsing: you are both strongly suggesting to parse Jinja first and I get it, because it is the most logical thing to do normally. In my case however it is better to do the other way around. It's not that what you suggest is not doable, but I would prefer to keep things as they are now in my code. But in any case it is not a game changer, so I will see. If I have time I might even write a custom extension as you have suggested. 

Anyway, thanks for your time and patience. Closing the issue
