### ISSUE TITLE
toc extension: [TOC] surrounded by span-level tags is ignored

### ISSUE THREAD

**Issue by thread13** [Python-Markdown/markdown#103]
Follow-up to [bug #100](https://github.com/waylan/Python-Markdown/issues/100#issuecomment-5926683): 

code:

```
<unknown><p>[TOC]</p></unknown>

## 1
## 2
```

transforms into:

```
<p><unknown><p>[TOC]</p></unknown></p>
<h2 id="1">1</h2>
<h2 id="2">2</h2>
```

What I believe to be wrong. 

Same happens with the `u` tags instead of `unknown`, which are probably not block-level tags.  

Following the [original description](http://daringfireball.net/projects/markdown/syntax#html), I have tried this:

```
<span>

<p>[TOC]</p>

</span>

## 1
## 2
```

with no luck as well. ["Unlike block-level HTML tags, Markdown syntax is processed within span-level tags."](http://daringfireball.net/projects/markdown/syntax#html)

So being block-level,  inline or unknown for a tag seems to be indifferent for the problem. 

If there is a right way to wrap `[TOC]` with _any_ tags, please let me know.

**Comment by waylan** [comment]
You seemed to have misunderstood my explanation. For the marker to be recognized it must be the only thing in a paragraph - that it, a markdown style paragraph. Anything else will cause it to fail.

When I said it matches `<p>[TOC]</p>` that was a little misleading because it actually matches the text ('"[TOC]"') of a 'p' element in an ElementTree Object. However, if any other markup of any kind (markdown or raw html) or any other text are contained within that 'p' Element, then a match is not found. And just to be clear, raw HTML is not converted to ElementTree Elements. It is just passed through unaltered - the markdown parser just sees it as plan text.

So to answer your question, the way it is currently implemented, there is no way to wrap the toc marker in raw html - which was the point of issue #100. Please continue any further discussions there. Closed as a duplicate.

**Comment by thread13** [comment]
I see. Fixed this with an independent post-processor, but may be some day I should try and see how hard it can be to do the right thing.  

A post-processor is fine, but I am missing some extended possibilities like using custom ids for the headings, like

```
### heading text ### heading-id
```

for inter-document references. 

Best, 
/t13
