### ISSUE TITLE
Html inlined markdown converted as text with 3.3 (strange case)

### ISSUE THREAD

**Issue by anlau** [Python-Markdown/markdown#1061]
Conversion of following (simplified) markdown has changed in 3.3.0.

```md
#Test
<div>**Bold text**</div>
```
3.2.2:

```html
<h1>Test</h1>
<p><div><strong>Bold text</strong></div></p>
```

3.3.0 (same with 3.3.1, 3.3.2 and 3.3.3):

```html
<h1>Test</h1>
<div>**Bold text**</div>
```

Note: inlined markdown is not rendered correctly even in 3.2.2 if the heading is absent or followed by a return.

We noticed this change in a MkDocs static website with a default configuration (no `md_in_html` extension). It's working as expected in 3.3 with `md_in_html` extension and `markdown="1"` attribute.

Probably more a fyi than a bug. Or at least incorrect usage on our end.

**Comment by facelessuser** [comment]
Yup this is expected. The old parser had a lot of buggy quirks and was re-written. In your specific case, prior to 3.3.0, the `div` wasn't handled like an HTML block tag because there was no blank line before it. The new parser will now handle it like a block tag even though there is no blank line in front of it. This now matches other parsers. So this behavior is known and is expected and, yes, different.

In 3.3.0+, block tags, if they are at the start of the line, will be handled like block tags, and the content will not be parsed as Markdown unless you are using the `md_in_html` extension and have added the `markdown="1"` attribute the tag.

**Comment by waylan** [comment]
As the [rules][1] explain:

> Note that Markdown formatting syntax is not processed within block-level HTML tags. E.g., you can’t use Markdown-style `*emphasis*` inside an HTML block.

Therefore, the behavior in 3.2.2 was a bug, which we fixed.

[1]: https://daringfireball.net/projects/markdown/syntax#html
