### ISSUE TITLE
Deadlock: never ending match() in treeprocessors.py!

### ISSUE THREAD

**Issue by vladsf** [Python-Markdown/markdown#1065]
Hi, 
[match = pattern.getCompiledRegExp().match(data[startIndex:])](https://github.com/Python-Markdown/markdown/blob/447da662b0c9548941a44a911e45c7cf6ad32861/markdown/treeprocessors.py#L278) never ends and hangs python process.
This happens in v2.6.11 python 2/3 and I guess later version are affected as well.
It happens only with certain input data and with `patternIndex = 2`.
Please see the python file attached with the sample code, pattern #2 and data.
[reg.py.txt](https://github.com/Python-Markdown/markdown/files/5527070/reg.py.txt)

**Comment by facelessuser** [comment]
1. v2.6.11 is an old version, so unless you can reproduce the issue on the latest version v3.3.3, there will probably be no action taken on this.

2. The provided example does not show an issue with Python Markdown as the provided script doesn't even call Python markdown. If there is an issue here, the opening post is very cryptic about what the issue is.

Can you provide an example, using the latest Python Markdown v3.3.3, that exhibits the issue?

**Comment by vladsf** [comment]
I have a better example now, yet you have no security policy nor advisory and asking me to post a vulnerability. That's not a good idea. I suggest to set up a security policy first for this project.

**Comment by facelessuser** [comment]
I'm not sure what you are looking for as a security policy. I can tell you that we cannot fix a bug that is not described.

If there is something you need, you are going to have to be clear in order to help us help you.

**Comment by vladsf** [comment]
[Python-Markdown Security page](https://github.com/Python-Markdown/markdown/security) exists and is empty now. I guess there must a be an email or something there so I can submit a test case without posting it on Github.

**Comment by facelessuser** [comment]
Okay, that sounds like a task for @waylan to look into.

**Comment by waylan** [comment]
Please describe the issue in a comment here.

**Comment by vladsf** [comment]
This comment would be an open-to-all issue. GitHub recommends creating a draft security advisory to privately discuss and fix a security vulnerability in your open source project - https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/creating-a-security-advisory
I suggest following this recommendation. Please create a draft security advisory and add me as collaborator.

**Comment by waylan** [comment]
The "attack vectors" for Markdown are pretty small. I'm having a hard time understanding what could be so sensetive. Sure, you may have discovered some syntax which could crash the parser. While we try to avoid that, there are various reports of that sort reported here. And it is a users responsibility to ensure any calls to the parser do not crash their server or the like. Or if there is some sort of XSS attack, well, that is well known (see [Markdown and XSS][1]) and we do not claim to protect against it anyway. In fact, we [encourage using a third party tool][2] for that. If there is really something else, and you really insist on reporting is privately, then you can send an email to the maintainers as listed on [PyPI][3].

[1]: https://michelf.ca/blog/2010/markdown-and-xss/
[2]: https://python-markdown.github.io/change_log/release-3.0/#safe_mode-and-html_replacement_text-keywords-deprecated
[3]: https://pypi.org/project/Markdown/

**Comment by vladsf** [comment]
Better safe than sorry. GitHub would not have created such advisory just for fun. 
Some projects are still migrating to Python3 and still using 2.6.11. I have sent the example to your email. I hope this bug is easy to fix and is not present in recent versions.
Thank you.

**Comment by waylan** [comment]
We only support the most recent version. If its not in that version, no patch will be forthcoming.

Also, as a reminder, we all work on this in our spare time as volunteers. The amount of extra work and time that you have already required me to go through just to obtain a bug report has far exceeded most, and it is not even verified to exist in the currently supported version. I'm not sure why I should spend any more time on this.

**Comment by vladsf** [comment]
Well, I spent much more time with gdb to identify the issue and prepare the test case. I see your point yet I'm not making money on Python-Markdown neither. "Won't fix" for a vulnerability is an answer as well. I see.

**Comment by facelessuser** [comment]
It's not a "Won't fix", it's a please show us what the issue is and whether it is present in the latest release. Some things have been redesigned since v2.6.11, and your issue may not even be relevant anymore.

**Comment by waylan** [comment]
Below is the report I received via email. There is no need for secrecy here. I received the email via my phone and will not be able to verify it for some time. Although I suspect the issue no longer exists due to the recent refactor of inline parsing. 

> Please find the .py file attached which demonstrates never ending markdown() call.
> The data used for markdown() is real world example, not something artificial.
> This problem exists in 2.6.11.

```python
import re
import markdown

def test_regex():  
    regex = re.compile(u'(?<!\\!)\\[([^\\]\\[]*(\\[[^\\]\\[]*(\\[[^\\]\\[]*(\\[[^\\]\\[]*(\\[[^\\]\\[]*(\\[[^\\]\\[]*(\\[[^\\]\\[]*\\])*[^\\]\\[]*\\])*[^\\]\\[]*\\])*[^\\]\\[]*\\])*[^\\]\\[]*\\])*[^\\]\\[]*\\])*[^\\]\\[]*)\\]\\s?\\[([^\\]]*)\\]')

    data = '[ id = 64 port = 33060\nRun [set session Servcx_wait_timeout=10][ id = 65 port = 33060\nRun [set session Servcx_wait_timeout=10][ id = 66 port = 33060\nRun [set session Servcx_wait_timeout=10][ id = 67 port = 33060\nRun [set session Servcx_wait_timeout=10][ id = 68 port = 33060\nRun [set session Servcx_wait_timeout=10][ id = 69 port = 33060\nRun [set session Servcx_wait_timeout=10][ id = 70 port = 33060\nRun [set session Servcx_wait_timeout=10][ id = 71 port = 33060\nRun [set session Servcx_wait_timeout=10][ id = 72 port = 33060\nRun [set session Servcx_wait_timeout=10][ id = 73 port = 33060\nRun [set session Servcx_wait_timeout=10][ id = 74 port = 33060\nRun [set session Servcx_wait_timeout=10][ id = 75 port = 33060\nRun [set session Servcx_wait_timeout=10][ id = 76 port = 33060\nRun [set @a=1][ id = 63 port = 33060\nRun [set @a=1][ id = 64 port = 33060\nRun [set @a=1][ id = 65 port = 33060\nRun [set @a=1][ id = 66 port = 33060\nRun [set @a=1][ id = 67 port = 33060\nRun [set @a=1][ id = 68 port = 33060\nRun [set @a=1][ id = 69 port = 33060\nRun [set @a=1][ id = 70 port = 33060\nRun [set @a=1][ id = 71 port = 33060\nRun [set @a=1][ id = 72 port = 33060\nRun [set @a=1][ id = 73 port = 33060\nRun [set @a=1][ id = 74 port = 33060\nRun [set @a=1][ id = 75 port = 33060\nRun [set @a=1][ id = 76 port = 33060'

    #result = regex.match(data)
    html = markdown.markdown(data)
    pass

if __name__ == "__main__":  
    test_regex()
```

**Comment by mitya57** [comment]
This does not happen with new versions. `git bisect` shows that it was fixed in d18c3d0acab0e7469c3284c897afcb61f9dd1fea which is included in 3.0 and newer versions.

**Comment by vladsf** [comment]
Thank you for the quick response! 
Please remove the .py file from open access.

**Comment by mitya57** [comment]
> Please remove the .py file from open access.

Why, if a fixed version was released more than two years ago? You mentioned Python 2, but that version is itself not receiving security updates for half a year, so people who are using it probably don't care much about security.

Anyway, it's @waylan's comment so I would let him decide whether or not to delete it.

**Comment by facelessuser** [comment]
@waylan there was no hang on the latest due to our refactoring of inline parsing. So this is not a current bug.

**Comment by vladsf** [comment]
@mitya57 I'm afraid the problem is a bit deeper, so I am asking. I went up from gdb and C level to 'markdown'. Perl RE engine is not vulnerable unlike Python3 so I wonder.

**Comment by waylan** [comment]
We are no longer using the regular expression that was causing the problem. In fact, this was a factor in making the change. The reference implementation (markdown.pl) makes use of Perl's recursive feature in the regex. However, Python's `re` library does not support recursive regex. Therefore, the old regex was a hack to fake it. However, in version 3 we completely refactored that code to use Python for parsing that, rather than relying on a regex.

**Comment by vladsf** [comment]
OK, so clearly it is Python's library issue which is still much slower Perl's engine. Wow.

**Comment by vladsf** [comment]
This is Python problem indeed - https://www.benfrederickson.com/python-catastrophic-regular-expressions-and-the-gil/
It seems RE2 lib addresses the issue.

**Comment by waylan** [comment]
If we were to switch to a different lib, we would probably use [regex](https://pypi.org/project/regex/). However, every time the subject comes up we have always been able to work around the problem in other ways. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by qbolec** [comment]
Hello :)
W.r.t. to the `regex` in the above snippet, it really looks like someone is trying to "keep the balance of the opening and closing brackets", which as we know is not a regular language, thus as a heuristic it seems to "inline" just a few levels of otherwise recursive grammar. But either the `regex` has a bug, or it does something more specific than counting brackets, as in particular:
```
    data= "[a[][]c][]";
```
matches, but:
```
    data= "[a[]d[]c][]";
```
doesn't match. (Basically the regex seems to require that nested brackets need to be next to each other (`[][]`), as opposed to being separated by something `[]d[]`). I'm not sure if that was the intent of the authors. If it wasn't intentional, then the regexp could actually be made a bit simpler and faster by using `rec[N]=\[ (not-a-bracket|  rec[N-1] )* \]` instead of current `rec[N]=\[ not-a-bracket* rec[N-1]* not-a-bracket* \]`.

Anyway, assuming that the original code is doing exactly what was needed, then I propose the following fix:
```
regex = re.compile(u'(?<!\\!)\\[(([^\\]\\[]*|[^\\]\\[]*(\\[([^\\]\\[]*|[^\\]\\[]*(\\[([^\\]\\[]*|[^\\]\\[]*(\\[([^\\]\\[]*|[^\\]\\[]*(\\[([^\\]\\[]*|[^\\]\\[]*(\\[([^\\]\\[]*|[^\\]\\[]*(\\[[^\\]\\[]*\\])+[^\\]\\[]*)\\])+[^\\]\\[]*)\\])+[^\\]\\[]*)\\])+[^\\]\\[]*)\\])+[^\\]\\[]*)\\])+[^\\]\\[]*))\\]\\s?\\[([^\\]]*)\\]')
```
It seems to work much faster, but is equivalent AFAICT, except that it introduces new capture groups, so if the Python code relies on numbering of capture groups then this numbering needs to be adjusted.

The change I've introduced depends on an observation that a pattern:
```
A*B*A*
```
is equivalent to:
```
(A*|A*B+A*)
```
as there are either 0 or at least one occurrence of `B`.
The reason it works faster is this: `B*` can match empty string, but `B+` can't. This means that if you run the original regexp on "AAA...AAA" it will try to break it N possible ways into `A^i B^0 A^(N-i)`, while my regexp only tries to match it to `A^N`, and then to fails to see any `B` in it, and then it's done. (This relies on the nice property that A and B must differ at first symbol, as `B` always starts with `[`, but `A` - never)
I've just applied this observation to all levels.

Here's the visualisation of the change once you add some white space and indentation to the old and new regexp:

```
--- old.regex    2020-11-16 15:03:47.392410700 +0100
+++ new.regex    2020-11-16 15:03:51.252632600 +0100
@@ -1,43 +1,43 @@
 (?<!\!)
 \[
 (
-  [^\]\[]*
+  ([^\]\[]*|[^\]\[]*
   (
     \[
-    [^\]\[]*
+    ([^\]\[]*|[^\]\[]*
     (
       \[
-      [^\]\[]*
+      ([^\]\[]*|[^\]\[]*
       (
         \[
-        [^\]\[]*
+        ([^\]\[]*|[^\]\[]*
         (
           \[
-          [^\]\[]*
+          ([^\]\[]*|[^\]\[]*
           (
             \[
-            [^\]\[]*
+            ([^\]\[]*|[^\]\[]*
             (
               \[
               [^\]\[]*
               \]
-            )*
-            [^\]\[]*
+            )+
+            [^\]\[]*)
             \]
-          )*
-          [^\]\[]*
+          )+
+          [^\]\[]*)
           \]
-        )*
-        [^\]\[]*
+        )+
+        [^\]\[]*)
         \]
-      )*
-      [^\]\[]*
+      )+
+      [^\]\[]*)
       \]
-    )*
-    [^\]\[]*
+    )+
+    [^\]\[]*)
     \]
-  )*
-  [^\]\[]*
+  )+
+  [^\]\[]*)
 )
 \]
 \s?
```
I'd be glad to offer a fix for the actual Python source code, if someone points me to the place in code where this regexp is generated and used.

BTW, I share @vladsf 's views on security, so in case you ever decide to hide his snippet, consider hiding my comment, too.

**Comment by waylan** [comment]
That regex was removed from the code in d18c3d0 almost 2 years ago. I don't understand why people continue to insist on discussing their objections to code which we have long since abandoned. I'm locking this discussion.
