### ISSUE TITLE
<svg> tag

### ISSUE THREAD

**Issue by cguilloud** [Python-Markdown/markdown#1106]
Hi,
Thanks for your work that we use via `mkdocs`.
We use `markdown-inline-graphviz` extension which insert a SVG image as XML content using `<svg>` element.

The problem we are facing is that `<svg>` tag ( and inners `<g>` tags) are wrapped with `<p>` tags and this corrupts the svg.

So, I propose to add `'svg'` to the list of block level elements ( like `'image'`) :
https://github.com/Python-Markdown/markdown/blob/master/markdown/core.py#L75

Thanks in advance for your attention.
Cyril.

**Comment by facelessuser** [comment]
But you can also use SVG inline. They are not inherently block. And what do you mean corrupts?

**Comment by facelessuser** [comment]
I would argue that if `markdown-inline-graphviz` needs its content to be rendered without the `<p>` tag, they could create a treeprocessor extension that replaces `<p><svg></svg></p>` with simply `<svg></svg>` but they should probably flag their `svg` somehow so they don't strip `svg` that is not meant to be block. They could also change their approach as the current `markdown-inline-graphviz` is using an inline processor instead of a block processor, so it isn't a surprise that it is wrapped in a `<p>` tag.

From an extension, you can actually update the block list, but as a user, I would not want `markdown-inline-graphviz` to this as there are legitimate uses of inline SVG, and I would not want the parsing of SVG to suddenly trigger block logic.

**Comment by waylan** [comment]
> ( like 'image')

@cguilloud you make point, `img` tags can be either inline or block level and we have clearly designated them as block level. However, we have done so because the Markdown rules clearly designate them as block level. However, the rules make no mention of `svg` tags, which makes it unclear how they should be treated.

The concern is that because the exiting behavior has existed for many years, we can assume that some users could have a number of inline `svg` tags in their documents. If we were to change the behavior, we would break those documents when they updated. For that reason, we will keep the existing behavior in-place. Note that the block-level behavior only happens when the opening tag is at the beginning of the line. Therefore, inline `svg` tags would not encounter this issue as they would generally occur somewhere other than the beginning of a line.

Finally, if you are using `svg` tags as block level tags, why not simply wrap them in a `div` or other similar block-level tag? That would effectively cause Markdown to ignore them and would have no effect on how your browser would render the HTML. This really is the best option, as it gives document authors the most flexibility.

**Comment by waylan** [comment]
I should add that I might reconsider if you can point to other Markdown implementations which treat `svg` tags as block-level tags.

**Comment by facelessuser** [comment]
Whether we change SVG to block or not, it will not fix the issue with `markdown-inline-graphviz` as it is using an inline parser. As such, all content will be wrapped in a `<p>` tag. If we were talking about the parsing of raw SVG, this may be a different discussion.

**Comment by facelessuser** [comment]
Just as an FYI, it is kind of a mixed bag how Markdown parsers treat SVG. Here is what Bablemark 2 says: https://johnmacfarlane.net/babelmark2/?text=test%0A%0A%3Csvg%0A++viewBox%3D%220+0+100+100%22+preserveAspectRatio%3D%22xMidYMid+slice%22%0A++style%3D%22width%3A100%25%3B+height%3A100%25%3B+position%3Aabsolute%3B+top%3A0%3B+left%3A0%3B+z-index%3A-1%3B%22%3E%0A++%3ClinearGradient+id%3D%22gradient%22%3E%0A++++%3Cstop+class%3D%22begin%22+offset%3D%220%25%22%2F%3E%0A++++%3Cstop+class%3D%22end%22+offset%3D%22100%25%22%2F%3E%0A++%3C%2FlinearGradient%3E%0A++%3Crect+x%3D%220%22+y%3D%220%22+width%3D%22100%22+height%3D%22100%22+style%3D%22fill%3Aurl(%23gradient)%22+%2F%3E%0A++%3Ccircle+cx%3D%2250%22+cy%3D%2250%22+r%3D%2230%22+style%3D%22fill%3Aurl(%23gradient)%22+%2F%3E%0A%3C%2Fsvg%3E%0A%0Atest

**Comment by facelessuser** [comment]
Additionally, I believe SVG is styled as inline by default in browsers. If you are using raw SVG, I'd recommend wrapping in a `<div>` tag.

**Comment by waylan** [comment]
@facelessuser if you normalize insignificant whitespace, Babelmark shows [less divergence][1] among implementations. What is interesting to me is the small number of implementations which do not wrap the `svg` tag in a `p` tag (PHP Markdown being the most surprising). It would seem that they are explicitly treating the `svg` tag as block-level. However, they are certainly in the minority.

However, where things get weird is when you [introduce blank lines][2] into the contents of the `svg` tag. I suspect this is what prompted the original request. However, we clearly match the reference implementation here. I see no reason to change.

So, there are two ways to aproach this:

1. Do not include any blank lined within a `svg` tag. 
2. Wrap the `svg` tag in a `div`.

[1]: https://johnmacfarlane.net/babelmark2/?normalize=1&text=test%0A%0A%3Csvg%0A++viewBox%3D%220+0+100+100%22+preserveAspectRatio%3D%22xMidYMid+slice%22%0A++style%3D%22width%3A100%25%3B+height%3A100%25%3B+position%3Aabsolute%3B+top%3A0%3B+left%3A0%3B+z-index%3A-1%3B%22%3E%0A++%3ClinearGradient+id%3D%22gradient%22%3E%0A++++%3Cstop+class%3D%22begin%22+offset%3D%220%25%22%2F%3E%0A++++%3Cstop+class%3D%22end%22+offset%3D%22100%25%22%2F%3E%0A++%3C%2FlinearGradient%3E%0A++%3Crect+x%3D%220%22+y%3D%220%22+width%3D%22100%22+height%3D%22100%22+style%3D%22fill%3Aurl(%23gradient)%22+%2F%3E%0A++%3Ccircle+cx%3D%2250%22+cy%3D%2250%22+r%3D%2230%22+style%3D%22fill%3Aurl(%23gradient)%22+%2F%3E%0A%3C%2Fsvg%3E%0A%0Atest
[2]: https://johnmacfarlane.net/babelmark2/?normalize=1&text=test%0A%0A%3Csvg%0A++viewBox%3D%220+0+100+100%22+preserveAspectRatio%3D%22xMidYMid+slice%22%0A++style%3D%22width%3A100%25%3B+height%3A100%25%3B+position%3Aabsolute%3B+top%3A0%3B+left%3A0%3B+z-index%3A-1%3B%22%3E%0A%0A++%3ClinearGradient+id%3D%22gradient%22%3E%0A++++%3Cstop+class%3D%22begin%22+offset%3D%220%25%22%2F%3E%0A++++%3Cstop+class%3D%22end%22+offset%3D%22100%25%22%2F%3E%0A++%3C%2FlinearGradient%3E%0A++%3Crect+x%3D%220%22+y%3D%220%22+width%3D%22100%22+height%3D%22100%22+style%3D%22fill%3Aurl(%23gradient)%22+%2F%3E%0A++%3Ccircle+cx%3D%2250%22+cy%3D%2250%22+r%3D%2230%22+style%3D%22fill%3Aurl(%23gradient)%22+%2F%3E%0A%0A%3C%2Fsvg%3E%0A%0Atest

**Comment by cguilloud** [comment]
Hi, 
Thanks for all your comments !

I was also considering to over-wrap the `<svg>` by a `<div>` or `<object>`  (not clear for me what is better)  as an alternative.
I asked here because I was also thinking that it could be more correct to put it at markdown level.
but, if, as you said it can be used inline, and there is a risk for other usages, I agree that it must be better to change it at  `markdown-inline-graphviz` level.

Here is a small example of code generated by `markdown-inline-graphviz` using  `graphviz`:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
 "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Generated by graphviz version 2.42.3 (20191010.1750)
 -->
<!-- Title: G Pages: 1 -->
<svg width="62pt" height="44pt"
 viewBox="0.00 0.00 62.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
<title>G</title>
<polygon fill="white" stroke="transparent" points="-4,4 -4,-40 58,-40 58,4 -4,4"/>
<!-- card -->
<g id="node1" class="node">
<title>card</title>
<ellipse fill="none" stroke="black" cx="27" cy="-18" rx="27" ry="18"/>
<text text-anchor="middle" x="27" y="-14.3" font-family="Times,serif" font-size="14.00">card</text>
</g>
</g>
</svg>
```
* It should display  a circle with "card" inside.
* it works fine (for me ;-)) with: 
   -  Markdown.pl 1.0.1
   -  PHP Markdown 1.9.0
* If put into a  `<div>` it works fine 

BTW: it was working some months ago... but I cannot reproduce :( 

Thanks.
Cyril.

**Comment by waylan** [comment]
I checked the [HTML5 spec][1]

> The `svg` element from the SVG namespace falls into the embedded content, phrasing content, and flow content categories for the purposes of the content models in this specification.

Embedded content, phrasing content and flow content can either be block-level or inline. Specifically, there are some elements in each category which are block-level, some which are inline and some that can be either. Therefore, I would agree with the suggestion to wrap your `svg` in a `div` if you want to ensure the browser treats it as block-level content.

[1]: https://dev.w3.org/html5/spec-LC/the-map-element.html#svg-0
