### ISSUE TITLE
Several Errors when importing

### ISSUE THREAD

**Issue by ghost** [Python-Markdown/markdown#1112]
```
import markdown
html = markdown.markdown("# hello")
```
The above is the example given on https://pypi.org/project/Markdown/ with the only change being I've entered an h1 with hello written within it.

The example code gives the following error:

```
Traceback (most recent call last):
  File "markdown.py", line 1, in <module>
    import markdown
  File "/mnt/storage/markdown+docs/markdown.py", line 2, in <module>
    html = markdown.markdown("hello")
TypeError: 'module' object is not callable
```

After having a look into the module files, I noticed the class markdown is actually Markdown with a capital M. 

```
import markdown
html = markdown.Markdown("# hello")
```

However that raises a new error:

```
Traceback (most recent call last):
  File "markdown.py", line 1, in <module>
    import markdown
  File "/mnt/storage/markdown+docs/markdown.py", line 2, in <module>
    html = markdown.Markdown("hello")
AttributeError: partially initialized module 'markdown' has no attribute 'Markdown' (most likely due to a circular import)
```

The same error occurs when I import any of the standalone functions, from markdown import *, or any other work around I can think of.

After uninstalling then reinstalling markdown via pip3, I repeated everything above and the same issues arise.

Python version: latest 3.8

**Comment by waylan** [comment]
The problem is that you named your file `markdown.py` which is causing a conflict with the `markdown` module. By default, Python will try to import a module from the current working directory first, and it if doesn't find a file by that name it will then look at the locations listed in your pythonpath. Because your file is named `markdown.py`, when you `import markdown` you are simply importing your own code which does not define `markdown.markdown` or `markdown.Markdown`. Therefore, both errors are correct.

Simply rename your file to something unique and things will work correctly.
