### ISSUE TITLE
UnescapePostprocessor doesn't escape the HTML characters.

### ISSUE THREAD

**Issue by akshatdalton** [Python-Markdown/markdown#1127]
I found this bug when I was adding the support to re-enable [Backslash escaping](https://github.com/Python-Markdown/markdown/blob/a11431539d08e14b0bd821ceb101fa59d6a74c8a/markdown/inlinepatterns.py#L77) and extended the list of [`ESCAPED_CHARS`](https://github.com/Python-Markdown/markdown/blob/a11431539d08e14b0bd821ceb101fa59d6a74c8a/markdown/core.py#L72-L73) to all the Punctuation characters. (Related PR: https://github.com/zulip/zulip/pull/17511)

For the following example input:
```html
\<strong\>Strong text\</strong\>
\<script\>alert(1)\</script\>
```

In the final output, HTML characters are left unescaped:
```html
<strong>Strong text</strong>
<script>alert(1)</script>
```

Expected output:

```html
&lt;strong&gt;Strong text&lt;/strong&gt;
&lt;script&gt;alert(1)&lt;/script&gt;
```

This can introduce XSS issues in the web app.

**Comment by akshatdalton** [comment]
For now, I've added a [small patch](https://github.com/zulip/zulip/pull/17511/files#diff-fdf42dee6384fb054fbc027e0b7b4f68896624321adb1b5f7a4ccf89094b92edR2097-R2100) (where I'm working in the PR mentioned) in [`UnescapePostprocessor`](https://github.com/Python-Markdown/markdown/blob/a11431539d08e14b0bd821ceb101fa59d6a74c8a/markdown/postprocessors.py#L123) -- escaping the HTML characters.

**Comment by facelessuser** [comment]
From what I recall, certain characters are better handled with HTML escaping in the escape function. I don't think anything special needs to happen in the unescape. I have an extension that escapes anything with `\` (within reason, and assuming and depending on if some other preprocessor doesn't get ahold of the characters first), and just handling a few special HTML cases seemed sufficient: https://github.com/facelessuser/pymdown-extensions/blob/main/pymdownx/escapeall.py#L54.

```py
>>> import markdown
>>> markdown.markdown('\<strong\>Strong text\</strong\>', extensions=['pymdownx.escapeall'])
'<p>&lt;strong&gt;Strong text&lt;/strong&gt;</p>'
```

**Comment by waylan** [comment]
Backslash escaping does not do HTML escaping. Those are two different things. Consider the example in the [rules][0]. `\*` renders as `*`. Therefore `\<` would render as `<` not `&lt;`. Although, you will notice that angle brackets are not even in the list of escapable characters. @facelessuser has pointed to an extension which apparently does this, although I find that to be a really strange behavior and can't image any situation where I would ever want to use it.

Finally, you should not be using manual escaping to address XSS concerns. If you have XSS concerns I suggest reading [Markdown and XSS][1]. If you want a Python solution for sanitizing Markdown's output, I suggest [bleach-allowlist][2]. To be clear, you would pass the Markdown text into Python-Markdown and then the HTML returned from Python-Markdown would be passed through bleach.

[0]: https://daringfireball.net/projects/markdown/syntax#backslash
[1]: https://michelf.ca/blog/2010/markdown-and-xss/
[2]: https://github.com/yourcelf/bleach-allowlist

**Comment by facelessuser** [comment]
Let me just clarify, I only used HTML escaping in my extension for the specified HTML characters as they did not go through the Markdown parser properly without doing so.

**Comment by akshatdalton** [comment]
Thanks for the suggestions!

Well, I'm not saying that doing Backslash escaping should also do the HTML escaping. I was expecting the HTML escaping in the **final output**. Because for a simple input:
```.py
>>> import markdown
>>> markdown.markdown("{} [] () <>")
'<p>{} [] () &lt;&gt;</p>'
```
we are doing HTML escaping to `<` and `>` characters, hence, I was also expecting the HTML escaping to be there in the final output when Backslash escaping is done. I looked in the [commonmark](https://spec.commonmark.org/dingus/?text=%5C!%5C%22%5C%23%5C%24%5C%25%5C%26%5C%27%5C(%5C)%5C*%5C%2B%5C%2C%5C-%5C.%5C%2F%5C%3A%5C%3B%5C%3C%5C%3D%5C%3E%5C%3F%5C%40%5C%5B%5C%5C%5C%5D%5C%5E%5C_%5C%60%5C%7B%5C%7C%5C%7D%5C~%0A), and they were doing the HTML escaping in the final output:
`\>` -> `<p>&gt;</p>`

What I'm trying to put here is that, according to me, [`UnescapePostprocessor`](https://github.com/Python-Markdown/markdown/blob/a11431539d08e14b0bd821ceb101fa59d6a74c8a/markdown/postprocessors.py#L123) should do the HTML escaping in the final output.




> Consider the example in the [rules](https://daringfireball.net/projects/markdown/syntax#backslash). `\*` renders as `*`. Therefore `\<` would render as `<` not `&lt;`. Although, you will notice that angle brackets are not even in the list of escapable characters.

```.py
>>> import markdown
>>> m = markdown.core.Markdown()
>>> m.ESCAPED_CHARS
['\\', '`', '*', '_', '{', '}', '[', ']', '(', ')', '>', '#', '+', '-', '.', '!']
>>> markdown.markdown("\\ \` \* \_ \{ \} \[ \] \( \) \> \# \+ \- \. \!")
'<p>\\ ` * _ { } [ ] ( ) > # + - . !</p>'
```
So, `>` is intentionally there in the list of [`ESCAPED_CHARS`](https://github.com/Python-Markdown/markdown/blob/a11431539d08e14b0bd821ceb101fa59d6a74c8a/markdown/core.py#L72-L73)?

**Comment by facelessuser** [comment]
I think the confusion is that Markdown escaping is meant to avoid the Markdown parser from parsing the content as Markdown. `>` is normally used for block quotes, so yes it is there, and yes it does prevent block quotes from being parsed. So, Python Markdown does what it set out to do with the escape. You can see here it is not alone: https://johnmacfarlane.net/babelmark2/?text=%5C%3E+test. With that said, it is in the minority specifically in how it approaches it.

I personally, felt that when `>`, `<`, and `&` were escaped (at least in my plugin), they should also be HTML escaped. With that said, I did not pursue such behavior here officially in Python Markdown as I viewed it as my own personal interpretation. Though I can see there be a strong argument for it as Python Markdown is in the minority there, but I can also understand the argument if Python Markdown does not wish to do so as there is already a clear way to escape such characters (using HTML escapes in Markdown: `&gt;`, etc.).

**Comment by waylan** [comment]
First of all, you still seem to be conflating backslash escaping and HTML escaping. The two are different and not directly related to eachother. Backslash escaping simply means that a character is treated as a standalone character rather than given the special meaning in the Markdown syntax. That's it. HTML escaping means that the output is converted to an escape sequence which a browser will display as raw HTML but not interpret as HTML. Note that the one affects Markdown's behavior whereas the other affects your browser's behavior.

> I was expecting the HTML escaping in the **final output**. Because for a simple input:
> 
> ```python
> >>> import markdown
> >>> markdown.markdown("{} [] () <>")
> '<p>{} [] () &lt;&gt;</p>'
> ```
> 
> we are doing HTML escaping to `<` and `>` characters, hence, I was also expecting the HTML escaping to be there in the final output when Backslash escaping is done.

Okay, now I understand your thinking. If a standalone anglebracket is HTML escaped, and a backlash escaped anglebracket is just a standalone anglebracket, then it should be HTML escaped as well. That seems reasonable.

That said, [Babelmark][1] does not support that. First we can ignore all of the Commonmark implementations, as we are **not** a Commonmark implementation. I would like to draw your attention to the reference implementation (`markdown.pl`). The input:

```
< >

\>
```

Results in the following output:

```html
<p>&lt; ></p>
<p>></p>
```

First of all `<` is not backslash escapable so we don't try it. Notice, however, that `>` is not escaped in either case. Of course, this is because a standlaone `>` means nothing in HTML without an opening `<` before it. Therefore, it doesn't actually need to be HTML escaped.

If we were going to change anything with Python-Markdown, we might consider not HTML escaping `>`. Although, it doesn't make any difference one way or the other in how a browser will treat it, so it's not worth the effort.

However, it seems that the issue is that you want to add `<` to the list of backslash escaped characters. In that case, you expected the character to also be HTML escaped, which is probably the correct behavior in that scenario. However, that character is rather special. Therefore, we would need to include code for a single character which we don't even include in the list. That's nonsensical. Seems to me that your extension should be overirding the processor to modify the behavior.

[1]: https://johnmacfarlane.net/babelmark2/?normalize=1&text=%3C+%3E%0A%0A%5C%3E

**Comment by akshatdalton** [comment]
Thank you all for your answers and suggestions!
I get the point that Python-Markdown follows Babelmark and is not CommonMark implementation.
Backslash escaping in Python-Markdown is more around Markdown's behaviour rather than HTML/browser's behaviour.

> However, it seems that the issue is that you want to add ``< to the list of backslash escaped characters. In that case, you expected the character to also be HTML escaped, which is probably the correct behavior in that scenario. However, that character is rather special. Therefore, we would need to include code for a single character which we don't even include in the list. That's nonsensical. Seems to me that your extension should be overirding the processor to modify the behavior.

Yes, we have extended the list of `ESCAPED_CHARS` to all the punctuation characters and to ensure that Backslash Escape doesn't introduce any XSS issues in the browser we have overridden the `UnescapePostprocessor` to modify the behaviour. 
The same can be found here:
1. [Extended list of `ESCAPED_CHARS`](https://github.com/zulip/zulip/pull/17511/files#diff-fdf42dee6384fb054fbc027e0b7b4f68896624321adb1b5f7a4ccf89094b92edR2149).
2. [Overridding the `UnescapePostprocessor`](https://github.com/zulip/zulip/pull/17511/files#diff-fdf42dee6384fb054fbc027e0b7b4f68896624321adb1b5f7a4ccf89094b92edR2084-R2102).
