### ISSUE TITLE
Licensing issue with Stackoverflow's CC-BY-SA License

### ISSUE THREAD

**Issue by uptickmetachu** [Python-Markdown/markdown#1148]
Hi, thank you for this library. 

We have recently been FOSS audited and this package was flagged with potential licensing issues. 

Code copied/distributed and/or adapted from [Stackoverflow requires](https://stackoverflow.com/help/licensing):
1. attribution and
2. **licensing under the same license as the original ([CC-BY-SA-3.0](https://creativecommons.org/licenses/by-sa/3.0/) or [CC-BY-SA-4.0](https://creativecommons.org/licenses/by-sa/4.0/)).** 
This repositories MIT License is not compatible with CC-BY-SA.

The code that is causing issue:

https://github.com/Python-Markdown/markdown/blob/faf73b08bb984669fcba044259f8d67fbfed69ab/markdown/util.py#L103
https://github.com/Python-Markdown/markdown/blob/faf73b08bb984669fcba044259f8d67fbfed69ab/markdown/util.py#L161

Consider changing the implementation of the function such that the attribution isn't required.

**Comment by facelessuser** [comment]
The StackOverflow code that was referenced I could hardly call an algorithm, it is more a demonstration of how to wrap a function creating a decorator. There is barely anything novel there and mainly helps people understand decorators which aren't always intuitive to some people.

Stackoverflow is filled with examples simply demonstrating how to use Python functions properly. Simply using a Python function as demonstrated on StackOverflow does not constitute copyright infringement.

You can't copyright the use of the "warn" function, so are they copyrighting the wrapping functions with decorators? As illustrated here https://docs.python.org/3/library/functools.html#functools.wraps?

The "copied" example simply demonstrates basic Python usage to achieve what people can't always remember how to do. I don't know how you'd make this extremely different except changing the function names.

If we were talking about an actual algorithm here, I'd be more concerned.

**Comment by uptickmetachu** [comment]
Thank you for taking the time to respond so promptly! 

I agree with you 100% with the deprecation decorator. It isn't doing anything novel. The attribution appears to be linking to the stack overflow comment only to document other similar usages. 

Perhaps the get_stack_depth function can be modified with something like:

```
def current_stack_size(size=2):
    frame = sys._getframe(size)
    while True:
        frame = frame.f_back
        if not frame:
            return size
        size += 1
```

Thoughts? I can open a PR with the change.

**Comment by facelessuser** [comment]
> Perhaps the get_stack_depth function can be modified with something like:
> 
> ```
> def current_stack_size(size=2):
>     frame = sys._getframe(size)
>     while True:
>         frame = frame.f_back
>         if not frame:
>             return size
>         size += 1
> ```
> 
> Thoughts? I can open a PR with the change.

My honest opinion is that the above is wholly unnecessary and is changing things simply to change things. My personal opinion is that if the link bothers anyone, I'd remove the StackOverflow link. Python demonstrates how to use wrappers: https://docs.python.org/3/library/functools.html#functools.wraps

And python explains their API for "warn": https://docs.python.org/3/library/warnings.html#warnings.warn

The example was essentially a demo of how to properly use decorators. Not much different than what is documented in Python's own documentation that I linked above. If anything, I'd argue that the StackOverflow example is derived from Python's own example.

I've answered plenty of questions on StackOverflow about my own libraries: https://stackoverflow.com/a/59977885/3609487. I'm simply demonstrating how they can use my library, the same way I do in my docs for the official repo.  This doesn't make using my library in this way bound to CC-BY-SA. My libraries are licensed under MIT, and me demonstrating the basics on StackOverflow on how to use them will not cause them to infect their repo licensing with CC-BY-SA.

Often, people are showing concepts that happen to be tailored to the specific asker's question, but they are quite often very basic things, fundamentals of a given library in question or the language API. I feel like this deprecated example falls into the above.

With that said, StackOverflow has plenty of examples of algorithm implementations, if Python Markdown was using any of that, I would recommend more care to apply the learned concept in a different way instead of copying code word for word.

I'll let @waylan weigh in though as the project maintainer. I personally see nothing wrong with what Python Markdown is doing, but I understand that seeing this may make your company's lawyers nervous at first glance. Company lawyers are paid to be overly cautious as that helps protect the company.

**Comment by waylan** [comment]
I agree with @facelssuser here. This seems like a complete waste of our time.

**Comment by uptickmetachu** [comment]
Agreed, seems dumb but lawyers / COPYLEFT auditing tools will get a false trigger... If code wasn't copied from SO the simplest resolution is to remove the attribution. A docstring explaining the functions usage would achieve the intention of the current attribution. 

Sorry for the time taken and thankyou for your response!

**Comment by jarekwg** [comment]
100% agree with you guys. Definitely don't want to be wasting your time with this nonsense -- I'd honestly likely be much less accommodating to this faff than @facelessuser has been already (thank you!).
Have thrown up a PR at #1149, to hopefully get past this quickly. :)

Cheers,
