### ISSUE TITLE
table does not render properly in <details> subsection

### ISSUE THREAD

**Issue by jlinoff** [Python-Markdown/markdown#1150]
I really like this package. Unfortunately, the following markdown does not render properly.

```
<details>

<summary>About</summary>

### Table Test (requested)

key  | value
--- | -----
a | a value
b | b value
c | c value

</details>
```

<img width="173" alt="Screen Shot 2021-07-02 at 9 44 39 AM" src="https://user-images.githubusercontent.com/2991242/124305608-31702d80-db1a-11eb-8385-fc96e22c3a04.png">
<img width="557" alt="Screen Shot 2021-07-02 at 9 44 21 AM" src="https://user-images.githubusercontent.com/2991242/124305638-3a60ff00-db1a-11eb-8d9a-4546da79ff85.png">

**Comment by waylan** [comment]
This is the correct, expected behavior. As the [Syntax Rules][1] state:

> Note that Markdown formatting syntax is not processed within block-level HTML tags. 

Of course, Commonmark [behaves differently][3] by parsing Markdown content after the first blank line within block-level HTML tags. However, Python-Markdown is *not* a Commonmark parser. It implements the original Markdown rules.

That said, you can use the [md_in_html][2] extension to alter the behavior. For that matter, I suspect an extension which implemented Commonmark's processing of raw HTML would be a really popular extension. I don't have a need for it, but it would make for a great third party extension.

[1]: https://daringfireball.net/projects/markdown/syntax#html
[2]: https://python-markdown.github.io/extensions/md_in_html/
[3]: https://spec.commonmark.org/0.29/#example-156

**Comment by jlinoff** [comment]
That makes sense thank you for explaining the reason and providing the reference.
