### ISSUE TITLE
apply customized styling to markdown elements

### ISSUE THREAD

**Issue by tian-yan** [Python-Markdown/markdown#1184]
does it support applying customized styling to markdown elements (h1, h2, h3, codeblock, blockquote etc) when rendering markdown file to HTML file ?

**Comment by facelessuser** [comment]
If you use CSS, sure, you can style HTML any way you want. If you are asking if the HTML that is generated will have custom styling baked in, then the answer is no unless you override the specific extension to inject your styling, but in most cases that would seem unneeded as you can do almost anything you want just by applying CSS.

**Comment by waylan** [comment]
Note that we only ever return an HTML fragment. Therefore the wrapping structure (`html`, `head`, and `body`) all need to be provided by you anyway. Of course, any CSS would either be defined in or linked to from the `head` , so that would be in your full control.

Now, if you are asking if we provide a mechanism for defining styling hooks in the generated HTML, then I would suggest checking out the [attr_list][1] extension.

[1]: https://python-markdown.github.io/extensions/attr_list/
