### ISSUE TITLE
Have some question about toc extension code line 313-314 

### ISSUE THREAD

**Issue by a358003542** [Python-Markdown/markdown#1212]
the toc extension code line in 313-314:

```
        for pp in self.md.postprocessors:
            toc = pp.run(toc)
```
It's will call all postprocessors, I am a new guy try to write some extension and then find the toc conflict my extension, and finally found that the toc extension called all postprocessor [so my postprocessor run function has call twice], I think this piece of code is a little out of control, because all the future extension will consider the toc extension will called my postprocessor, maybe limited to current the native some of postprocessors would be more nicer? 

If the future extension has some needed to the toc output, let's they do their own. 

just some advise, maybe there are a more good reson to write like that?

**Comment by waylan** [comment]
If you look at the built-in postprocessors, you should notice that they all undo things which were done earlier to the text. For example, they swap out placeholders for HTML entities, raw HTML and and the like. If that wasn't done, then the TOC could contain placeholders in the final result rather than the expected text. So, yes, the postprocessors are run twice: once on the body of the output and once on the TOC. However as the text within the TOC is a separate (now independent) copy of text from the body, the second run is necessary. Of course, the Markdown core doesn't know about this need of the extension (nor should it), so the extension makes the extra call itself, which it only runs on the TOC, not on the document body.

Because you are objecting to this behavior, then I am assuming you are not using a postprocessor as cleanup, but as the main function of your extension. This is not how postprocessors were intended to be used. If you can implement your entire extension in a postprocessor, then you don't need to use the extension API at all. Simply pass the output of Markdown into your own custom function directly and return the altered results.

**Comment by a358003542** [comment]
@waylan Thanks your explaination, maybe this write to the document would be nicer.

I just think maybe limited that piece of code behavior to the official supported extension would be nicer, like that:

OFFICIAL_EXTENSIONS = []

```
        for pp in self.md.postprocessors:
            if self.md.postprocessors in OFFICIAL_EXTENSIONS:
                toc = pp.run(toc)
```

Again just i am think, How to do depend on your guys. 

This issue will be closed in short time.

**Comment by waylan** [comment]
In my experience most third party extension also need this behavior for the same reasons.

If your extension is so unique that it needs different behavior, then it is up to your extension tp provide a workaround. Of course, you can always override/replace the TOC extension with your own. Therefore, we will not be making the requested change.
