### ISSUE TITLE
Numbered lists not working if not at start of text

### ISSUE THREAD

**Issue by avoca999** [Python-Markdown/markdown#1217]
It's more likely than not I'm either doing something wrong, or don't understand something here??

Having trouble formatting what I want to say!

I'm getting:
![image](https://user-images.githubusercontent.com/32246338/151360294-194785e4-1c11-4055-aa6a-c2b1e7dd0d68.png)

but
![image](https://user-images.githubusercontent.com/32246338/151360216-dc31f5a7-2613-46e5-bc64-4ce3617d9ec9.png)

The first one looks like it should also generate an ordered list, to me?

(There's a single space after each number and full stop, if that's relevant)

**Comment by facelessuser** [comment]
In the future, please provide copy/pastable examples as copying from pictures is a real pain. Pictures are fine as long as there are copy/pastable examples. With that said, your issue is that in Python Markdown, all new paragraphs under a list must start with an indentation of 4 spaces. I understand that there are many CommonMark parsers and will allow two space indentations, but Python Markdown is an old-school parser that is based on the original Markdown spec.

```markdown
1. Text

    Another paragraph.

2. Text

3. Text
```

**Comment by avoca999** [comment]
Aha - I did try several times to post proper text examples, but couldn't get it to show clearly what I meant, hence the images. I think I've worked that out.

Actually your answer gave me a clue - I need to leave a newline between the regular text and the start of the numbered list:

**This input:**
`Here is a list:\n1.  plop\n2.  plap\n3.  plip`

produces this output (bad - no list):
`<p>Here is a list:\n1.  plop\n2.  plap\n3.  plip</p>`

but **this input** (extra newline):
`Here is a list:\n\n1.  plop\n2.  plap\n3.  plip`

produces this output (good):
`<p>Here is a list:</p>\n\n<ol><li>plop</li><li>plap</li><li>plip</li></ol>`
