### ISSUE TITLE
rendering \n

### ISSUE THREAD

**Issue by md975** [Python-Markdown/markdown#1219]
Hi,

I have a string containing a lot of "\n" indicating new lines. When I do the following:

> html = markdown.markdown(ss)
with open("file.html", "w", encoding="utf-8", errors="xmlcharrefreplace") as output_file:
       output_file.write(html)

I see "\n" in the output file and it's not rendered. Is there a way to resolve this issue?
I don't want to see "\n", I want it to actually go to the next line.

Thanks!

**Comment by facelessuser** [comment]
I'm not quite sure I understand the complaint. Can you elaborate? Can you provide a specific example or problematic Markdown getting converted to a form you do not like?

Keep in mind that if you are concerned that the browser itself in which you are viewing the HTML is not rendering the `\n`, that is by design as browsers do not render `\n` within blocks unless they are within something like `<pre>` code blocks or have CSS applied to them which treats the given element as a `<pre>` block in regard to white space. This is not a Markdown problem. If you which to force `\n` in a given element to be treated as an actual line break, you will have to provide the appropriate CSS, maybe something like `white-space: pre;`.

**Comment by md975** [comment]
Sorry, I'm very new to this. Your comment was very helpful. Thanks so much.

**Comment by md975** [comment]
This is a general follow-up and not related to the library itself, but is there anything I can replace "\n" with, that would render as a new line when I open the output html file in Chrome?
I have a string in Python like this:

```
ss="<p>Here is an article for the phrase <em>all rights reserved</em> in <a " \
   "href=\"https://en.wikipedia.org/wiki/All_rights_reserved\">Wiki</a>, saying that the copyright holder reserves, " \
   "or holds for its own use, all the rights provided by copyright law. \n >\n\nBut this seems to be a different " \
   "idiom. \n</p> "
html = markdown.markdown(ss)
with open("file.html", "w", encoding="utf-8", errors="xmlcharrefreplace") as output_file:
     output_file.write(html)

```
Thanks for your help!

**Comment by mitya57** [comment]
You can end a line with two spaces (`  `), and Markdown will convert that to a line break.
Also you can use raw HTML line break, `<br>`.
Finally, there is [`nl2br` extension](https://python-markdown.github.io/extensions/nl2br/) which converts line breaks in input to HTML line breaks.
