### ISSUE TITLE
Getting issue while executing markdown in lambda

### ISSUE THREAD

**Issue by mhrjan** [Python-Markdown/markdown#1279]
Please find the below error ,
The error we are getting is with markdown 3.4.1 and it is working fine when using python version 3.3.7,

[ERROR] Runtime.ImportModuleError: Unable to import module 'handler': cannot import name 'etree' from 'markdown.util' (/var/task/site-packages/markdown/util.py)Traceback (most recent call last): | [ERROR] Runtime.ImportModuleError: Unable to import module 'handler': cannot import name 'etree' from 'markdown.util' (/var/task/site-packages/markdown/util.py) Traceback (most recent call last):

**Comment by waylan** [comment]
Are you using any third party extensions? What options are you passing t0 Markdown?

**Comment by mhrjan** [comment]
Yes i use mdx_gfm and here is the syntax
markdown.markdown(raw_markdown, extensions=[GithubFlavoredMarkdownExtension()])

**Comment by waylan** [comment]
My guess is that the issue is with the extension. As explained in the [release notes][1], we removed some code which was deprecated back in version 3.0. The error message you are getting suggests that the extension is calling some of that removed code. I would suggest following up with the developers of the extension.

[1]: https://python-markdown.github.io/change_log/release-3.4/#previously-deprecated-objects-have-been-removed
