### ISSUE TITLE
footnote does not produce valid HTML

### ISSUE THREAD

**Issue by posativ** [Python-Markdown/markdown#129]
I used the footnotes extension in my HTML5 blog and got the following from the [W3 validator with my post](http://validator.w3.org/check?uri=http%3A%2F%2Fblog.posativ.org%2F2012%2Flinkschleuder-26%2F&charset=%28detect+automatically%29&doctype=Inline&group=0).

Don't know why `<li id="fn:1">` is generated, but this is _not_ a valid pseudo element and should be not accessible in CSS selectors (at least SASS breaks). Pandoc produces valid output in the form of `id=fn-1`, but I used to use python-markdown, not an external tool.

**Comment by waylan** [comment]
Our output is an exact copy of [PHP Markdown Extra](http://michelf.ca/projects/php-markdown/extra/#fn-output)'s. Also, I believe that this does valid as HTML4 or XHTML1. Looks like you're trying to validate as HTML5 and the errors are actualy regarding depreciated use of the 'rev' and 'rel' attributes.

Regarding `<li id="fn:1">`, this is used so that you can click on the superscript in the body and jump down to the footnote (thus an id): `http://example.com/some/page.html#fn:1`. Of course, the `fn:1` indicates that this is footnote number 1. Footnote number two would be 'fn:2'. As each footnote would be different, not sure why you would be using css to reference the li id's. Seems like you would want to use `div.footnotes` and it's children (like perhaps `li:first`). The point is that the id was never meant as a styling hook.

In any event, this does "look like" a pseudo element and probably should be changed. I've brought this up on the [markdown list](http://six.pairlist.net/pipermail/markdown-discuss/2012-August/002612.html) in hopes that some consistency can be reached among the various implementations. Thanks for the report.

**Comment by michelf** [comment]
`fn:1` is a perfectly valid id attribute. It's true that it was not meant to be a style hook and it's probably a bad idea to use it as such (because what follows `fn:` is a user-defined text). In any case, you can still use it as a style hook if you backlash-escape the colon in your CSS selector, if you really want to.

**Comment by posativ** [comment]
Okay, I see that `fn:1` is fine (I ended by with li:first-child for the styling), but can we make footnotes compatible with HTML5 if possible?
