### ISSUE TITLE
<details> content is rendered outside

### ISSUE THREAD

**Issue by GuillaumeDesforges** [Python-Markdown/markdown#1333]
I'm using mkdocs with markdown akin to that:

```markdown
  * a bullet point, renders well

    > A quote, renders well

    <details>
      <summary>A summary, renders well</summary>

      Some details, excuse me?
    </details>
```

renders

```html
<ul>
<li>
<p>a bullet point, renders well</p>
<blockquote>
<p>A quote, renders well</p>
</blockquote>
<p></p>
<details>
<summary>A summary, renders well</summary>
</details>
<p></p>
<p>Some details, excuse me?</p>
</li>
</ul>
```

As we can see here, the content inside the `<details>` block in the source gets put outside in the output HTML.

The expected behavior for me would be that the closing `</details>` would be after the HTML of its content.

**Comment by waylan** [comment]
First thing to note is that the Markdown rules [explicitly state][1]:

> The only restrictions are that block-level HTML elements — e.g. `<div>`, `<table>`, `<pre>`, `<p>`, etc. — must be separated from surrounding content by blank lines, and the start and end tags of the block should not be indented with tabs or spaces. 

As start and end tags cannot be indented, that means that they cannot be nested inside a list item. Of course, that applies to block-level HTML tags, not span-level tags. Therefore, the reported behavior only applies to span-level HTML tag parsing.

[1]: https://daringfireball.net/projects/markdown/syntax#html

Second, I'm getting different output than reported.

```python
>>> import markdown
>>> markdown.__version__
'3.4.3'
>>> src = '''
...   * a bullet point, renders well
... 
...     > A quote, renders well
... 
...     <details>
...       <summary>A summary, renders well</summary>
... 
...       Some details, excuse me?
...     </details>
... '''
>>> print(markdown.markdown(src))
<ul>
<li>
<p>a bullet point, renders well</p>
<blockquote>
<p>A quote, renders well</p>
</blockquote>
<p><details>
  <summary>A summary, renders well</summary></p>
<p>Some details, excuse me?
</details></p>
</li>
</ul>
```

Notice that the "body" is correctly inside of the `details` tag. However, the opening `details` tag and the `summary` are wrapped in a `p` and the "body" and closing `details` are wrapped in a second `p`. This is because it is not being parsed as block-level HTML. If you remove the indentation from the the `details` tags, that issue goes away. Of course, because the rules explicitly disallow indented block-level HTML, we will not support it and you cannot expect block-level HTML blocks to work correctly when nested in list items.

Third, why is your output different than what I am getting? I expect the empty `p` tags in your output are a clue. Some other tool is processing Markdown's output and attempting to normalize the invalid output by explicitly closing the obviously invalid tag. Perhaps you obtained the HTML from your browser's dev tools, which would show the HTML as interpreted by the browser, not the HTML as it was received. My guess is that whatever tool is attempting to fix the invalid HTML has munged things up a bit. I would suggest finding the HTML file from MkDocs' output and then you will see what Markdown is actually outputting.

So how do we fix it? The rules prevent us from adding support for block-level raw HTML nested in list items, so you need a workaround. I expect a third-party Markdown extension would provide the best solution. I would suggest looking at the [Details Block extension][2]. which is part of [PyMdown Extensions][3]. The benefit is that as the extension doesn't require raw HTML, it is not restricted by Markdown's rules and can work when nested in list items, block quotes etc.

Finally, what about the invalid HTML output? That is how Markdown works; bad input results in bad output, which is the clue that you gave it bad input. When you are using raw HTML, it is your responsibility as the document author to ensure it is valid. The only way to ensure block-level tags (and their content) are not munged by the Markdown parser is to never indent them. Once you step outside those rules, then you are on your own and you can't expect valid output. In fact, I will note that the reference implementation (`markdown.pl`) has the exact same behavior in this instance. This is the correct expected output. You are expected to change your input.

I understand that some people don't like that answer, but we didn't write the rules, we are simply following them as written. You will find that Commonmark follows different behavior. But that is because they rewrote the rules to define different behavior. However, Python-Markdown is a Markdown parser, not a Commonmark parser, so we will keep our behavior as-is.

[2]: https://facelessuser.github.io/pymdown-extensions/extensions/blocks/plugins/details/
[3]: https://facelessuser.github.io/pymdown-extensions/
