### ISSUE TITLE
How to use target="_blank" in link item

### ISSUE THREAD

**Issue by VanilleAngeles** [Python-Markdown/markdown#1341]
With Pandoc shell command line no problem.
With markdown python program it's impossible.
I use several tests without success.
A solution ?

Markdown syntaxe: 
`[Markdown Python](https://github.com/Python-Markdown/markdown/issues){:target="_blank"}`

Thanks

**Comment by waylan** [comment]
Could you please provide us with the options you are passing to Python-Markdown (including any extensions you are using) as well as the actual output and the output you are expecting?

**Comment by VanilleAngeles** [comment]
Good evening.
My python prog (where file is my markdown file)
`                with open (file, 'r') as f:
                    Html = markdown.markdown(f.read())`
A simple markdown file
`
# target test
[Markdown Python](https://github.com/Python-Markdown/markdown/issues){:target="_blank"}  
`
The Html result
`....
</div>
<h1>target test</h1>
<p><a href="https://github.com/Python-Markdown/markdown/issues">Markdown Python</a>{:target="_blank"}  </p><
...`

Is it enough for checking ?
Thanks

**Comment by VanilleAngeles** [comment]
Good evening
The python file
`
                with open (file, 'r') as f:
                    Html = markdown.markdown(f.read())
`
I gave the markdown syntax previously.
Is it enough for you ?
Thanks

**Comment by waylan** [comment]
As a reminder, the `{:target="_blank"}` syntax is not part of Markdown's [standard syntax][0]. Therefore, we do not support it by default. However, with the [attr_list extension][1] we do provide support. If you enable the extension, then your input would presumably work as desired. I say "presumably" because you did not provide me with an example of the output you expect. Therefore, I can only assume the extension will match your expectations. If it doesn't then you may want to explore other [third-party extensions][2] and/or [build your own][3] extension.

[0]: http://daringfireball.net/projects/markdown/syntax
[1]: https://python-markdown.github.io/extensions/attr_list/
[2]: https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions
[3]: https://python-markdown.github.io/extensions/api/

**Comment by VanilleAngeles** [comment]
Thank you for your explanation. The extension will apply target to ALL links; it's not what I want.
I will use a python instruction.
On MD link line ( if I want open the link on a new page) I will add {:target="_blank"} at the end of the address 
`[Markdown Python](https://github.com/Python-Markdown/markdown/issues {:target="_blank"})  `
and after convertinf md to html the python instruction
`FinalHtml = FinalHtml.replace('{:target="_blank"}">','" target="_blank">')`

Thank you

**Comment by waylan** [comment]
I'm confused as to what you want. Isn't this the desired behavior?

```python
>>> import markdown
>>> src = '''
... [blank](http://example.com){:target="_blank"}
... [no blank](http://example.com/no_blank)
... '''
>>> print(markdown.markdown(src, extensions=['attr_list']))
<p><a href="http://example.com" target="_blank">blank</a>
<a href="http://example.com/no_blank">no blank</a></p>
```

**Comment by VanilleAngeles** [comment]
Exactly what I want.
Thanks very much from France.
