### ISSUE TITLE
Meta processor - allows undocumented leading spaces

### ISSUE THREAD

**Issue by sebbASF** [Python-Markdown/markdown#1352]
The RE for matching the start of a meta data entry allows for 0-3 leading spaces.

This does not appear to be documented.

Also I wonder why is it permitted?
It would help to explain this.

**Comment by waylan** [comment]
That was implemented many years ago so I can't recall exactly what the thinking was. However, there are a few different reasons why we might have made that choice.

1. The syntax was copied from other implementations. It is very likely that those implementations had the same behavior.
2. Markdown syntax is intentionally very forgiving. Four spaces of indent would make for an indented code block. Therefore any less that four spaces would not be a code block. It seems odd to allow three spaces of indent for a paragraph, but not other elements. Therefore, for consistency with the rest of the syntax, the same flexibility was implemented for meta-data.

So then, why not document it? Because it is not documented for the other elements either. While the parser is permissive in what is allows, such sloppy Markdown is not actually encouraged. Therefore, the documentation covers how to form well-formed Markdown.

I should note that I am aware that not everyone agrees with this approach. However, this approach is based on the view of the original creator of Markdown (John Gruber). We try to stay true to his approach even if we personally disagree and would prefer to do things differently.

Of course, if you would prefer your Markdown parser to work differently, then you can create your own extensions which work how you want. Or you are free to use a different parser.

**Comment by sebbASF** [comment]
I see, useful to know. Thanks!
