### ISSUE TITLE
RFE: please start making github releases

### ISSUE THREAD

**Issue by kloczek** [Python-Markdown/markdown#1365]
Is it possible next time on release new version make the github release to have entry on https://github.com/Python-Markdown/markdown/releases entries? 🤔

I'm asking because only on make gh release is spread notification about new release to those who have set watch->releases.

More about gh releases is possible to find on
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

**Comment by waylan** [comment]
> I'm asking because only on make gh release is spread notification about new release to those who have set watch->releases.

Oh, that's why people care about this. I never saw any reason to as you install from PyPI. But I suppose this would be a sensible reason for it. A PR to add this to the existing [deploy workflow][1] is welcome.

[1]: https://github.com/Python-Markdown/markdown/blob/master/.github/workflows/deploy.yml

**Comment by waylan** [comment]
I just found https://github.com/marketplace/actions/github-release which will create a release without attaching files. This is probably the way to go.

**Comment by kloczek** [comment]
yep 😄

**Comment by waylan** [comment]
Turns out that while the above-linked action does not upload any files, GitHub will automatically attach a zip/tar.gz of the  related tag at time of release. Therefore, having files with a release is unavoidable. Seems like we should have the release files which are uploaded to PyPI if we are going to have anything.
