### ISSUE TITLE
Multiple newlines break code formatting

### ISSUE THREAD

**Issue by mattiaverga** [Python-Markdown/markdown#1391]
Consider these examples:
```
>>> from markdown import markdown
>>> markdown('```\nsome\ncode\n```')
'<p><code>some\ncode</code></p>'
>>> markdown('```\n<some@email.me>\n```')
'<p><code>&lt;some@email.me&gt;</code></p>'
```
This is in line with other implementations, as I can see in [Babelmark III](https://babelmark.github.io/?text=%60%60%60%5Cnsome%5Cncode%5Cn%60%60%60%0A%0A%60%60%60%5Cn%3Csome%40email.me%3E%5Cn%60%60%60).

Now this:
```
>>> from markdown import markdown
>>> markdown('```\nsome\n\ncode\n```')
'<p>```\nsome</p>\n<p>code\n```</p>'
>>> markdown('```\n<some@email.me>\n\n```')
'<p>```\n<a href="&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#115;&#111;&#109;&#101;&#64;&#101;&#109;&#97;&#105;&#108;&#46;&#109;&#101;">&#115;&#111;&#109;&#101;&#64;&#101;&#109;&#97;&#105;&#108;&#46;&#109;&#101;</a></p>\n<p>```</p>'
```
seems a bit unexpected, compared to other [Babelmark](https://babelmark.github.io/?text=%60%60%60%5Cnsome%5Cn%5Cncode%5Cn%60%60%60%0A%0A%60%60%60%5Cn%3Csome%40email.me%3E%5Cn%5Cn%60%60%60) implementations. To add more fun, the online babelmark tool shows that markdown 3.3.2 produces the correct output, but even if I try to pin the markdown version locally I always get the wrong output...

**Comment by facelessuser** [comment]
Python Markdown is an old school Markdown parser and fenced code blocks were not part of the spec when it was created. Many parsers these days have fenced code blocks by default, but Python Markdown implements them via extensions as it did originally. You can either use [`fenced_code`](https://python-markdown.github.io/extensions/fenced_code_blocks/) or [`pymdownx.superfences`](https://facelessuser.github.io/pymdown-extensions/extensions/superfences/). Personally, I'd recommend the latter only because it plays nice in nested constructs.

**Comment by mattiaverga** [comment]
Got it, thanks.
