### ISSUE TITLE
global flags not at the start of the expression at position 63

### ISSUE THREAD

**Issue by Atom2330** [Python-Markdown/markdown#1474]
I am not able to download udemy videos using the Udemy-dl 1.1

I am getting the Global flags error 

![image](https://github.com/user-attachments/assets/4eb78577-a47c-495a-9b91-5037c477ef3a)
![Screenshot 2024-08-01 144635](https://github.com/user-attachments/assets/cb60a429-e073-411d-97d0-d09ead6d03c0)
![Screenshot 2024-08-01 144648](https://github.com/user-attachments/assets/c01f9898-084f-4a9e-af4e-b084c324070e)

Please check and help me

**Comment by facelessuser** [comment]
We did not create nor do we maintain udemy 1.1. You will need to talk to the author of that library to have the issue fixed. At no point in your posted call stack is Python Markdown mentioned. The issue is squarely in the udemy library.

What I can say is that they are not including their inline, regex flags in their regex pattern at the start of the pattern which is now more strictly enforced in recent versions of Python `re`.  They need to fix their library. There is nothing for us to do here.
