### ISSUE TITLE
Extension to include boilerplate reference-style links

### ISSUE THREAD

**Issue by jpmens** [Python-Markdown/markdown#167]
I need a Python Markdown extension which includes a bunch of reference-style links, but I can't get it to work. 

I have the following extension `mdx_refs.py` where I append a reference-style link to `new_lines`:

``` python

from markdown.preprocessors import Preprocessor
import markdown

class RefsExtension(markdown.Extension):

    def __init__(self, configs):
        self.config = dict()

        for c in configs:
            self.config[c[0]] = c[1]

    def extendMarkdown(self, md, md_globals):
        md.registerExtension(self)
        md.refs_options = self.config
        md.preprocessors['refs'] = RefsPreprocessor(md)

class RefsPreprocessor(markdown.preprocessors.Preprocessor):

    def __init__(self, configs):
        print "******* (refs) "

    def run(self, lines):
        new_lines = []

        for l in lines:
            new_lines.append(l)

        new_lines.append("")
        new_lines.append("[example]: http://www.example.com/something")
        for l in new_lines:
            print "-----> %s" % l

        return new_lines

def makeExtension(configs=None):
    return RefsExtension(configs=configs)
```

The caller uses that extension:

```
    #!/usr/bin/env python

    import sys
    import markdown
    from codecs import open

    md = markdown.Markdown(
        extensions=['fenced_code', 'refs'],
        output_format = 'html4'
    )

    text = """
    Hello *JP*, have you seen [example]?

    This one works [Xoo][xoo]?

    [xoo]: http://example.org"""

    print md.convert(text)



When running the program, I get the following output:


    -----> Hello *JP*, have you seen [example]?
    -----> 
    -----> This one works [Xoo][xoo]?
    -----> 
    -----> 
    -----> 
    -----> 
    -----> [example]: http://www.example.com/something
    <p>Hello <em>JP</em>, have you seen [example]?</p>
    <p>This one works <a href="http://example.org">Xoo</a>?</p>
    <p>[example]: http://www.example.com/something</p>

Is what I'm trying to accomplish at all possible?
```

**Comment by waylan** [comment]
If I understand you correctly, you want to set up a bunch of default link references. That way, if a reference style link exists in the document, but is not defined in that document, the default is used?

Rather than try to add more markdown syntax to the document, why not use the internal API that the existing reference preproccessor uses? Within your extension's `RefsPreprocessor.run` method, just do:

``` python
def run(self, lines):
    self.markdown.references[id] = (link, title)
    return lines
```

Obviously, you'll need to provide a way to define the id, link & title (for no title, use an empty string), but that should get you started. Also, I would suggest inserting your preprocessor _before_ the existing reference preprocessor. In fact, that's part of why your existing code does not work. With my suggested solution, if a reference does exist in the document, then that would override the predefined default (which I would think you would want).

Actually on further thought, you don't need a preprocessor at all. Just assign the predefined refs in your `RefsExtension.extendMarkdown` method:

``` python
def extendMarkdown(self, md, md_globals):
    md.references = {
        'id1': ('link1', 'title1'),
        'id2': ('link2', 'title2')
    }
```

Hope that helps. And, as this is not an issue with markdown itself, I'm closing this. For more assistance with creating your own extensions, I would suggest asking on the [mailing list](https://lists.sourceforge.net/lists/listinfo/python-markdown-discuss).

**Comment by jpmens** [comment]
Thank you _very_ much, @waylan.
