### ISSUE TITLE
definition list behavior differences with PHP Markdown Extra

### ISSUE THREAD

**Issue by skurfer** [Python-Markdown/markdown#172]
Given a list like this:

```
Item 1
: Paragraph 1

  Paragraph 2
```

PHP Markdown Extra will include paragraph 2 in the definition. Python-Markdown treats it as a stand-alone paragraph outside the definition list. Only by increasing the indent two spaces will Python-Markdown treat second paragraph as part of the definition.

```
Item 1
:   Paragraph 1

    Paragraph 2
```

**Comment by waylan** [comment]
This is a known and intentional difference. Python-Markdown enforces 4 spaces of indent everywhere. Any edge cases where other implementations allow less than 4 spaces of indent (usually only in lists) is considered a bug (by me) in that implementation. I am not interested in intentionally implementing a bug. If you don't like four spaces of indent, you can set the [tab_length](http://packages.python.org/Markdown/reference.html#tab_length) to whatever you want. Of course, that will effect the entire document - not just lists. If it is **really** important to you, you can always create your [own extension](http://packages.python.org/Markdown/extensions/api.html) that does whatever you want.

**Comment by skurfer** [comment]
OK. I thought consistency with PHP Markdown Extra was an overriding goal. Thanks for the clarification.

Seems to me that 4 spaces indicates a `<pre>` block, and to _require_ it in other contexts is a bug. Of course it should be an _option_ in other contexts, like lists. But you clearly disagree.

I'll experiment with `tab_length`. Thanks.

**Comment by waylan** [comment]
The [syntax rules](http://daringfireball.net/projects/markdown/syntax#list) clearly state:

> List items may consist of multiple paragraphs. Each subsequent paragraph in a list item must be indented by either 4 spaces or one tab.

To me, any behavior which differs from that is a bug.

**Comment by skurfer** [comment]
Ah, I see. My indentation of all ordered and unordered lists by 2 spaces kept me from ever having to learn that rule (since all subsequent paragraphs are naturally preceded by 4 or more spaces). Thanks again.
