### ISSUE TITLE
Footnote extension: id which contains : (colon) causes id confusion

### ISSUE THREAD

**Issue by brmullikin** [Python-Markdown/markdown#180]
Although the current output of ids (fn:x and fnref:x) is the current standard, the id's do not play well with others (cannot target easily with jquery, etc). The reason for this is because : (colon) is used to denote a pseudo class or pseudo element in css. Jquery and others see the colon and think that everything after the colon is a pseudo element and choke, because no such pseudo element (obviously) exists.

I understand that it is not desirable to change this behavior entirely, however, it would be nice if there were either an option to set the default footnote and footnote-ref prefix/separator to something more accessible. e.g. pass a third parameter to make id functions.

My thought is that setting the output_format to html5 can alter the output format of footnotes as well, perhaps using "fn-x" instead of "fn:x".

**Comment by waylan** [comment]
Is there a a rule in the html spec prohibiting (or, at least discouraging)
colons in ids? If so, then, yes, we should change this. If not, is jquery
choking just because a colon exists in the id (and jquery is only
manipulating other, unrelated parts of the document)? If so, that sounds
like a bug in jquery. Or, is jquery only choking when the id is passed to
jquery as a selector? If so, it would seem highly unlikely to me that
jquery would not provide an easy way to escape the colon, which sounds like
a bug in jquery.

Obviously, if it turns out to be a bug in jquery, then that should be
addressed upstream. If however, it turns out that our output is not
according to the html spec, then I think we need some consensus across
markdown implementations about how best to address this. Point me to the
relevant part of the spec, and I'll take it up with the various
implementors who support footnotes and see what we can come up with.

**Comment by brmullikin** [comment]
the Html specification allows both . (periods) and : (colons). To select an id with a period or colon in it using any css syntax (which jquery uses) one must escape the character. However, doing so is big performance hit. The problem also arises when one needs to arbitrarily select an id. In such a case, one needs to (per jquery's own recommendation) run a replace function to escape all occurrences of periods or colons. Again, doing so is a performance hit. Selecting an ID in such a way is almost 10x slower than simply omitting the colon. [see test](http://jsbin.com/ujajuf/6/). I do not have performance tests for css, but the same general theory applies for all css syntax based selections. (at the very least it makes stying potentially & unnecessarily cumbersome)

The choice of a colon as a separator for footnote ids seems an arbitrary choice in the first place; there is no additional functionality nor additional benefit gained, so far as I can tell. A concern would be breaking old scripts/styles/etc which rely on the current format, so I would suggest an "opt-in" replacement strategy. But the distinct downside (decrease in performance and significantly more difficult css selection rules) and the seemingly lack of an upside makes me believe that we should seriously consider replacing the colon.

**Comment by waylan** [comment]
I just brought this up for discussion on the markdown-discuss mailing list:

http://six.pairlist.net/pipermail/markdown-discuss/2013-January/002807.html

**Comment by michelf** [comment]
Conspicuously avoiding the subject of changing the output right now, my guess is that Jquery has an optimization for the common pattern `#nocolon` (probably calling getElementById under the hood) and that putting an escape makes it take the slow path (not using getElementById). To see that, take your test and add a class name (making the selector `#nocolon.anyclass`), or put an ancestor (as in `body #nocolon`), and you'll get equal speed everywhere.

**Comment by brmullikin** [comment]
Good catch! I hadn't thought to to test with additional selectors. It seems that contrary to what I thought before, escaping the colon comes with an arbitrary amount of overhead.

**Comment by waylan** [comment]
I think @michelf is right. However, his comment on the mailing list (pointing to php's [#58](https://github.com/michelf/php-markdown/issues/58)) reminded me about commit 2fe5b5b. Since that commit, the output of footnotes is different when `output_format` is set to "html5". Perhaps we could implement a change (dash instead of colon) only when outputting html5. That way, most older sites will continue to work the way they do now (whether their authors update markdown or not) and new sites (more likely to use html5) get the updated behavior.It's just a thought right now. Not something I'm in a hurry to implement. Of course, patches may move it along.
