### ISSUE TITLE
Link tags are not processed as blocklevel elements

### ISSUE THREAD

**Issue by alainv** [Python-Markdown/markdown#197]
## Summary

Link tags inside markdown files are not processed as blocklevel elements and get inserted between <p> tags.
## Observed behavior

Processing

```
<link rel="stylesheet" href="mycss.css" />
```

Returns

```
<p><link rel="stylesheet" href="mycss.css"/></p>
```
## Expected behavior

The line should not be processed.
## Fix

Add `link` as a block level element in `util.BLOCK_LEVEL_ELEMENTS`

**Comment by waylan** [comment]
Actually, is [appears](http://johnmacfarlane.net/babelmark2/?normalize=1&text=%3Clink+rel%3D%22stylesheet%22+href%3D%22mycss.css%22+%2F%3E) that Python-Markdown's current behavior appears to be favored. Of course, that's not to say it's the correct behavior. This looks like one of those issues were we need to decide between consistency with other implementations (which hold **a lot** of weight) and doing what's right/valid/less surprising. Obviously, the change would be less surprising, but what does the (X)HTML spec say about this. Is is invalid to have a link in a p tag? Does the spec consider link tags as block level?

**Comment by waylan** [comment]
Okay, just took the time to look this up. According to the [HTML4 spec](http://www.w3.org/TR/REC-html40/struct/links.html#edef-LINK), a link "may only appear in the HEAD section of a document." In other words, any raw link in markdown would result in **invalid** (X)HTML (I don't expect anyone is writing markdown output to the head of their html templates). As we don't purposely support invalid output, I can't see adding support for this.

That said, I did note that in specific circumstances, a link can be valid in the body of a document in [HTML5](http://www.whatwg.org/specs/web-apps/current-work/multipage/semantics.html#the-link-element). Specifically, "[w]hen used with the itemprop attribute, the element can be used both in the head element and in the body of the page, subject to the constraints of the microdata model." So the question is, are there any microdata formats that use link elements and are invalid inside a p tag? Only with a definitive yes to that question will I consider this change (and probably only when output_format=html5).

But why not make the change given that the output is invalid anyway -- at least with the change it is prettier? Because, when document authors do things wrong, ugly results provide a better hint that something is wrong. It should be obvious what the problem is. Links inside otherwise empty p elements result in big ugly swaths of whitespace in the browser. Remove the wrapping p tags, and that unwanted whitespace goes away. Of course, the correct fix it to remove the links -- and by leaving the p tags in -- that it what gets communicated to the author.
