### ISSUE TITLE
Documentation and implementation are not consistent on indentation of HTML tables

### ISSUE THREAD

**Issue by antoneliasson** [Python-Markdown/markdown#209]
In the documentation for the tables extension, the resulting HTML is indented like this:

```
<table>
  <thead>
    <tr>
      <th>First Header</th>
      <th>Second Header</th>
    </tr>
  </thead>
```

However, testing shows that none of the table related HTML tags are indented.

**Comment by antoneliasson** [comment]
This was tested in Arch Linux (64-bit) with Python version 3.3.0 and Python-Markdown 2.2.1.

**Comment by waylan** [comment]
This is a known and intentional.  The documentation is formatted to make it easier to read.

While Python-Markdown's actual output does have some whitespace formatting, it is not perfect - which doesn't really matter because it's insignificant whitespace anyway. If you really care about insignificant whitespace in your html, Then I suggest passing the output through a tool made for that purpose. Of course, patches are welcome if you have the time to improve Python-Markdown's whitespace handling - I don't.

**Comment by antoneliasson** [comment]
Of course it's not important. I thought this was a documentation mistake.
