### ISSUE TITLE
Safe mode doesn't allow HTML entities

### ISSUE THREAD

**Issue by aiiie** [Python-Markdown/markdown#214]
When `safe_mode` is set, it escapes/removes/replaces HTML entities:

``` python
>>> import markdown
>>> markdown.markdown('&lt;')
u'<p>&lt;</p>'
>>> markdown.markdown('&lt;', safe_mode='escape')
u'<p>&amp;lt;</p>'
```

I would expect it to leave these entities untouched, even in safe mode. In other words, I'd expect this behavior:

``` python
>>> markdown.markdown('&lt;', safe_mode='escape')
u'<p>&lt;</p>'
>>> markdown.markdown('<', safe_mode='escape') == markdown.markdown('&lt;', safe_mode='escape')
True
```

This matches the behavior you see on GitHub and Stack Overflow.

**Comment by waylan** [comment]
HTML entities are HTML. Therefore they are treated as such.

Regarding Github and SO. If I'm not mistaken, don't they allow a subset of html tags also? Python-Markdown's "safe_mode" allows **no** raw html. 

Admittedly, "safe_mode" is not the best name, but we can't go back in time to change it. Think of is as no_html_mode; that's what it is in  practice. In fact, if you want "safe" sanitation of markdown's output, I would suggest a third party tool like [bleach](https://github.com/jsocol/bleach) rather than our "safe_mode". In fact, I've been considering removing "safe_mode" altogether in a future release. Still not decided on that yet.

**Comment by patricktokeeffe** [comment]
+1 for removing 'safe mode' since it breaks the specification.

**Comment by waylan** [comment]
@patricktokeeffe as per the [2.5 Release Notes](https://pythonhosted.org/Markdown/release-2.5.html#backwards-incompatible-changes), 'safe mode' is being deprecated.

**Comment by jpatel3** [comment]
+1
