### ISSUE TITLE
Can't define a code block after a definitiion list

### ISSUE THREAD

**Issue by bnguyen-atlassian** [Python-Markdown/markdown#219]
With the def_list extension turned on you cannot create a code block immediately after a list item.

For example, this syntax does not work:

```
Item
: sub-item

    # code block

```

**Comment by bnguyen-atlassian** [comment]
You can workaround this by enabling the fenced code block extension and using that notation.

**Comment by waylan** [comment]
This is not a bug but an annoyance of Markdown's syntax rules. In fact, you cannot have a code block after any kind of list item (ul, ol, df). This is because nested blocks in a list item are indented the same way a code block would be. The parser has no way to tell which you intended and so a child block is always assumed.  As you noted, a workaround is to use fenced code blocks. This is actually one of the main motivations for creating that extension.
