### ISSUE TITLE
URLs with colons in safe mode

### ISSUE THREAD

**Issue by artss** [Python-Markdown/markdown#220]
URLs with colons are not being parsed correctly with safe_mode='escape'. 

``` python
>>> from markdown import Markdown
>>> md = Markdown(safe_mode='escape')
>>> md.convert('[more](http://vimeo.com/blog/post:268)')
u'<p><a href="">more</a></p>'
```

**Comment by waylan** [comment]
Actually, this is intentional. Colons are not allowed in urls (except in a few know-to-be-safe situations) when in safe_mode. See the comments in the code starting at [line 332](https://github.com/waylan/Python-Markdown/blob/master/markdown/inlinepatterns.py#L332)  of inlinepatterns.py.

Why disallow colons? According to [RFC 1738](http://www.rfc-editor.org/rfc/rfc1738.txt), a colon is a reserved character and should be escaped. It says:

> [O]nly alphanumerics, the special characters "$-_.+!*'(),", and
>    reserved characters used for their reserved purposes may be used
>    unencoded within a URL.

Therefore, if a colon is used for anything other than its reserved purpose, it must be encoded. That being that case, you'll need to write your url like this: `http://vimeo.com/blog/post%3A268` for safe_mode to let it through. Here's a helpful [encoding/decoding tool](http://meyerweb.com/eric/tools/dencoder/).
