### ISSUE TITLE
Support for strikethrough

### ISSUE THREAD

**Issue by rfscotteb** [Python-Markdown/markdown#221]
We formally (and politely) request support for strikethrough. We use Bitbucket, and they indicated we should make this request here. Thank you for your time and consideration!

**Comment by waylan** [comment]
Thanks for your polite request.  Unfortunately, It is not clear to me whether you are requesting that striketrough be added as a default behavior of Markdown, or as an optional extension. As stated in our project [goals](http://pythonhosted.org/Markdown/index.html#goals), the default behavior of Python-Markdown should not deviate from the Markdown [syntax rules](http://daringfireball.net/projects/markdown/syntax). As strikethrough is not mentioned in the rules, we will not be adding it to Python-Markdown as a default behavior.

If you are requesting an extension, that might be considered (although extremely unlikely). Why does it need to be shipped with Python-Markdown? Why can't it exist as a [third party extension](https://github.com/waylan/Python-Markdown/wiki/Third-Party-Extensions)? In fact, how is some new markup better that just using inline raw html (`<del>some text</del>`)? There would hardly be any saved typing there. And then consider the following (from the [inline html rules](http://daringfireball.net/projects/markdown/syntax#html)):

> For any markup that is not covered by Markdown’s syntax, you simply use HTML itself. There’s no need to preface it or delimit it to indicate that you’re switching from Markdown to HTML; you just use the tags.

In my opinion, the simplicity of using raw del tags isn't enough motivation for me to implement and maintain an extension. Especially when considering the markdown philosophy above. Of course, you're free to disagree with me. But that's why we have an [Extension API](http://pythonhosted.org/Markdown/extensions/api.html). You can implement whatever changes to the syntax that you want.

In fact, if you want to write the extension yourself, you might want to take a look at this [tutorial](http://achinghead.com/python-markdown-adding-insert-delete.html) which steps you through the process of creating an extension. It happens to implement strikethrough, among other things. You are free to take that code and do what you want with it. I only wrote if for demonstration purposes and have no need to use it or desire to maintain it.

**Comment by rfscotteb** [comment]
Hi! Thank you so much for your response. I completely understand your position. The reason I was making this request is because Bitbucket uses your library to parse Markdown and they have indicated they won't use any extensions either. In addition, the `<del>` syntax does not work in Bitbucket.

I will push Bitbucket to support some extensions or at least the `<del>` syntax.

Thanks again!
Rob

**Comment by Friz-zy** [comment]
Hello guys,
2015 on calendar, maybe you can add support for [github flavored markdown](https://help.github.com/articles/github-flavored-markdown/)?

Goal for example:
Input: `##~~Hard~~Hand way`
Export: `~~Hard~~Hand way`
Even at [wiki](https://en.wikipedia.org/wiki/Markdown) it has another convention...

**Comment by waylan** [comment]
@Friz-zy, not sure what the calendar year has to do with anything. We will change the default behavior when the [syntax rules](http://daringfireball.net/projects/markdown/syntax) change (granted, that seems highly unlikely). Of course, you can [write your own extensions](https://pythonhosted.org/Markdown/extensions/api.html) which change the behavior in any way you want. In fact, [many have](https://github.com/waylan/Python-Markdown/wiki/Third-Party-Extensions). Perhaps you will find an existing extension that meets your needs.

**Comment by n37r06u3** [comment]
https://facelessuser.github.io/pymdown-extensions/extensions/tilde/   maybe you want this.

**Comment by darkdragon-001** [comment]
I couldn't find it in the docs, are issues for the included extensions tracked here or in separate repos? If separate repos, it would be good to link them in the docs...

This would fit in the `extras` extensions I suppose...

**Comment by facelessuser** [comment]
https://facelessuser.github.io/pymdown-extensions/extensions/tilde/ they're are probably others too.
