### ISSUE TITLE
why does _serialize_html downcase the closing tag?

### ISSUE THREAD

**Issue by eichin** [Python-Markdown/markdown#237]
It doesn't matter for html and xhtml, but I'm updating some code that used python-markdown 2.0.x to generate RSS to current versions, and I'm getting output with `<pubDate>...</pubdate>` - that is, the tags don't match (rss is not case-insensitive, or at least most of the XML-based tools for chewing on it aren't.)  `_serialize_html` at https://github.com/waylan/Python-Markdown/blob/master/markdown/serializers.py#L179 downcases the tag to compare it against some constants (`script`, `style`, `HTML_EMPTY`) which seems sensible, but then it writes out the downcased version and not the original.

Should I instead be writing a custom serializer (2.0 didn't even have them so it didn't come up...) or are there other approaches that make sense now?

**Comment by waylan** [comment]
Interesting find. It appears that this bug has existed since the serializer was first [added](https://github.com/waylan/Python-Markdown/commit/c89c1263798eaedffa09077819e769b019801556#L2R167) . As noted in that commit message, the actual work was done by others. The code was ripped out of ElementTree 1.3 preview (I believe 1.3 has never been released as production code - although a variation of it was used in later python versions) which included an HTML serializer. I'm not sure if that bug existed in ElementTree 1.3 preview or not (I didn't check).

In any event, I see that in [L175](https://github.com/waylan/Python-Markdown/blob/master/markdown/serializers.py#L175) of the current codebase we're comparing the tag against HTML_EMPTY without using lower (we should be). The real question is, should the actual tags be downcased in the output or not? When outputing x/html it seems that everything should be consistent, so downcasing provides a nice way to ensure that. On the other hand, tags are only ever created programicaly, so perhaps we should leave it up to extension authors to get right and make no assumptions in the serializer. I'm likely to go with the later approach.

Finally, if you are not outputing x/html, then yes, you probably should be writing your own serializer or perhaps use ElementTree's xml serializer (the API should still be the same). We needed an html specific serializer to avoid getting things like `<p/>` (as opposed to `<p></p>` ) in our output. I forget the exact details, but some edge-case was generating output which was crashing at least one browser hard when combined with a certain doctype. The thing is, that output was valid xml (with a different doctype). The only sensible fix to that and similar issues was to use an html specific serializer. In fact ElementTree 1.3 preview contained 2 serializers, one for xml and one for x/html. You shouldn't try to use one to generate the other type of output. Even xhtml is different enough from xml to require two serializers.

Thanks for the report.

**Comment by eichin** [comment]
Thanks.  Indeed,

``` python
    mdd = markdown.Markdown(extensions=...)
    mdd.output_formats["xml"] = markdown.util.etree.tostring
    mdd.set_output_format("xml")
```

(where the `extensions` include a custom RSS `treeprocessor` based on the old example) produces the output I'm looking for (I didn't see a cleaner way to "register" a serializer.)
