### ISSUE TITLE
***italic bold** italic*

### ISSUE THREAD

**Issue by tobiasberling** [Python-Markdown/markdown#253]
I think the output for `***italic bold** italic*` should be `<p><strong><em>italic bold</strong> italic</em></p>` (generated by Dingus).
The output I get from Python-Markdown is `<p><strong>*italic bold</strong> italic*</p>`. 
I checked this for version 2.2 and the latest master commit (e92d7cf65e)

**Comment by waylan** [comment]
Well, our output is certainly better than [some](http://johnmacfarlane.net/babelmark2/?normalize=1&text=***italic+bold**+italic*). This is a common problem for markdown parsers. The way the Python-Markdown parser works we either get something that works with your sample, or this: `***italic bold* bold**` but not both. It comes down to what order the various pieces of the parser are run in. At the time, very few if any implementations got it right (but they did get the [alternative](http://johnmacfarlane.net/babelmark2/?normalize=1&text=***italic+bold*+bold**) right) so we followed suite. I see that about half get I correct now. Guess we should to. Thanks for the report.

**Comment by waylan** [comment]
So I reread the original post and to clear any confusion up, @tobiasberling's suggested solution (`<p><strong><em>italic bold</strong> italic</em></p>` is **_not**_ the correct solution. That is a known bug in markdown.pl. Look at the nesting of the 'strong' and 'em' tags. That is not valid html by any standard. The correct output should be: 

``` html
<p><em><strong>italic bold</strong> italic</em></p>
```

Oh and I forget to mention in my previous comment, an easy workaround is to mix '*' and '_' in your input:

```
_**italic bold** italic_
```

There is absolutely no ambiguity there. The parser will always do what the author intended ([See what I mean](http://johnmacfarlane.net/babelmark2/?normalize=1&text=_**italic+bold**+italic_)). Well, that is unless the author wants [invalid nesting](http://johnmacfarlane.net/babelmark2/?normalize=1&text=_**italic+bold_+italic**). At least the output of most implementations in that instance inform the author that s/he did something wrong.

**Comment by JordanReiter** [comment]
In fairness if you look at the results page, one set of parsers does get it right (peg-markdown 0.4.14 et al). 

In fact, this set of parsers gets it right [_both ways_](http://johnmacfarlane.net/babelmark2/?text=***italic+bold**+italic*%0A%0A**bold+*italic+bold***)!

It would be interesting to look at these parsers and see how they do it as all others get it wrong in one way or another, probably due to either carelessness around tags in the markown.pl-inspired parsers, or by not looking ahead far enough.

**Comment by waylan** [comment]
Well, yes, that's because peg-markdown uses a [peg](http://en.wikipedia.org/wiki/Parsing_expression_grammar) grammar and parses the
text into a parse tree. That tokenized tree is then converted into HTML.

Almost all other markdown implementations follow markdown.pl’s lead and
simply run a series of regular expression substitutions. Which of the
expressions get run first determines which part of the example input gets
matched incorrectly. So, using the given example input, markdown.pl (the
original) would first match the double `*`s and swap them out resulting
In the following:

```
<strong>*italic bold</strong> italic*
```

Then it would run the next regex swapping out the single `*`s. And as those
regexs have no knowledge of HTML nesting, we get invalid HTML.
Python-Markdown is a little more sophisticated (HTML aware) so it avoids
the invalid nesting.

Of course, for the given use case, running the second regex first would
have resulted in:

```
<em>**italic bold** italic<em>
```

Clearly, in that senerio, running the first regex second would then return
the desired result. The problem is that, as mentioned in a previous
comment, the alternate input would then parse incorrectly.

The point is that to fix this properly requires either some much more
complex regex or competely rewriting the parser from the ground up. Most
implementations have slowly moved to more complex regex.

## 

Waylan Limberg

**Comment by waylan** [comment]
This is actually a pretty simple fix:

``` diff
diff --git a/markdown/inlinepatterns.py b/markdown/inlinepatterns.py
--- a/markdown/inlinepatterns.py
+++ b/markdown/inlinepatterns.py
@@ -100,7 +100,7 @@ BACKTICK_RE = r'(?<!\\)(`+)(.+?)(?<!`)\2(?!`)' # `e=f()` or
 ESCAPE_RE = r'\\(.)'                             # \<
 EMPHASIS_RE = r'(\*)([^\*]+)\2'                    # *emphasis*
 STRONG_RE = r'(\*{2}|_{2})(.+?)\2'                      # **strong**
-STRONG_EM_RE = r'(\*{3}|_{3})(.+?)\2'            # ***strong***
+STRONG_EM_RE = r'(\*|_){3}(.+?)\2{2}(.*?)\2'            # ***strong***
 SMART_EMPHASIS_RE = r'(?<!\w)(_)(?!_)(.+?)(?<!_)\2(?!\w)'  # _smart_emphasis_
 EMPHASIS_2_RE = r'(_)(.+?)\2'                 # _emphasis_
 LINK_RE = NOIMG + BRK + \
@@ -279,6 +279,8 @@ class DoubleTagPattern(SimpleTagPattern):
         el1 = util.etree.Element(tag1)
         el2 = util.etree.SubElement(el1, tag2)
         el2.text = m.group(3)
+        if len(m.groups())==5:
+            el2.tail = m.group(4)
         return el1
```

Unfortunately, there is a bug in [`markdown.treeprocessors.InlineProcessor.__processPlaceholders()`](https://github.com/waylan/Python-Markdown/blob/master/markdown/treeprocessors.py#L143) which strips everything out of the parent strong element (we get `<p><strong></strong></p>`). Or it might actually be in [`markdown.treeprocessors.InlineProcessor.__processElementText()`](https://github.com/waylan/Python-Markdown/blob/master/markdown/treeprocessors.py#L110) which is called by `__processPlaceholders()`. I didn't write that code and never quite worked out what `__processElementText()` is trying to accomplish. What I do know for sure is that this only happens when an InlinePattern returns a complex nested element with a tail somewhere in it. None of the built-in patterns have ever done so up to this point and I suspect that there is just some edge case that is not accounted for in the code.

I could keep working to debug this, but I am inclined to scrap the whole inline placeholder code and start over. Especially given that we also have issue #161 to resolve. I believe that during the 2008 GSoC project, Artem was trying to write a more performant way of swapping the placeholders   back out, but in the process, made it overly complex and hard to debug. By rewriting from scratch (following the methodology used for the htmlStash) we may lose some performance when parsing short documents, but if we resolve issue #161 and allow a fix to the nested bold/italic issue here, I think that is an overall win.

I bring this all up here because it needs to be resolve before I can apply the above diff to fix this issue. Stripping out document text is worse that what we get now, so this will have to wait until the other issue is resolved first.

And, as stated in an earlier comment, as this can be worked around by mixing underscores and asterisks `_**italic bold** italic_`, it is not really a high priority anyway.

**Comment by facelessuser** [comment]
I have been working to make the emphasis parsing work better for my personal use, and after an extremely painful time of trying to unravel `InlineProcessor`, I was able to get elements with `tails` and `text` to work:

``` diff
diff --git a/markdown/treeprocessors.py b/markdown/treeprocessors.py
index a82141a..6992cfb 100755
--- a/markdown/treeprocessors.py
+++ b/markdown/treeprocessors.py
@@ -129,11 +129,11 @@ class InlineProcessor(Treeprocessor):
             text = subnode.tail
             subnode.tail = None

-        childResult = self.__processPlaceholders(text, subnode)
+        childResult = self.__processPlaceholders(text, subnode, isText)

         if not isText and node is not subnode:
             pos = list(node).index(subnode)
-            node.remove(subnode)
+            # node.remove(subnode)
         else:
             pos = 0

@@ -141,7 +141,7 @@ class InlineProcessor(Treeprocessor):
         for newChild in childResult:
             node.insert(pos, newChild)

-    def __processPlaceholders(self, data, parent):
+    def __processPlaceholders(self, data, parent, isText=True):
         """
         Process string with placeholders and generate ElementTree tree.

@@ -160,6 +160,11 @@ class InlineProcessor(Treeprocessor):
                         result[-1].tail += text
                     else:
                         result[-1].tail = text
+                elif not isText:
+                    if parent.tail:
+                        parent.tail += text
+                    else:
+                        parent.tail = text
                 else:
                     if parent.text:
                         parent.text += text
```

I then used these patterns in the order shown below (interleaving the star patterns with the underscore patterns, but in order relative to their token):

``` python
STAR_TRIPLE_RE = r'(\*{3})(?!\s)(.*?)(?<!\s)\2'
UNEVEN_STAR321 = r'(\*{3})(?!\s)(.+?)(?<!\s)\*{2}(.+?)(?<!\s)\*'
UNEVEN_STAR312 = r'(\*{3})(?!\s)(.+?)(?<!\s)\*(.+?)(?<!\s)\*{2}'
STAR_STRONG_RE = r'(\*{2})(?!\s)(.*?)(?<!\s)\2'
UNEVEN_STAR211 = r'(\*{2})(?!\s)(.+?)(?<!\s)\*(.+?)(?<!\s)\*'
STAR_EMPHASIS_RE = r'(\*)(?!\s)(.*?)(?<!\s)\2'

UNDERLINE_TRIPLE_RE = r'(_{3})(?!\s)(.*?)(?<!\s)\2'
UNEVEN_UNDERSCORE321 = r'(_{3})(?!\s)(.+?)(?<!\s)_{2}(.+?)(?<!\s)_'
UNEVEN_UNDERSCORE312 = r'(_{3})(?!\s)(.+?)(?<!\s)_(.+?)(?<!\s)_{2}'
UNDERLINE_STRONG_RE = r'(_{2})(?!\s)(.*?)(?<!\s)\2'
UNEVEN_UNDERSCORE211 = r'(_{2})(?!\s)(.+?)(?<!\s)_(.+?)(?<!\s)_'
UNDERLINE_EMPHASIS_RE = r'(_)(?!\s)(.*?)(?<!\s)\2'
```

With a modified DoubleTagPattern for the _uneven_ rules:

``` python
class UnevenDoubleTagPattern(SimpleTagPattern):
    """Return a ElementTree element nested in tag2 nested in tag1.

    Useful for strong emphasis etc.

    """
    def handleMatch(self, m):
        tag1, tag2 = self.tag.split(",")
        el1 = util.etree.Element(tag1)
        el2 = util.etree.SubElement(el1, tag2)
        el2.text = m.group(3)
        el2.tail = m.group(4)
        return el1
```

And then running this on a non-exhaustive test just to prove it out:

``` markdown
***Test me** and this*
___Test me__ and this_

***Test me* and this**
___Test me_ and this__

**Test me* and this*
__test me_ and this_

***Test me***
___Test me___

**Test me**
__Test me__

*Test me*
_Test me_
```

I got this:
![screenshot 2014-09-18 23 18 01](https://cloud.githubusercontent.com/assets/1055125/4331017/6d687d8e-3fbc-11e4-8fdd-e306b203f3b1.png)

Spot checking the changes against other markdown content didn't seem to reveal anything (granted, as I said, I haven't done an exhaustive test on this).

Hopefully this helps.  But this seems to finally open up more complex tags.  This probably needs to be _stressed_ more to make sure there aren't more bugs, or side effects, but generally it seems to work pretty good.  I am only now starting to look at **smart** variants (ala github bold and italics), but I assume this can help with emulation there as well.

**Comment by facelessuser** [comment]
Small adjustment to regex rules (no need for uneven 211 rule, and should use `.+?` instead of `.*?`).  This set actually visually matched the dingus output. I was going to add a 311 rule, but that is also not needed:

``` python
STAR_TRIPLE_RE = r'(\*{3})(?!\s)(.+?)(?<!\s)\2'
STAR_UNEVEN_321_RE = r'(\*{3})(?!\s)(.+?)(?<!\s)\*{2}(.+?)(?<!\s)\*'
STAR_UNEVEN_312_RE = r'(\*{3})(?!\s)(.+?)(?<!\s)\*(.+?)(?<!\s)\*{2}'
STAR_STRONG_RE = r'(\*{2})(?!\s)(.+?)(?<!\s)\2'
STAR_EMPHASIS_RE = r'(\*)(?!\s)(.+?)(?<!\s)\2'

UNDERLINE_TRIPLE_RE = r'(_{3})(?!\s)(.+?)(?<!\s)\2'
UNDERLINE_UNEVEN_321_RE = r'(_{3})(?!\s)(.+?)(?<!\s)_{2}(.+?)(?<!\s)_'
UNDERLINE_UNEVEN_312_RE = r'(_{3})(?!\s)(.+?)(?<!\s)_(.+?)(?<!\s)_{2}'
UNDERLINE_STRONG_RE = r'(_{2})(?!\s)(.+?)(?<!\s)\2'
UNDERLINE_EMPHASIS_RE = r'(_)(?!\s)(.+?)(?<!\s)\2'
```

Updated Test with:

```
***Test me** and this*

___Test me__ and this_

***Test me* and this**

___Test me_ and this__

***Test me* and this*

___test me_ and this_

**Test me* and this*

__test me_ and this_

***Test me***

___Test me___

**Test me**

__Test me__

*Test me*

_Test me_
```

![screenshot 2014-09-19 06 41 09](https://cloud.githubusercontent.com/assets/1055125/4335253/51ec9052-3ffa-11e4-9aa5-d3e053981fcf.png)

EDIT:  I had nl2br on to isolate the cases.  The test above has been updated with new lines showing how I actually tested.

**Comment by facelessuser** [comment]
In case someone is trying to duplicate things, I have been doing this as an extension that overwrites the existing rules.  Here is the actual pattern loading:

``` python
        star_triple = SMART_STAR_TRIPLE_RE if enable_all or enable_asterisk else STAR_TRIPLE_RE
        star_double = SMART_STAR_STRONG_RE if enable_all or enable_asterisk else STAR_STRONG_RE
        star_single = SMART_STAR_EMPHASIS_RE if enable_all or enable_asterisk else STAR_EMPHASIS_RE
        underline_triple = SMART_UNDERLINE_TRIPLE_RE if enable_all or enable_underscore else UNDERLINE_TRIPLE_RE
        underline_double = SMART_UNDERLINE_STRONG_RE if enable_all or enable_underscore else UNDERLINE_STRONG_RE
        underline_single = SMART_UNDERLINE_EMPHASIS_RE if enable_all or enable_underscore else UNDERLINE_EMPHASIS_RE

        self.md.inlinePatterns["strong_em"] = DoubleTagPattern(star_triple, 'strong,em')
        self.md.inlinePatterns.add("strong_em2", DoubleTagPattern(underline_triple, 'strong,em'), '>strong_em')
        self.md.inlinePatterns['strong'] = SimpleTagPattern(star_double, 'strong')
        self.md.inlinePatterns.add('strong2', SimpleTagPattern(underline_double, 'strong'), '>strong')
        self.md.inlinePatterns["emphasis"] = SimpleTagPattern(star_single, 'em')
        self.md.inlinePatterns["emphasis2"] = SimpleTagPattern(underline_single, 'em')

        if not enable_all and not enable_asterisk:
            self.md.inlinePatterns.add('strong_em3', UnevenDoubleTagPattern(STAR_UNEVEN_321_RE, 'strong,em'), '>strong_em')
            self.md.inlinePatterns.add('em_strong', UnevenDoubleTagPattern(STAR_UNEVEN_312_RE, 'em,strong'), '>strong_em3')
        if not enable_all and not enable_underscore:
            self.md.inlinePatterns.add('strong_em4', UnevenDoubleTagPattern(UNDERLINE_UNEVEN_321_RE, 'strong,em'), '>strong_em2')
            self.md.inlinePatterns.add('em_strong2', UnevenDoubleTagPattern(UNDERLINE_UNEVEN_312_RE, 'em,strong'), '>strong_em4')
```

**Comment by facelessuser** [comment]
This does breakdown with stuff like `___Test me__ and this_ this___`.  But this is because dingus is a procedural parser and Python Markdown is a regex parser.  Dingus does things like `<strong>Test <em>Test </strong>Test </em>`. 

As you can see, the opening and closing tags are interleaved with each other.  You are not going to get this with regex that sets each rule to a given tag.  So I don't think Python Markdown should chase after 1:1 dingus output, but things can be improved.

Also, with the rules I posted above, I am still not sure the order the rules should be done in.  Maybe the **321** and **312** should come before the **triple** rule.

**Comment by waylan** [comment]
@facelessuser glad to see you working on this. I haven't had time to take a real close look at what you have done, but a quick glance at your diff looks like you are on the right track to me. With your patch applied, do all of our [tests](https://pythonhosted.org/Markdown/test_suite.html) pass?

I recently noticed that we don't have good test coverage on some of this code (see the [report](https://coveralls.io/files/290890666) on the latest build). I couldn't help but notice that all of the untested bits relate to tails - which of course, are not being used as they currently don't work. And in fact, I see you removed some of the untested code. With that issue fixed, I bet the rest of the untested code in that class would be tested with an appropriate test or two.

If we can add a few more tests to get 100% test coverage and not have any of the existing tests fail, I will be satisfied that the issue is fixed. Feel free to create a pull request with your work so far (minus your extension of course). When we reach that goal, I'll merge it.

**Comment by facelessuser** [comment]
> With your patch applied, do all of our tests pass?

I have not run the tests yet, but I will.  Just narrowing the issue down was a recursive headache last night.  I was just pleased to get a proof of concept working.

> I recently noticed that we don't have good test coverage on some of this code (see the report on the latest build)

I know I was exercising some of those parts of the code, but I am not certain if all of them.  Some of them are edge cases that I don't think would occur normally with what I was doing.  Namely the wrong placeholder check which doesn't directly have anything to do with `tail` code specifically, but if I can trigger the code to run I will.

> If we can add a few more tests to get 100% test coverage and not have any of the existing tests fail, I will be satisfied that the issue is fixed. Feel free to create a pull request with your work so far (minus your extension of course). When we reach that goal, I'll merge it.

I am a little unclear as to which you are referring to; I feel there are two issues here:
1.  markdown.treeprocessors.InlineProcessor bug
2. Improve italic and bold support

I will probably just approach both and let you reject whatever you don't like :smile:.

I will let you know when I have something more than some proof of concept stuff.

**Comment by facelessuser** [comment]
After adding the `tail` fix and italic and bold fixes.  I ran the tests on Python2.7 and Python3.3 (hopefully did it right).  The only issues I see are actually improvements (`*** Test` should translate to`<em>*</em> Test` since smart rules are not included for `*`; dingus also translates `***` to `<em>*</em>` when they are by themselves but not part of `hr` tags):

```
.......................S...................................................M.......................................M..................SSS...SSS..S.S..S..SS.SSSSSSS.....................S...S.SS..S....S.....................................................................................................................................
======================================================================
MarkdownSyntaxError: TestSyntax: "misc/em_strong"
----------------------------------------------------------------------
MarkdownSyntaxError: Output from "/Users/facelessuser/Desktop/Python-Markdown/tests/misc/em_strong.txt" failed to match expected output.
```

``` diff
--- /Users/facelessuser/Desktop/Python-Markdown/tests/misc/em_strong.html
+++ actual_output.html
@@ -4,7 +4,7 @@
 <p>With spaces: * *</p>
 <p>Two underscores __</p>
 <p>with spaces: _ _</p>
-<p>three asterisks: ***</p>
+<p>three asterisks: <em>*</em></p>
 <p>with spaces: * * *</p>
 <p>three underscores: ___</p>
 <p>with spaces: _ _ _</p>
```

```
======================================================================
MarkdownSyntaxError: TestSyntax: "misc/para-with-hr"
----------------------------------------------------------------------
MarkdownSyntaxError: Output from "/Users/facelessuser/Desktop/Python-Markdown/tests/misc/para-with-hr.txt" failed to match expected output.
```

``` diff
--- /Users/facelessuser/Desktop/Python-Markdown/tests/misc/para-with-hr.html
+++ actual_output.html
@@ -2,5 +2,5 @@
 <hr />
 <p>Followed by another paragraph.</p>
 <p>Here is another paragraph, followed by:
-*** not an HR.
+<em>*</em> not an HR.
 Followed by more of the same paragraph.</p>
```

```
----------------------------------------------------------------------
Ran 333 tests in 8.230s

FAILED (MarkdownSyntaxError=2, SKIP=25)
```

Current fork is here https://github.com/facelessuser/Python-Markdown

**Comment by facelessuser** [comment]
Fork at https://github.com/facelessuser/Python-Markdown has 98% code coverage for `treeprocessors.py`.  All `tail` code is covered.  The last 2% has to do with getting a no/wrong placeholder.  Placeholder code coverage is really out of scope for this issue, and frankly, I am not sure right now how to easily force such a scenario to get the 100% coverage.  I don't think that should halt this progress though as all relevant code is covered now.

I am done for now.

**Comment by waylan** [comment]
I just pushed up a branch [strongem](https://github.com/waylan/Python-Markdown/tree/strongem) where I cherry-picked the commits addressing the tail issue from PR #342 and squashed them into one commit (660614c). I also added a second commit (0500d86) which offers a simple solution to the strong/em issue. Note that in that second commit, I copied @facelessuser's tests wholesale (not including the extension stuff) and many of them are still failing. I have not yet reviewed most of the tests and many of them may be removed. This is in a branch because the behavior is subject to change. I may squash additional commits before merging to master. Just wanted to get it out there for review. Compare the branches here: https://github.com/waylan/Python-Markdown/compare/strongem

**Comment by facelessuser** [comment]
Just an FYI, the tests I added were mainly to characterize the behavior of the current regex in test.  It was always the intention to narrow them down to what was viewed as important once the implementation was  decided upon.  At the time, I felt it helped a lot to see how the regex responded to extreme scenarios to see what was getting traded off.  For the most part, the changes mainly affected complex scenarios and not basic behavior.  Anyways, look forward to seeing what you end up settling on.
