### ISSUE TITLE
Inline Placeholder not being swapped out in very long documents

### ISSUE THREAD

**Issue by user-none** [Python-Markdown/markdown#255]
Using 2.3.1.

It's the INLINE_PLACEHOLDER_PREFIX it's being inserted but not being replaced properly at a later stage.

Test case using an 8.2 MB example file. Create the example file using  https://gist.github.com/user-none/6694226 .

Shortly into the converted file you'll see the following:

```
klzzwxh:10007 klzzwxh:10008
klzzwxh:10009 klzzwxh:10010
klzzwxh:10011 klzzwxh:10012 klzzwxh:10013 klzzwxh:10014
klzzwxh:10015 klzzwxh:10016 klzzwxh:10017
Morbi luctus felis ornare, lobortis sapien klzzwxh:10018, semper tellus.
...
```

**Comment by waylan** [comment]
Curious, how much shorter does the document need to be before these errors don't appear?

**Comment by user-none** [comment]
Looks like the text repeated 667 times for a file size of 934K will cause the issue. Repeated 666 times no issue. Issue appears on block every block including and after 667.

**Comment by waylan** [comment]
So I was playing around with this and I came up with a simpler test that reproduces this:

``` python
src = '**foo**\n\n'*10001
markdown.markdown(src)
```

I find it peculiar that exactly 10,001 instances of inline markdown cause the error, but not 10,000. Of course, each instance generates an Inline placeholder and each placeholder is added to a dict with a new key. I'm wondering if this is reaching some limits in python. Although a quick test shows I can create a dict with more that 10,001 keys. Not really sure what to make of this.

**Comment by fake-name** [comment]
I've recently run into this issue. (It's still there in the current HEAD (2.4.DEV)).  

The problem is that in `util.py`,  
`INLINE_PLACEHOLDER_RE = re.compile(INLINE_PLACEHOLDER % r'([0-9]{4})')`

`{4}` limits the regex to at max match the string "9999". Therefore, any documents with more then 10,000 inline entities, all placeholders beyond 9999 will not be replaced.

Frankly, I don't know why the range is fixed in the first place. The HTML placeholder Regex is:  
`HTML_PLACEHOLDER_RE = re.compile(HTML_PLACEHOLDER % r'([0-9]+)')`

I'd suggest that they both should use the `[0-9]+` pattern, which means line 39 would then be:  
`INLINE_PLACEHOLDER_RE = re.compile(INLINE_PLACEHOLDER % r'([0-9]+)')`

In my testing, this fixes it. I can pull request if you'd like, but it's a 3-character change, so it seems easier to just let the dev's know, and someone will C+P the change.

**Comment by waylan** [comment]
@fake-name the reason the INLINE_PLACEHOLDER_RE is limited to 4 digits is because the placeholder is [zero-padded to 4 digits](https://github.com/waylan/Python-Markdown/blob/master/markdown/treeprocessors.py#L59). This has been the case for [6 years](https://github.com/waylan/Python-Markdown/commit/75c56efdc078fc3586a40a3dce7239819ded39a3#diff-93368430a9a8bada97cacb7f408da518R1413) now. I can't say what the thinking was back then, but we would have hit other issues (like maximum recursion depth) before hitting this issue. In any event, I don't think there is any good reason for it. As you note, the HTML_PLACEHOLDER does not pad its counter, so the INLINE_PLACEHOLDER shouldn't need to either.

Thanks for the comment. I had forgotten about the padded placeholders and was stumped as to what could be causing this.

**Comment by fake-name** [comment]
It's probably also worth noting that I don't think the inline placeholder needs to be zero-padded either, though it does make the data-structure possibly sort more pleasantly for debugging purposes.

---

I was dealing with some GIANT text files (10MB+) and ran into this problem. I've patched my local markdown install, but it's nice to see it get integrated into the main distribution.
