### ISSUE TITLE
Cannot use inline code tags inside of reference links

### ISSUE THREAD

**Issue by twolfson** [Python-Markdown/markdown#280]
It looks like reference links work and inline code + inline links work but a combination of the two does not.

Working:

```
>>> markdown.markdown('[hello][]\n\n[hello]: world')
u'<p><a href="world">hello</a></p>'
>>> markdown.markdown('[`hello`](world)')
u'<p><a href="world"><code>hello</code></a></p>'
```

Not working:

```
>>> markdown.markdown('[`hello`][]\n\n[`hello`]: world')
u'<p>[<code>hello</code>][]</p>'
```

The expected output of the above is the same as the output of the second

```
u'<p><a href="world"><code>hello</code></a></p>'
```

**Comment by waylan** [comment]
@twolfson, thanks for your report. I agree that this would appear to be a bug a first glance. However you should note that the syntax documentation states:

> Link definition names may consist of letters, numbers, spaces, and punctuation  — but they are not case sensitive.

Note that it does **not** say that they may consist of markdown markup, which may or may not be different than "punctuation" (depending on the implementation).

In fact, the various regex based implementations appear to have the [same behavior](http://johnmacfarlane.net/babelmark2/?normalize=1&text=%5B%60hello%60%5D%5B%5D%0A%0A%5B%60hello%60%5D%3A+world'). The way the regexparsers work is that they run one regular expression against the source text after another. Of course, so that markdown syntax can be enclosed in code tags, the code regex runs first. That means that the text between the brackets will be changed before the parser even looks for reference style links. Thus it will no longer match the reference name and will not be recognized as a reference style link[^1]. I'm not aware of any way to work around this except by starting from scratch with a completely different parsing method (top-down, Left-to-Right, PEG, etc. — methods used by the implementations which do not exhibit this behavior).

As the original implementation (markdown.pl) works this way, I see no reason to change. After all, if you need to have code inside a link, you can use a reference name in the [second set of brackets](http://johnmacfarlane.net/babelmark2/?normalize=1&text=%5B%60hello%60%5D%5Bid%5D%0A%0A%5Bid%5D%3A+world'). That works in all implementations.

For the reasons stated above and given that a minor adjustment to the source text works around this, I am closing this wontfix.

[^1]: Interestingly, the link regexes are run after the code regex, then all other inline markup (bold, italics, etc) after that. Therefore, all other inline markdown will [work](http://johnmacfarlane.net/babelmark2/?normalize=1&text=%5B*hello*%5D%5B%5D%0A%0A%5B*hello*%5D%3A+world') as a definition name (it's just seen as "punctuation"). However, this is more a happy coincidence than a requirement of the syntax rules.

**Comment by twolfson** [comment]
It is good to know that explicit reference links work. For what it's work GFM does support this behavior. Thank you for your consideration.

[`hello`](world)

```
[`hello`][]

# This should have a closing bracket but GitHub is parsing it
[`hello`: world
```
