### ISSUE TITLE
Convert DOS to Unix line endings

### ISSUE THREAD

**Issue by koobs** [Python-Markdown/markdown#289]
All sources contain windows line endings, for example setup.py:

```
def get_version():^M
    " Get version & version_info without importing markdown.__init__ "^M
    path = os.path.join(os.path.dirname(__file__), 'markdown')^M
    fp, pathname, desc = imp.find_module('__version__', [path])^M
    try:^M
        v = imp.load_module('__version__', fp, pathname, desc)^M
        return v.version, v.version_info^M
    finally:^M
        fp.close()^M
^M
```

**Comment by waylan** [comment]
Hmm, I do almost all of my development on Linux. Not sure how that could be. Or are you referring to the release rather than the git repo? It just occurred to me that as I didn't have access to my dev box when I generated the latest release I used a windows box (ugh), which would have resulted in all the line endings being converted by git on checkout. I'm so used to git doing the right thing regardless of what platform I'm on, that it didn't occur to me that the release would have platform specific line endings. Sorry about that. I'll keep that in mind next time. Although, I find it curious that you would be pulling changes from a release rather than the repo - especially when you're committing the changes to a git repo. Each release is tagged. Seems like a merge --squash would be the way to go if you wanted one commit for each release.

**Comment by koobs** [comment]
Thanks for the prompt response Waylan. This issue was more of a heads up, just in case you weren't aware. 

Yep on the release (sdist) rather than the repo. FreeBSD Python Ports use releases from PyPI (not unlike pip) if upstreams release them there.

No changes were pulled, the reference above is just a consequence of including this issues URL in my commit message to the ports repository, which is mirrored on GitHub here: https://github.com/freebsd/freebsd-ports.

Thanks again :)
