### ISSUE TITLE
Codehiglight broken with pygments master

### ISSUE THREAD

**Issue by domenkozar** [Python-Markdown/markdown#297]
If `None` is passed to pygments https://github.com/waylan/Python-Markdown/blob/master/markdown/extensions/codehilite.py#L109, AttributeError exception is raised inside the function `get_lexer_by_name`

**Comment by waylan** [comment]
According to Pygments’ [docs](http://pygments.org/docs/api/#module-pygments.lexers), `pygments.util.ClassNotFound` should be raised, which [appears](https://bitbucket.org/birkenfeld/pygments-main/src/8c4f7deee753bef17c8fbe85cb9eb5ab4e19b0ba/pygments/util.py?at=default#cl-28) to be a subclass of `ValueError`. As we are [catching](https://github.com/waylan/Python-Markdown/blob/master/markdown/extensions/codehilite.py#L110) `ValueError`, that shouldn't be a problem.

However, it appears that a [recent change](https://bitbucket.org/birkenfeld/pygments-main/commits/f8f4c391ed2ace5956ebe9a72a1079044dee70d4) to Pygments now causes a different error to be raised only when a non-string is passed in. Naturally, `nonstring.lower()` raises an `AttributeError`. We could just check for both in CodeHilite, but that seems like it could hide other issues. I've [reported](https://bitbucket.org/birkenfeld/pygments-main/issue/967/pygmentslexersget_lexer_by_name-no-longer) the problem to Pygments to see if they intended to disable passing `None` in to `pygments.lexers.get_lexer_by_name`. If so, we'll adjust our code. Otherwise the upstream fix will address this issue.

To be clear, I'm considering this a bug in Pygments until the developers of that project indicate otherwise. Also, I didn't check if the change in Pygments has made it to a release yet or not. If it has, that might sway me to address it here.

**Comment by domenkozar** [comment]
Fixed in https://bitbucket.org/birkenfeld/pygments-main/pull-request/300/get_lexer_by_name-handle-edge-case-when/diff
