### ISSUE TITLE
link url with two points in path

### ISSUE THREAD

**Issue by ctrl-alt-d** [Python-Markdown/markdown#301]
The issue is than markdown links are not right rendered as html when url link path contains ":" char. Sample:

```
[This link don't work](http://www.cacauet.org/wiki/index.php/Java:_introducci%C3%B3_r%C3%A0pida)
```

The environment is Markdown 2.3.1 with Python 2.7. And code looks like:

```
markdown(value, 
                  safe_mode=False, 
                  extensions=['tables', 'codehilite', 'sane_lists', 
                                      'fenced_code', 'def_list']
                 )
```

My first issue post, sorry about newbie mistakes.

**Comment by waylan** [comment]
@ctrl-alt-d don't worry about being a noob. Everyone has to start somehow. Here, I'll take you through my process of working through your report.

``` pycon
>>> import markdown
>>> markdown.version
'2.4'
>>> txt = "[This link don't work](http://www.cacauet.org/wiki/index.php/Java:_introducci%C3%B3_r%C3%A0pida)"
>>> markdown.markdown(txt)
u'<p><a href="http://www.cacauet.org/wiki/index.php/Java:_introducci%C3%B3_r%C3%A0pida">This link don\'t work</a></p>'
```

That's correct. Hmm, maybe one of those extensions are causing a problem??

``` pycon
>>> markdown.markdown(txt, extensions=['tables', 'codehilite', 'sane_lists', 'fenced_code', 'def_list'])
u'<p><a href="http://www.cacauet.org/wiki/index.php/Java:_introducci%C3%B3_r%C3%A0pida">This link don\'t work</a></p>'
```

Nope. `safe_mode` [defaults](https://pythonhosted.org/Markdown/reference.html#safe_mode) to False, but just to be sure:

``` pycon
>>> markdown.markdown(txt, safe_mode=False)
u'<p><a href="http://www.cacauet.org/wiki/index.php/Java:_introducci%C3%B3_r%C3%A0pida">This link don\'t work</a></p>'
```

Although, maybe if `safe_mode` is on...

``` pycon
>>> markdown.markdown(txt, safe_mode=True)
u'<p><a href="">This link don\'t work</a></p>'
```

Of course. With safe_mode on, we don't allow colons in links to avoid cross site scripting ([XSS](https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet)) attacks (the comments in the [code](https://github.com/waylan/Python-Markdown/blob/master/markdown/inlinepatterns.py#L330) explain more). Sorry we are not going to change this and open a potential security hole (thus I've closed this issue). Of course, you are welcome to create your own extension which works around this. Or better yet, rather than using `safe_mode`, run the output of markdown through an HTML sanitizer like [Bleach](https://github.com/jsocol/bleach). In fact, I recommend Bleach over our own `safe_mode`.

``` pycon
>>> html = bleach.clean(markdown.markdown(txt))
```

**Comment by ctrl-alt-d** [comment]
@waylan, thanks a lot by your fast reply and also about clear and complete explanation. I will learn more about Bleach. Congrats about your perfect work.
