### ISSUE TITLE
Ordered list next to un-ordered list

### ISSUE THREAD

**Issue by jlvcm** [Python-Markdown/markdown#309]
if i set my markdown as:

```
1.  one
2.  two
3.  three

*   one
*   two
*   three
```

instead of 
1.  one
2.  two
3.  three
-   one
-   two
-   three

i'm getting
1.  one
2.  two
3.  three
4.   one
5.   two
6.   three

**Comment by me-and** [comment]
Python-Markdown here matches the reference markdown.pl implementation. You can [check this with Babelmark](http://johnmacfarlane.net/babelmark2/?normalize=1&text=1.++one%0A2.++two%0A3.++three%0A%0A*+++one%0A*+++two%0A*+++three).

I agree the behaviour is counterintuitive, but I could believe a fix wouldn't be accepted since losing parity with the reference implementation brings its own problems.

**Comment by waylan** [comment]
@me-and is correct. Unfortunately, this is not a bug. However you will find the [sane lists extension](https://pythonhosted.org/Markdown/extensions/sane_lists.html) to offer a more intuitive behavior. And as it ships with Python-Markdown, it's not to much trouble to use.

**Comment by jlvcm** [comment]
then, this is wrong https://pythonhosted.org/Markdown/extensions/sane_lists.html#syntax ?

**Comment by me-and** [comment]
What do you think is wrong with that page?

**Comment by jlvcm** [comment]
"In other words, an ordered list will not continue when an unordered list item is encountered and vice versa" if this was true, the case above would work just fine, right?

**Comment by me-and** [comment]
Right. Provided you are using the sane lists extension, the case above will work just fine. You will not be using the sane lists extension unless you explicitly use it.

[The Extensions section](https://pythonhosted.org/Markdown/extensions/index.html) of the documentation explains how to use an extension.

**Comment by jlvcm** [comment]
Thanks :D..sorry for my confusion
