### ISSUE TITLE
Extension import issue in Markdown 2.5

### ISSUE THREAD

**Issue by brimcfadden** [Python-Markdown/markdown#341]
Markdown 2.5 has an issue with importing extensions. I've only seen it in the following form:
1. Have a library that is named the same thing as an extension. In my case, it's [PyTables](https://github.com/PyTables/PyTables), which shares a module name with the tables extension (`import tables` vs. `from markdown.extensions import tables`).
2. Create a `markdown.Markdown` object, and include the previous extension.
3. It raises an exception:

```
Traceback (most recent call last):
  [ ... ]
  File "/usr/local/lib/python2.7/dist-packages/markdown/__init__.py", line 154, in __init__
    configs=kwargs.get('extension_configs', {}))
  File "/usr/local/lib/python2.7/dist-packages/markdown/__init__.py", line 180, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, {}))
  File "/usr/local/lib/python2.7/dist-packages/markdown/__init__.py", line 261, in build_extension
    return module.makeExtension(**configs)
AttributeError: Failed to initiate extension 'tables': 'module' object has no attribute 'makeExtension'
```

I discovered that it was using the wrong module with the debugger:

```
ipdb> n
> /usr/local/lib/python2.7/dist-packages/markdown/__init__.py(222)build_extension()
    221             # Assume string uses dot syntax (`path.to.some.module`)
--> 222             module = importlib.import_module(ext_name)
    223             logger.debug('Successfuly imported extension module "%s".' % ext_name)

ipdb> ext_name
'tables'

[ ... ]

ipdb> module
<module 'tables' from '/usr/local/lib/python2.7/dist-packages/tables/__init__.pyc'>
```

This is a regression from 2.4.1, which works fine in this scenario.

**Comment by waylan** [comment]
We did make some changes in this code. Did you read the [release notes](https://pythonhosted.org/Markdown/release-2.5.html)? With this release we shouldn't have made any backward incompatible changes yet. However, there will be in future releases so you might want to change your code now if it doesn't line up with the current recommended best practices. Specifically, read the second to last item in [Backwards-incompatible Changes](https://pythonhosted.org/Markdown/release-2.5.html#backwards-incompatible-changes) and the second item in [What's New](https://pythonhosted.org/Markdown/release-2.5.html#whats-new-in-python-markdown-25).

However, I'm curious what we broke. Can you show me how you are calling markdown.Markdown? Are you passing in an instance of a class or passing in a string? If a string, which one? Without those details I can't duplicate your situation.

In fact, if you are passing in the string 'table', that would not have worked prior to the 2.5 release (as noted in [What's New](https://pythonhosted.org/Markdown/release-2.5.html#whats-new-in-python-markdown-25)). You would have only ever gotten the built-in extension. So the change here is actually not a regression, but progression. In fact, you say the module is wrong, but `/usr/local/lib/python2.7/dist-packages/tables/__init__.pyc` would be the module for PyTables. The module for the built-in table extension would be `...markdown/extensions/tables.py` (I don't know how you have it installed so I left the front of that path off).

Or are you saying that passing in the string 'tables' now only ever gets you the PyTables lib, when you want `markdown.extensions.tables`?  Oh, just followed your link to PyTables ... which is clearly not a markdown extension. Now I see your problem. Not sure how to work around that name clash than to say that you need to update your code now rather than with the next release. I'll have to think about that.

**Comment by brimcfadden** [comment]
Changing the code to use absolute Python path strings (like `markdown.Markdown(extensions=['markdown.extensions.tables', ...])` fixed the issue. Thanks.

I actually didn't read the release notes – sorry! I was resolving a _works-on-my-machine_ issue between two machines, for code I didn't write. From my very limited scope, something went from working in 2.4.1 to not working in 2.5. Referring to it as a regression was off-the-cuff and without context.

I'm not sure if you still consider this to be an issue or not, so I won't close it myself.
