### ISSUE TITLE
Bug with bold/italic on same line

### ISSUE THREAD

**Issue by valeriangalliat** [Python-Markdown/markdown#365]
The following input:

``` md
Example __*bold italic*__ on the same line __*bold italic*__.

Example **_bold italic_** on the same line **_bold italic_**.
```

Will result in the following HTML.

``` html
<p>Example __*bold italic<strong><em>bold italic</em><em> on the same line </em>_</strong>.</p>
<p>Example **_bold italic<strong><em>bold italic</em><em> on the same line </em>*</strong>.</p>
```

Though I think it should render like this:

> Example **_bold italic_** on the same line **_bold italic_**.

**Comment by valeriangalliat** [comment]
Though it works well with `***bold italic***` and `___bold italic___`, so I will use this instead.

**Comment by me-and** [comment]
Your example seems to [work just fine for me](http://johnmacfarlane.net/babelmark2/?normalize=1&text=Example+__*bold+italic*__+on+the+same+line+__*bold+italic*__.%0A%0AExample+**_bold+italic_**+on+the+same+line+**_bold+italic_**.). Can you give a bit more detail about what you're doing to get that input and output? What version of Python-Markdown are you using, and how exactly are you calling it?

**Comment by valeriangalliat** [comment]
Hi, thanks for answering.

```
% python --version
Python 3.4.2
% python -m markdown --version
__main__.py 2.5.1
% echo 'Example __*bold italic*__ on the same line __*bold italic*__.' | python -m markdown
<p>Example __*bold italic<strong><em>bold italic</em><em> on the same line </em>_</strong>.</p>
```

Also tried to clone the `master` branch of this very repo:

```
% python markdown/__main__.py --version
__main__.py 2.5.1
% echo 'Example __*bold italic*__ on the same line __*bold italic*__.' | python markdown/__main__.py 
<p>Example __*bold italic<strong><em>bold italic</em><em> on the same line </em>_</strong>.</p>
```

**Comment by me-and** [comment]
Well isn't that exciting. I can see this behaviour; I've just bisected the repository to find the commit that introduces it – this was introduced by 8358bb3c, so it's a regression in 2.5.1. That commit unsurprisingly changes the behaviour of nested em/strong parsing.

**Comment by facelessuser** [comment]
That is odd behavior,  all of my original work for handling nested bold and italic was removed and was not committed in that revision.  Only my fix for handling of tails in HTML actually made it through.  It was probably better since my work at the time was incomplete and not mature enough, sadly the alternative appears to be a little flawed as well (though I am sure it will be rectified soon).

As a workaround, you could also try using the following extension to correct this behavior: https://github.com/facelessuser/PyMdown/blob/master/pymdown/betterem.py.  Basically this is my work that I continued on the side to handle nested bold and italic in a more sane way (granted it is based on _my_ interpretation of how I feel bold and italic should work, so it may or may not align with your interpretation).  It at least does not suffer from the issue described above.  Documentation on the extension is found here: http://facelessuser.github.io/PyMdown/Extensions/BetterEm.html.  So you can see if it something you feel like trying or not.

I do plan on posting all the extensions I have been working on in the Python Markdown wiki once I feel they are **all** mature enough (which they are getting close to).  I will probably at that time break them out into a separate repo that can easily be installed as right now they are included in another project.  Feel free to try it out or not; just thought I'd share.

**Comment by facelessuser** [comment]
@valeriangalliat, the results you are getting are showing two isses:
1. Out of order (html tail issue)
2. Insufficient regex to highlight what we want

``` html
<p>Example __*bold italic<strong><em>bold italic</em><em> on the same line </em>_</strong>.</p>
```

Looking at this more, when you pulled the master, the way you are running it is causing you to still run the installed (non master markdown).  I won't go into details, but this is the case; it all has to do with how things are imported.  You should run it like this for testing (or you can install the master over 2.5.1):

``` python
import markdown

text = markdown.markdown(
    'Example __*bold italic*__ on the same line __*bold italic*__.'
)

print(text)
```

Now, running master we we see the out of order issue is fixed.  I recently added a tail fix that has not been released yet, but with it you no longer get out of order text:

``` html
<p>Example __*bold italic<strong><em> on the same line </em>_<em>bold italic</em></strong>.</p>
```

In regards to the wrong things getting recognized as bold and italic, the way the current regex is constructed vs the way things actually get returned is causing the problem.  Changing the regex from this:

``` python
EM_STRONG_RE = r'(\*|_){3}(.+?)\2(.*?)\2{2}'            # ***strongem*** or ***em*strong**
STRONG_EM_RE = r'(\*|_){3}(.+?)\2{2}(.*?)\2'            #  ***strong**em*
```

to this:

``` python
EM_STRONG_RE = r'(\*|_)\2{2}(.+?)\2(.*?)\2{2}'            # ***strongem*** or ***em*strong**
STRONG_EM_RE = r'(\*|_)\2{2}(.+?)\2{2}(.*?)\2'            #  ***strong**em*
```

Now gives us this:

``` python
<p>Example <strong><em>bold italic</em></strong> on the same line <strong><em>bold italic</em></strong>.</p>
```

Problem solved :wink:.

So, when I get some time, if @waylan or someone else doesn't get to it first, I will issue a pull request to fix this.

**Comment by waylan** [comment]
Yep, this is a bug that snuck in with  8358bb3. And apparently I had forgotten to update the server which Babelmark uses (it was still at 2.4). It is updated now to 2.5.1 and the bug definitely [exits](http://johnmacfarlane.net/babelmark2/?normalize=1&text=Example+__*bold+italic*__+on+the+same+line+__*bold+italic*__.%0A%0AExample+**_bold+italic_**+on+the+same+line+**_bold+italic_**.). Not sure when I'll have the time to get to this. Pull Requests are certainly welcome.

@valeriangalliat thanks for the report.
