### ISSUE TITLE
guess_lang=False doesn't work?

### ISSUE THREAD

**Issue by bjourne** [Python-Markdown/markdown#374]
Here is my markdown file:

```
I want this text verbatim:

    svn co http://emacspeak.googlecode.com/svn/trunk/lisp/g-client/
    cd g-client
```

And my opts.yml:

```
markdown.extensions.codehilite:
    guess_lang: False
    GUESS_LANG: False
```

Converting to html:

```
python -m markdown -x codehilite -x meta -c opts.yml test.md
```

The result is clearly syntax hilighted:

```
<p>I want this text verbatim:</p>
<div class="codehilite"><pre><span class="n">svn</span> <span class="n">co</span> <span     class="n">http</span><span class="o">:</span><span     class="c1">//emacspeak.googlecode.com/svn/trunk/lisp/g-client/</span>
<span class="n">cd</span> <span class="n">g</span><span class="o">-</span><span     class="n">client</span>
<span class="n">make</span>
....
```

What am I missing? Why isn't the syntax hilighting turned off for the block?

**Comment by waylan** [comment]
Because `'markdown.extensions.codehilite' != 'codehilite'`. Try this command instead:

```
python -m markdown -x markdown.extensions.codehilite -x meta -c opts.yml test.md
```

The two need to match exactly. If it helps, the old way of only using the last part of an extension name only will stop working in the release after next and is discouraged. And as support for YAML config files is new, we only included support for the new requirement, but you have to use it everywhere for it to work. Perhaps that last part needs to be documented better.
