### ISSUE TITLE
Treeprocessor – Difference between docs and inline comment

### ISSUE THREAD

**Issue by stianjensen** [Python-Markdown/markdown#375]
In the documentation for the Treeprocessor (https://pythonhosted.org/Markdown/extensions/api.html#treeprocessors) it says that:

> A Treeprocessor should inherit from markdown.treeprocessors.Treeprocessor, over-ride the run method which takes one argument root (an Elementree object) and **returns either that root element or a modified root element.**

In the inline comments for the run method in the treeprocessor class, it says:

> Subclasses of Treeprocessor should implement a `run` method, which
>         takes a root ElementTree. This method can **return another ElementTree
>         object, and the existing root ElementTree will be replaced, or it can
>         modify the current tree and return None.**

What is the correct usage?

**Comment by waylan** [comment]
Actually both are correct (neither is all-inclusive). In other words, you can return a new ElementTree object, return a modified ElementTree object, or return `None`. If you return `None`, the existing ElementTree object is used. However, as all Python variables point to objects by reference, if you modify the existing ElementTree object before returning `None`, those changes will be retained.  As Python functions and methods return `None` by default (if there's no `return` statement), if feels natural to just make the modification to the object and leave out the `return` statement altogether.

The [code](https://github.com/waylan/Python-Markdown/blob/master/markdown/__init__.py#L380) that calls the treeprocessors is actually pretty simple (only four lines). Notice that a copy is made every time `None` is _not_ returned. Which suggests that returning `None` is likely to be more efficient. The docs should probably be updated to recommend that as the expected behavior and indicate that returning an object (new or modified) is a secondary alternative.
