### ISSUE TITLE
Python-Markdown calls logging.captureWarnings on import

### ISSUE THREAD

**Issue by mitya57** [Python-Markdown/markdown#384]
Forwarding from [Debian bug 776591](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=776591):

> python-markdown in jessie calls `logging.captureWarnings(True)` on import,
> unconditionally.  For a library, this is unbelievably antisocial.
> Logging should be left in control of the application.

Can I remove that maybe? That call is in two places: in `__init__.py` and `extensions/headerid.py`.

**Comment by waylan** [comment]
Just be sure that when the commandline script (defined in markdown__main__.py) runs, that captureWarnings is True. My recollection is that captureWarnings has to be set in the module the warnings are issued in, but  perhaps I'm wrong about that. Have at it.

**Comment by mitya57** [comment]
What should be the expected behaviour? When running the commandline script with, for example, `-v` and `-x headerid`, I don't get the warning about `headerid` being deprecated even with the current code.

Do you have a test case that I can use to make sure I don't change the commandline script behavior?

**Comment by waylan** [comment]
@mitya57 by the time I figured out why the warnings weren't being logged, I had a solution, so I just committed it.

**Comment by mitya57** [comment]
Thank you!

**Comment by waylan** [comment]
Oh and one other thing, if Debian doesn't want to wait for the next release, I don't see any reason why this one commit couldn't be backported as 2.5.3. Yes, I realize that they are listing the current version as 2.5.1-2 and would probably up the version to 2.5.1-3. Personally, I install all Python packages via pip not the system package manager (yes I realize not everyone does and there even some legitimate reasons to support both). I just am not interested in getting involved in the politics there and will always ignore Debian's weird insistence on some alternate version numbering system. Besides, they update to newer versions way to slowly for me. I want the latest stable release from the developer, not the lasted stable release from Debian (which can be multiple versions behind and likely has bugs fixed in later releases -- not so stable in my view). But that's just my personal opinion. Whatever they want to do.

**Comment by mitya57** [comment]
Debian is frozen currently, so I can't do any updates in testing/unstable, and they will probably stay on 2.5.1.

2.5.2 is already available in experimental, and if you do another release I will put it there as well. But there is no need for you to do a new release just because of us.
