### ISSUE TITLE
codehilite: allow using JS highlighting libs instead of Pygments

### ISSUE THREAD

**Issue by szhorvat** [Python-Markdown/markdown#386]
The codehilite extension will just output code usable by e.g. [Prettify](https://code.google.com/p/google-code-prettify/) when Pygments is not present.

This is a request to make this user-controllable: make it possible to request codehilite to _not_ use Pygments.  This is for situations that Pygments cannot handle but e.g. Prettify can.

In my use case Pygments cannot handle Mathematica code (the quality is unusable and create a full Pygments Mathematica highlighter would be a lot of work).  There is already a good and maintained [Mathematica highlighter for Prettify](https://github.com/halirutan/Mathematica-Source-Highlighting) though.

**Comment by waylan** [comment]
This is (sort-of) already available. If Pygments is not available (the lib cannot be imported), then the language (if known) is assigned as a class to the wrapping `code` tag. Or perhaps you are looking to optionally (through a config setting) turn pygments off even if the lib is available to import. My position has been for some time that you shouldn't need the CodeHilite extension in that instance. Just use JavaScript to find and highlight your code blocks in the browser. If the JavaScript lib you are using has specific requirements for the code wrapping markup, then a simple extension specific to that lib's requirements may be the best way forward (which you can write and maintain yourself -- I'm not interested in doing so). In my experience, each and every JavaScript code highlighting lib has very different expectations and we can't possibly support them all. In fact, if we were to support anything, it would be what is described in the HTML5 spec as I have previously [explained](http://achinghead.com/marking-up-code.html) in great detail.

**Comment by szhorvat** [comment]
> My position has been for some time that you shouldn't need the CodeHilite extension in that instance. Just use JavaScript to find and highlight your code blocks in the browser.

The extension does a few useful things that won't happen without it:
1. it adds a class attribute to `<pre>` tags, which some highlighting libraries require
2. it makes it easy to control the highlighting language manually and passes on this information in a HTML5 compliant way
3. it can guess the highlighting language automatically, if set up that way

This is a lot more than a simple extension could do, or one that I (or many others who just want to write MarkDown) have the expertise/time to write.

Also, the _only_ change required is to expose the `pygments` variable set at the very beginning to users.  Considering how small that change is, why not incorporate it?

Finally, about the workaround of not installing Pygments: it's not even easy to install Python-Markdown without Pygments, as package managers will auto-install dependencies.  I do wonder how many people have Pyhon-Markdown installed without Pygments.  Since the "pygment-less" code is already there, why not make good use of it and give users the choice to use it?

**Comment by facelessuser** [comment]
I kind of agree with this.  Just because someone doesn't want to use Pygments with Python Markdown, it doesn't mean they don't ever want to use it.  A requirement stating: "if you don't want to use Pygments, don't install it" assumes that Pygments is only used for Python Markdown.  Maybe I have Pygments installed for purpose X, but would prefer Python Markdown to not use Pygments.

> Finally, about the workaround of not installing Pygments: it's not even easy to install Python-Markdown without Pygments, as package managers will auto-install dependencies.

Exactly.

**Comment by waylan** [comment]
> I kind of agree with this. Just because someone doesn't want to use Pygments with Python Markdown, it doesn't mean they don't ever want to use it. A requirement stating: "if you don't want to use Pygments, don't install it" assumes that Pygments is only used for Python Markdown. Maybe I have Pygments installed for purpose X, but would prefer Python Markdown to not use Pygments.

Ok, that is a fair point. I always use virtualenvs and each one only ever has the dependencies for its particular use so this is a non-issue for me. But I certainly shouldn't expect all users to operate that way.

> Finally, about the workaround of not installing Pygments: it's not even easy to install Python-Markdown without Pygments, as package managers will auto-install dependencies.

Not true. Pygments is not listed (programmatically) as a dependency for Python-Markdown. Therefore installing Python-Markdown will not install Pygments. You still have to manually install Pygments when using Python based package management. Of course, the various OS based package managers may or may not include Pygments as a dependency. But a standard `pip install markdown` will not get you Pygments. Thus my statement that it is "short of" possible.

> This is a lot more than a simple extension could do, or one that I (or many others who just want to write MarkDown) have the expertise/time to write.

Actually that is about the simplest extension I could think of. It would be a great place for someone to start out learning the Extension API.

The reason why I'm hesitant to do it myself is that inevitably someone will want different HTML that what I output. For example they want the language as a class on the `pre` tag rather than the `code` tag, or they want a specific prefix added to the class, or they want to add a second class to turn on line numbering or ... you get the idea. I have no interest in any of that. And that is why this is best suited to third party extensions. If you want to use it with lib X then you write an extension which outputs HTML compatible with lib X. If someone else wants output compatible with lib Y, then they can write their own extension which works with lib Y.

To be clear, whatever output I chose is the **only** option I will ever support. I will not entertain any alternations. If that output is not what you want, then it is of no use to you. Therefore, I have been of the opinion that it is better to avoid the problem by not supporting it at all. That's why I created the extension API. So you can do whatever you want. All I need to do is maintain the base package and a few very popular extensions.

**Comment by szhorvat** [comment]
Would you approve a pull request that simply exposes the `pygments` variable as a setting, but doesn't change anything about what HTML is output when `pygments=False` from the current situation?

**Comment by facelessuser** [comment]
> Not true. Pygments is not listed (programmatically) as a dependency for Python-Markdown. Therefore installing Python-Markdown will not install Pygments.

Cool.  I didn't realize this.  I can still see why people would want to disable it though.

> Would you approve a pull request that simply exposes the pygments variable as a setting, but doesn't change anything about what HTML is output when pygments=False from the current situation?

I don't think you would need to directly set `pygments=False`.  I think what would make more sense is an extension option.  That way it checks both: `if pygments and some_pygments_option`.  So the user controls the option switch but if pygments isn't installed, it won't do anything.  That's just my personal opinion of how I would do it.
