### ISSUE TITLE
Lists require newline before them

### ISSUE THREAD

**Issue by shadowfacts** [Python-Markdown/markdown#413]
Lists must have a newline before them, otherewise they aren't rendered as lists, just as plain text. This is incorrect, lists should not be required to have newline before them.

**Comment by ryneeverett** [comment]
> <s>The only restrictions are that block-level HTML elements — e.g. `<div>, <table>, <pre>, <p>`, etc. — must be separated from surrounding content by blank lines...</s>

<s>-- http://daringfireball.net/projects/markdown/syntax</s>

Oops. Retracted,

**Comment by waylan** [comment]
Where, exactly, is this rule stated here: http://daringfireball.net/projects/markdown/syntax?

As far as I can tell, no such requirement exists.   In fact, it is a bad idea. Of course, hard line breaks are permitted within a paragraph. Therefore, if such a rule existed, the middle of a paragraph could unexpectedly become a list.

To be fair, the rule @ryneeverett quotes above is referring specifically to raw HTML blocks, but I would certainly prefer that it referred to all block level constructs. Unfortunately, it does not. For example, you do not need a blank line after a header, but that is because headers can only ever be one line. Therefore this works:

```
# A Header
* A list item.
```

But personally I never do that. When I come back later, I might misread that. Therefore, I always put a blank line between all my block level constructs and I never get any surprises.

**Comment by waylan** [comment]
Here's an example of why such a rule is a bad idea:

```
If I recall correctly, the album was released in
1976. However, if didn't become the #1 seller until
2006. Can you guess which one it is?
```

So, should the second and third lines be list items? Of course not. But if a blank line was not required, that it exactly what you would get.

**Comment by Neepawa** [comment]
Okay, I'm commenting on an issue that was closed three years ago ...
Taking inspiration from John McFarlane's *cmark* (CommonMark) project, he resolved the issue you noted in the previous comment by declaring that the only time an apparent ordered list item in the middle of a paragraph (that is, not preceded by a blank line) would become a list item was if its number was "1."
Of course, if your intent is to be as true as possible to John Greuber's Markdown, your comment stands.

**Comment by facelessuser** [comment]
> Of course, if your intent is to be as true as possible to John Greuber's Markdown, your comment stands.

Yes, this is roughly the intent.  This is not CommonMark.  CommonMark is an interpretation/derivative of Markdown.
