### ISSUE TITLE
Smartypants removes needed newlines

### ISSUE THREAD

**Issue by munificent** [Python-Markdown/markdown#439]
Hey, long time listener first time caller. Python Markdown is wonderful. I even wrote [a book](https://github.com/munificent/game-programming-patterns) using it. After all these years, I finally stumbled onto a bug:

``` python
import markdown

source = """
A line that 'wraps' with
*emphasis* at the beginning of the next line.
"""

print markdown.markdown(source, ['smarty'])
print markdown.markdown(source)
```

This prints:

```
<p>A line that &lsquo;wraps&rsquo; with<em>emphasis</em> at the beginning of the next line.</p>
<p>A line that 'wraps' with
<em>emphasis</em> at the beginning of the next line.</p>
```

The first output is wrong because without the newline between `with` and `<em>emphasis</em>`, it renders as "with_emphasis_".

**Comment by mitya57** [comment]
This is because after matching the string against pattern's `getCompiledRegExp()`, the last match group does not contain the trailing newline character. I added some debug prints to `__applyPattern()` method of `InlineProcessor` and got this:

```
data was: "A line that 'wraps' with\n"
pattern was: "(\\s|&nbsp;|--|–|—|&[mn]dash;|&#8211;|&#8212;)'(?=\\w)"
final regexp was: "^(.*?)(\\s|&nbsp;|--|–|—|&[mn]dash;|&#8211;|&#8212;)'(?=\\w)(.*?)$"
match groups are: ('A line that', ' ', "wraps' with")
data is now: "A line that\x02klzzwxh:0000\x03wraps' with"
```

Perhaps we need to make sure that InlineProcessor gets strings without trailing `\n`, and they are added back later by the tree processor. But @waylan knows how that code works, not me…

**Comment by waylan** [comment]
``` py
>>> pattern = r"^(.*?)(\s|&nbsp;|--|–|—|&[mn]dash;|&#8211;|&#8212;)'(?=\w)(.*?)$"
>>> text = "A line that 'wraps' with\n"
>>> re.match(pattern, text).groups()
('A line that', ' ', "wraps' with")
>>> re.match(pattern, text, re.DOTALL).groups()
('A line that', ' ', "wraps' with")
```

Hmm, I was expecting that last line to return:

``` py
('A line that', ' ', "wraps' with\n")
```

Not sure what is going on here.

**Comment by waylan** [comment]
Ok, I think I see what is causing this. I also tried the following (note that I added text after the newline):

``` py
>>> text = "A line that 'wraps' with\n text"
>>> re.match(pattern, text).groups()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'groups'
>>> re.match(pattern, text, re.DOTALL).groups()
('A line that', ' ', "wraps' with\n text")
```

Those give the expected result. It appears there is some weird behavior when a newline character is the last character in the text. And because the very first character of the second line of the paragraph is markup (`*emphasis*`), by the time smartypants gets to it the emphasis inline pattern has already processed that text and the string left to operate on is `"A line that 'wraps' with\n"`. Not sure how to force a match that includes the newline character when it is the last character in the string (and I'm not sure why that doesn't work with the DOTALL flag to begin with).

**Comment by waylan** [comment]
I got it:

``` py
>>> pattern = r"^(.*?)(\s|&nbsp;|--|–|—|&[mn]dash;|&#8211;|&#8212;)'(?=\w)(.*)$"
>>> re.match(pattern, text, re.DOTALL).groups()
('A line that', ' ', "wraps' with\n")
```

Notice that I dropped the non-greedy quantifier from the final group ( `(.*)` instead of `(.*?)`). Not sure if removing it will break other things yet (I don't think so, but I don't recall why it was added in the first place). Will need to test that later.

**Comment by waylan** [comment]
Well, the non-greedy quantifier was added some time ago (see 34c680a6 L721). That was way back before 2.0. I will do a through test when I get home later today (unless someone beats me to it).

**Comment by munificent** [comment]
Amazingly fast turnaround, thank you! :grinning:

**Comment by waylan** [comment]
FYI, a new bugfix release (version 2.6.4) was just uploaded which includes this fix.

**Comment by mitya57** [comment]
@waylan: Thanks for the quick fix!

**Comment by munificent** [comment]
:metal:
