### ISSUE TITLE
Another table and inline code issue

### ISSUE THREAD

**Issue by facelessuser** [Python-Markdown/markdown#449]
Inline code in tables can't escape backtics like they can outside of tables.

```
``Test` | passes``

| Table | Test     |
| ----- | ------- |
| Broken | ``Test` | fails`` |
```

You can see it only accepts a surrounding backtic of 1.  Then it splits on the pipe.  The rest is lost because the table is only 2 columns wide.

``` html
<p><code>Test` | passes</code></p>
<table>
<thead>
<tr>
<th>Table</th>
<th>Test</th>
</tr>
</thead>
<tbody>
<tr>
<td>Broken</td>
<td><code>`Test</code></td>
</tr>
</tbody>
</table>
```

I do have intentions of looking into the reason why and providing a fix when I get time.

**Comment by facelessuser** [comment]
I guess I don't under stand this design.  Maybe someone can fill in the gaps. 

So this doesn't work (a real world example I am trying to use -- just showing some regex):

| Doesn't work | Works |
| --- | --- |
| ```[!\"\#$%&'()*+,\-./:;<=>?@\[\\\]^_`{|}~]``` | ```[!\"\#$%&'()*+,\-./:;<=>?@\[\\\]^`_`{|}~]```. |

This is extremely limited as you can only show grave accents in a table's inline code block if all accents have a pair.  Now I am sure there was some reasoning here, I just don't understand it.  What is more, I figured that I could probably put it in an html code block, but the html code block was split as well.

I am not sure why we alter the behavior in tables.  I feel like it should capture just as it would outside of tables.  I understand we are treating backticks as a special case in tables, but I don't understand the additional requirement of only if all grave accents are paired.  This is jarring for a user as the rules have clearly changed inside a table.  I feel like the row should be processed with a normal code pattern and then split.  We are already parsing code patterns special in tables, we might as well do it proper.

Before I put in work, I want to know if allowing normal backtick logic would be rejected; I don't want to waste time.  As it stands, I am simply forced to throw out my entire table and do raw html tables as Python Markdown can't handle an odd number of grave accents in a table, and I am afraid a pull to fix this might be rejected.

**Comment by waylan** [comment]
@facelessuser, yes, normal markdown inline markup should work in tables just the same as it does outside of tables.

Now for some background: My personal opinion is that tables are a part of the HTML that should be represented as raw HTML and not have any Markdown equivalent (I believe this opinion aligns with John Gruber's [thinking](http://daringfireball.net/projects/markdown/syntax#html) on the matter). Of course, not everyone agrees (nor should they). That said, I threw together the Table extension just so our "extra" would have feature parity with PHP's "extra". However, that was long before most Markdown parsers had extensions (Python-Markdown was the first to offer a third-party API AFAIK). It is not so important to have that feature parity with PHP's "extra" today. In fact, it appears that my extension was a little incomplete. Search closed issues and you will find numerous requests to add features to the extension, which I always have said no to. My position has been that if you don't like the way it works, use a third party extension (of which there are a few) or build your own.

When the issue was recently reported with code spans in tables, I almost closed it with the same response. However, it was a fair report (something that should clearly work was not working). And when someone provided a fix that appeared to address the issue, I just accepted it. Maybe I shouldn't have (I believe it is this patch which you are struggling to understanding). But with my lack of interest in the feature, I have no motivation to work on a solution.

I see two possible solutions moving forward:
1. Someone provides a better patch which addresses the issue without making any changes to the intended syntax or adding any features. Then, when version 3.0 is released, it gets broken out into its own package which someone else can take up and maintain.
2. Nothing happens to the 'included' table extension. A third party package becomes the standard and with the release of 3.0, the 'included' table extension is discarded.

**Comment by facelessuser** [comment]
Thanks for the background. I like simple table support in Markdown, but I also do prefer raw HTML if doing complicated tables.

I'll take a look at it sometime soonish and see if I can sort it out.  I'm not sure of the thinking behind the latest approach.  I almost would have preferred it to keep breaking on pipes then trade pipes for another bug that then still fails on pipes in other circumstances.  I feel like this should be able to be fixed; I guess I'll know better when I get around to digging in.
