### ISSUE TITLE
Feature Request: track/watch file for changes and auto generate output.

### ISSUE THREAD

**Issue by udiboy1209** [Python-Markdown/markdown#460]
Should track changes to the `.md` file, and auto-generate output to the file specified. Something like a `--watch` option can be added

**Comment by mitya57** [comment]
Python-Markdown is not an application, it's a library that allows you to write your own applications. It's relatively easy to write one you mention ­— just use a module like inotify (for Linux) or watchdog (which has different backends for different platforms) and Python-Markdown.

This is not something that can be implemented in Python-Markdown's command-line interface because it has different purposes and it doesn't even have an event loop.

(That's my own opinion, @waylan can have a different one but I doubt that.)

**Comment by waylan** [comment]
I agree with @mitya57, this is outside the scope of this project. You may find various "static site generators" which offer such a feature and more.
