### ISSUE TITLE
Support list inside quote

### ISSUE THREAD

**Issue by davidshen84** [Python-Markdown/markdown#467]
On GitHub, we could have list inside a quote, e.g.:

> a
> - 1
> - 2

However, the same code is generated as

```
<blockquote>\n<p>a\n  - 1\n  - 2</p>\n</blockquote>
```

Hence, lost the list formatting.

**Comment by waylan** [comment]
Hmm, interesting edge case. In fact, [most](http://johnmacfarlane.net/babelmark2/?normalize=1&text=+%3E+a%0A+++-+1%0A+++-+2) implementations do not work with that input. [This](http://johnmacfarlane.net/babelmark2/?normalize=1&text=%3E+a%0A%3E+-+1%0A%3E+-+2) doesn't even work:

```
> a
> - 1
> - 2
```

You need to have a blank line between your paragraph and your list, like [this](http://johnmacfarlane.net/babelmark2/?normalize=1&text=%3E+a%0A%0A%3E+-+1%0A%3E+-+2):

```
> a

> - 1
> - 2
```

... or [this](http://johnmacfarlane.net/babelmark2/?normalize=1&text=%3E+a%0A%3E%0A%3E+-+1%0A%3E+-+2):

```
> a
> 
> - 1
> - 2
```

Why? Because your input won't even work outside of a blockquote, like [this](http://johnmacfarlane.net/babelmark2/?normalize=1&text=a%0A-+1%0A-+2):

```
a
- 1
- 2
```

You need to do [this](http://johnmacfarlane.net/babelmark2/?normalize=1&text=a%0A%0A-+1%0A-+2):

```
a

- 1
- 2
```

Clearly, this is not a bug, but intended behavior.
