### ISSUE TITLE
extensions/tables.py:76 refers to undefined ‘unicode’ name

### ISSUE THREAD

**Issue by mitya57** [Python-Markdown/markdown#470]
The `tables` extension has this code:

``` python
try:
    if isinstance(cells[i], str) or isinstance(cells[i], unicode):
        c.text = cells[i].strip()
    else:
        # we've already inserted a code element
        c.append(cells[i])
except IndexError:  # pragma: no cover
    c.text = ""
```

On Python 3, it should fail with `NameError` because `unicode` is no longer a built-in type name.
Because it doesn't, maybe this code is unused and some part of it can be dropped? (Is the first check about `str` always True?)

**Comment by mitya57** [comment]
I have added a debug print statement and run the testsuite. As I guessed, type is always `unicode` on Python 2 and `str` on Python 3. So either we can simplify the code by dropping `if` here, or the test suite is incomplete and doesn't test all cases.

**Comment by waylan** [comment]
According to the PY34 [coverage report](https://travis-ci.org/waylan/Python-Markdown/jobs/122205591#L277), Line [80](https://github.com/waylan/Python-Markdown/blob/4d96f00fd3e4945b5c18d53ea81868bee5486c98/markdown/extensions/tables.py#L80) (the `else` clause to that `if` statement) is the only line without test coverage (same in [PY27](https://travis-ci.org/waylan/Python-Markdown/jobs/122205589#L275)). So yes, this never is `False` in the tests. It's possible this was an edge case I imagined in development which will never be met in the real word and we could simply remove the `if` statement, but I'd prefer to be cautious.

My guess is that the existing code was written before we had a unified codebase for PY2 and PY3 and it was simply missed when we unified everything. And it never errors because on PY3 the first expression (`isinstance(cells[i], str`) evaluates to `True` so the second is never even checked (as it is an `or` statement) and no error is raised.

The fix is easy. It should be `if isinstance(cells[i], until.string_type)`.

**Comment by waylan** [comment]
Okay, this was introduced in fb65ed1. Clearly I missed this in review. 

Perhaps we should create a test to give us 100% coverage. If that is not possible (the expression is never `False`) then we can remove the `if` expression. Otherwise, change it to `if isinstance(cells[i], until.string_type)`.
