### ISSUE TITLE
Output to markdown

### ISSUE THREAD

**Issue by Asarew** [Python-Markdown/markdown#494]
Is there a possibility to output the result back to markdown files so you can use the extensions as a transpiler/polyfill?

If not, i think this would be a great addition for using the output markdown files in a hosted solution that don't support the [Python-Markdown extensions](https://pythonhosted.org/Markdown/extensions/index.html).

**Comment by waylan** [comment]
Are you asking for the Markdown files to be output instead of HTML or in addition to HTML? I'm pretty sure we are not interested in the former (what useful purpose would that server, they are already Markdown files) and the later could likely be accomplished via a Plugin once we add the Plugin API (see #206).

If instead you are looking for a way to transform Markdown files which use extension syntax to Markdown files which do not use extension syntax, then this is the wrong tool for the job. Even Pandoc can't do most of that. The reason extensions exist is because Markdown has no concept of the features provided by the extensions. That being the case, plain Markdown has no way of representing those features outside of raw HTML.

**Comment by brendo** [comment]
I actually implemented this very thing last week at my workplace. We wanted to invoke certain behaviour when different URL schemes were used in links, eg. `[link](jsonschema:/path/to/schema)` would trigger a JSON Schema visualisation of the desired source, and then replace the markdown to be `[link](/path/to/visualisation/)`.

To do this, I implemented a custom Renderer which simply took the arguments and returned a string of Markdown. The most complicated part was nested lists and I'm sure there's other nuances I missed, but it's working well for our current scenario.

**Comment by waylan** [comment]
Hmm, so I just reread my response above and it makes no sense. Apparently I wasn't paying attention and thought this was posted to a different project. In any event, I am not interested in maintaining a Markdown renderer. But it is certainly possible for you to provide your own.
