### ISSUE TITLE
Is there a plugin for frontmatter metadata?

### ISSUE THREAD

**Issue by nottrobin** [Python-Markdown/markdown#497]
Rather than the existing [metadata extension](https://pythonhosted.org/Markdown/extensions/meta_data.html#syntax), I'd rather use YAML frontmatter in my markdown files.

Is there a plugin for this?

**Comment by waylan** [comment]
I've come to conclude that it is better to process front-matter with a separate wrapping preprocessor, rather than an extension to the parser itself. Therefore I have created [docdata](https://github.com/waylan/docdata), which can handle MultiMarkdown style meta data as well as YAML data. In the future I expect this will replace the existing extension (as the separate "wrapper" that it is now, rather than as an extension).

As there is no actionable item here, I am closing this.

**Comment by nottrobin** [comment]
@waylan Yep, fair enough. Thanks.

For posterity, here's [my solution](https://gist.github.com/nottrobin/f0b024d4484daa4f5fd08f166a4dc1c6):

``` python
import frontmatter  # https://pypi.org/project/python-frontmatter/
import markdown

def parse_markdown(filepath):
    markdown_parser = markdown.Markdown(extensions=markdown_extensions)
    file_parts = frontmatter.load(filepath)

    return {
        'html': markdown_parser.convert(file_parts.content),
        'metadata': file_parts.metadata
    }
```

**Comment by mlcdf** [comment]
@nottrobin I was looking to do just this. Thank you!

And of course, thank you @waylan for this project.

**Comment by SHxKM** [comment]
@nottrobin Always great when someone shares his solution to save others time. Thanks!
