### ISSUE TITLE
URLs with colons don't work

### ISSUE THREAD

**Issue by Polsaker** [Python-Markdown/markdown#519]
Input:
`[test](http://test.com/foo:bar)`

Expected output:
`<a href="http://test.com/foo:bar">test</a>`

Actual output:
`<a href>test</a>`

**Comment by waylan** [comment]
Hmm, I can't seem to replicate this:

```py
>>> import markdown
>>> markdown.version
'2.6.7'
>>> markdown.markdown('[test](http://test.com/foo:bar)')
u'<p><a href="http://test.com/foo:bar">test</a></p>'
```

**Comment by Polsaker** [comment]
Just double checked, and it only happens when I use `safe_mode='escape'`
```
>>> import markdown
>>> markdown.version
'2.6.7'
>>> markdown.markdown('[test](http://test.com/foo:bar)', safe_mode='escape')
'<p><a href="">test</a></p>'
```

**Comment by waylan** [comment]
Ahh, that makes more sense. That does appear to be a bug, although `safe_mode` is being [deprecated][1], so I'm not sure it makes sense to bother fixing it. In fact, one of the reasons `safe_mode` is being deprecated is that is it nearly impossible to get these sorts of things correct (there will always be an edge case we miss).

[1]: https://pythonhosted.org/Markdown/release-2.6.html#safe_mode-deprecated

**Comment by waylan** [comment]
Okay, so I just reviewed the code and this is *not* a bug. If a colon exists in a URL's "path", "parameters", "query" or "fragment", the URL is assumed to be malicious code and stripped out. See the [code comments][1] for an explanation. Note that the URL in those comments (`http://ha.ckers.org/xss.html`) is now dead; the replacement page is <https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet>. For an easier to understand overview which explains how this relates to Markdown, I recommend reading [Markdown and XSS][2]. 

If you want colons in your URLs, then you can't use `safe_mode`. Of course, `safe_mode` is not actually "safe" so you should probably not be using it anyway. This is being closed as this behavior is not a bug but intentional.

[1]: https://github.com/waylan/Python-Markdown/blob/master/markdown/inlinepatterns.py#L375
[2]: https://michelf.ca/blog/2010/markdown-and-xss/
