### ISSUE TITLE
Incorrect rendering of blockquotes followed by an hr

### ISSUE THREAD

**Issue by belak** [Python-Markdown/markdown#531]
See https://johnmacfarlane.net/babelmark2/?text=attached%0A%3E+irrelephant+content%0A%3E%0A%3E+***%0A---%0A%3E+see

Originally reported here: https://bitbucket.org/site/master/issues/13742/block-quote-horizontal-line-parsing-issue

I don't know exactly what's causing this, but something's a little off.

**Comment by waylan** [comment]
If  the rules required blank lines between block level constructs we wouldn't have to deal with bugs like this `</rant>`. Turns out, [adding some blank lines][1] makes for a reasonable workaround. Sigh.

Yeah, something is definitely "a little off." I'll take a look when I find the time (unless someone else beats me to it). Thanks for the report.

[1]:  https://johnmacfarlane.net/babelmark2/?normalize=1&text=attached%0A%3E+irrelephant+content%0A%3E%0A%3E+***%0A%0A---%0A%0A%3E+see

**Comment by waylan** [comment]
Ignoring the funky output we are getting, the real question is what should be the correct output for that input. Consider this [input][0]:

```md
> # foo
# bar
```

Most implementations (including this one) render that as (whitespace normalized):

```html
<blockquote>
  <h1>foo</h1>
</blockquote>
<h1>bar</h1>
```

However, others (including the reference implementation) render that as (whitespace normalized):

```html
<blockquote>
  <h1>foo</h1>
  <h1>bar</h1>
</blockquote>
```

And the rules make a [case][1] for that behavior:

> Markdown allows you to be lazy and only put the > before the first line of a hard-wrapped paragraph:

Which suggests that if you want out of a blockquote, then you need a blank line. It might make resolving this bug easier, but I expect it will be a backward incompatible change for many users.

So the path to resolving this issue depends on the answer to the following question: 

__Should Example 1's output be the same as Example 2's output?__

__Example 1:__

```md
> # foo
# bar
```

__Example 2:__

```md
> # foo

# bar
```

[0]: http://johnmacfarlane.net/babelmark2/?normalize=1&text=%3E+%23+foo%0A%23+bar%0A
[1]:  http://daringfireball.net/projects/markdown/syntax#blockquote

**Comment by waylan** [comment]
Just checked the very thorough [CommonMark Spec][1] and our current behavior matches with regard to the headers in a blockquote (there is also an example of a HR following a blockquote with no blank line). But CommonMark diverges from the original Markdown rules and is not something Python-Markdown necessarily follows. However, the old-school implementations (those before CommonMark) seem to be split in half on this. Therefore,  I'm inclined to leave the behavior (for the header case) as-is.

So the answer to my question seems to be: __Yes, Example 1 and Example 2 should generate the same output.__ That being the case, we have a bug to resolve rather than a change in behavior to implement.

[1]: http://spec.commonmark.org/0.27/#block-quotes

**Comment by waylan** [comment]
The absolute minimum test case to replicate this seems to be:

```md
foo
> bar
> ***
---
> baz
```

Which is a very specific (and odd) edge case. It's no wonder this is the first report of it.

**Comment by SidIcarus** [comment]
Quickly putting this together but... 

Considering `<p>` differs in output pattern then `<h1>`, should they generate the same output?
[Ex. w/ p comparison][ht] 

Then definition of 'hard-wrapping' and 'soft-wrapping' come to mind.  

consider your examples with spaces at the end.
[Ex. w/ spaces][hs]
[Ex. w/ spaces but p instead of h1][ts]

adding a following block quote 
[Ex. w/ spaces & blockquote][hsh]
[Ex. w/ spaces & blockquote but p instead of h1][tst]

[hs]: <https://johnmacfarlane.net/babelmark2/?normalize=1&text=%3E+%23+foo%0A%23+bar%0A%0A%3E+%23+foo++%0A%23+bar%0A%0A%3E+%23+foo%0A%0A%23+bar%0A%0A%3E+%23+foo++%0A++%0A%23+bar>
[ts]:<https://johnmacfarlane.net/babelmark2/?normalize=1&text=%3E+foo%0Abar%0A%0A%3E+foo++%0Abar%0A%0A%3E+foo%0A%0Abar%0A%0A%3E+foo++%0A++%0Abar>
[hsh]: <https://johnmacfarlane.net/babelmark2/?normalize=1&text=%3E+%23+bar%0A%23+baz%0A%3E+%23+foo%0A%0A%3E+%23+bar%0A%23+baz++%0A%3E+%23+foo>
[tst]: <https://johnmacfarlane.net/babelmark2/?normalize=1&text=%3E+bar%0Abaz%0A%3E+foo%0A%0A%3E+bar++%0Abaz%0A%3E+foo>
[ht]: <https://johnmacfarlane.net/babelmark2/?normalize=1&text=%3E+%23+foo%0A%23+bar%0A%0A%3E+foo%0Abar%0A%0A%3E+%23+foo%0A%0A%23+bar%0A%0A%3E+foo%0A%0Abar>

**Comment by waylan** [comment]
@SidIcarus it should be noted that a header can only ever contain one line. Therefore there is always a difference in behavior between two lines of a paragraph and two header lines without a blank line between them. Therefore, your examples are not really relevant to this case.

Given the minimum input for this bug:

```md
foo
> bar
> ***
---
> baz
```

The only output I would find acceptable would be:

```html
<p>foo</p>
<blockquote>
  <p>bar</p>
  <hr />
</blockquote>
<hr />
<blockquote>
  <p>baz</p>
</blockquote>
```

**Comment by SidIcarus** [comment]
@waylan Woops. I knew that. I responded too quickly and didn't review it.

Also, why `<p>baz</p>` and not `<blockquote> <p>baz</p> </blockquote>`  or `<p>> baz</p>` ?

**Comment by waylan** [comment]
> Also, why `<p>baz</p>` and not `<blockquote> <p>baz</p> </blockquote>`

Good catch. I edited the comment and fix it. Thanks.

**Comment by facelessuser** [comment]
I'll pick this one up as well.

**Comment by waylan** [comment]
Thanks to @facelessuser for the fix. This will be available in the next release.
