### ISSUE TITLE
`\(` and `\)` become `(` and `)` in HTML output

### ISSUE THREAD

**Issue by renfeisong** [Python-Markdown/markdown#532]
I am debugging MathJax with Python-Markdown and noticed a wired issue. If the markdown markup contains `\(` or `\)`, it will be converted to `(` or `)` in the rendered HTML. It seems that Python-Markdown is treating the backslash in `\(` as an escape character, instead of taking its “face value.” Strangely, other similar sequences such as `\n` are processed correctly. Simple example:

```python
import markdown
print markdown.markdown('\\(\\)\\n')
```

Output:

```html
<p>()\n</p>
```

**Comment by facelessuser** [comment]
Yup.  That is a very bad syntax for Markdown.  I would not advise using that.  I would go with `$...$` and `$$...$$`.  Of course having an extension to also parse and ensure preservation isn't a bad idea either.  You could give this a try: http://facelessuser.github.io/pymdown-extensions/extensions/arithmatex/.  But there are other extensions that can do the job: https://github.com/waylan/Python-Markdown/wiki/Third-Party-Extensions.

If none of those suite you, you can always roll your own extension.

> Strangely, other similar sequences such as \n are processed correctly.

This behavior has always bothered me a little, I much prefer all chars to be escapable as then you don't have to remember what can and cannot be escaped. But Markdown (according to spec) has very specific chars that can be escaped.  Some extensions can add additional escapes.  The default allowed escapes are chosen specifically to help in navigating around the Markdown syntax.  You need to be able to escape `()` because it is often used in Markdown syntax, so to keep it from turning into a link or something like that, you need a way say "hey, I want a literal `()`".

Anyways, hope that helps.

**Comment by waylan** [comment]
The [rules][1] define a specific set of characters which are escapable and parentheses are on that list as they are used in the Markdown syntax for inline links. Otherwise, how would you escape them? That is never going to change and this is being closed for that reason.

That said, as @facelessuser points out, various extensions exist which handle escaping in different ways. If you are trying to use MathJax, then you need to use one of the available extensions which works around this conflict between Markdown and MathJax syntax (or create your own). While [Arithmatex][2] is one option (linked to above and and developed by @facelessuser), others are listed in the [wiki][3].

[1]: http://daringfireball.net/projects/markdown/syntax#backslash
[2]: http://facelessuser.github.io/pymdown-extensions/extensions/arithmatex/
[3]: https://github.com/waylan/Python-Markdown/wiki/Third-Party-Extensions#math--latex

**Comment by mitya57** [comment]
You may also find my [python-markdown-math](https://github.com/mitya57/python-markdown-math) extension useful. It supports the `\(...\)` and `\[...\]` delimiters, so there is no need to care about space around dollar signs.

It also generates proper MathJax `<script>` tags, so there is no need to use the MathJax tex2jax processor, which many other extensions are relying on.

**Comment by facelessuser** [comment]
Nice.  Good idea wrapping it in the script... Seems so obvious now :).
