### ISSUE TITLE
[Bug] & → &amp; in URL rendering

### ISSUE THREAD

**Issue by Kristinita** [Python-Markdown/markdown#556]
### 1. Summary

I don't find, how I can convert ampersands: `&` → `&amp;` in URL's. I use Python-Markdown via [**Pelican**](http://docs.getpelican.com/en/stable/).

### 2. Settings

I have a file `SashaHappyBirthday.md`, it contents:

```markdown
ValeriyaSpeller suggests in [**status bar**](https://www.google.ru/search?q=status+bar&newwindow=1&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi-j9WygojTAhVGiSwKHfRhATYQ_AUIBigB&biw=1173&bih=729).
```

### 3. Steps to reproduce

```shell
D:\Киролайна>python -m markdown SashaHappyBirthday.md
<p>ValeriyaSpeller suggests in <a href="https://www.google.ru/search?q=status+bar&amp;newwindow=1&amp;source=lnms&amp;tbm=isch&amp;sa=X&amp;ved=0ahUKEwi-j9WygojTAhVGiSwKHfRhATYQ_AUIBigB&amp;biw=1173&amp;bih=729">status bar</a>.</p>
```

### 4. Expected behavior

Don't convert URL's.

### 5. Actual behavior

`&` → `&amp;` in URL's. I get incorrect URL in output.

### 6. Environment

**Operating system and version:**
Windows 10 Enterprise LTSB 64-bit EN
**Python:**
3.6.1
**Python-Markdown:**
2.6.8

Thanks.

**Comment by waylan** [comment]
This is the expected behavior. See [Babelmark][1]. The two implementations which give the output you expected are definitely the outliers.

[1]: http://johnmacfarlane.net/babelmark2/?normalize=1&text=ValeriyaSpeller+suggests+in+%5B**status+bar**%5D(https%3A%2F%2Fwww.google.ru%2Fsearch%3Fq%3Dstatus%2Bbar%26newwindow%3D1%26source%3Dlnms%26tbm%3Disch%26sa%3DX%26ved%3D0ahUKEwi-j9WygojTAhVGiSwKHfRhATYQ_AUIBigB%26biw%3D1173%26bih%3D729).

**Comment by waylan** [comment]
And in fact, if the browser displays that link, it works exactly as it should (the browser understands the `&amp;` and converts it properly). There is no error here.

**Comment by Kristinita** [comment]
> This is the expected behavior.

> And in fact, if the browser displays that link, it works exactly as it should (the browser understands the &amp; and converts it properly). There is no error here.

@waylan,

### 1. Steps to reproduce

1. I copy and paste first link in browser URL bar → I press <kbd>Enter</kbd>; I copy and paste second link in browser URL bar → I press <kbd>Enter</kbd>.

2. I use [**Clickable URL**](https://github.com/leonid-shevtsov/ClickableUrls_SublimeText) Sublime Text package → I move carriage to first link → I run command `open_url_under_cursor`; I move carriage to second link → I run command `open_url_under_cursor`.

3. I use [**Open URL**](https://github.com/noahcoad/open-url) Sublime Text package → I move carriage to first link → I run command `open_url`; I move carriage to second link → I run command `open_url_under_cursor`.

4. I [**click to first and second URL**](https://superuser.com/a/532073/572069) in ConEmu — [**most popular terminal for Windows**](http://stackoverflow.com/a/10904494/5951529).

### 2. Expected behavior

+ `https://www.google.ru/search?q=status+bar&newwindow=1&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi-j9WygojTAhVGiSwKHfRhATYQ_AUIBigB&biw=1173&bih=729`

![Expected](http://i.imgur.com/euZtMWO.png)

### 3. Actual behavior

+ `https://www.google.ru/search?q=status+bar&amp;newwindow=1&amp;source=lnms&amp;tbm=isch&amp;sa=X&amp;ved=0ahUKEwi-j9WygojTAhVGiSwKHfRhATYQ_AUIBigB&amp;biw=1173&amp;bih=729`

![Actual](http://i.imgur.com/niIQPvr.png)

### 4. Environment

I tested in 3 browsers without addons and user settings → I get actual behavior, not expected 3 times:

+ Firefox 52.0.2 (64-bit),
+ Chrome 56.0.2924.87 (64-bit),
+ Opera 38.0.2220.41 (64-bit).

Operating system:

+ Windows 10 Enterprise LTSB 64-bit EN

Thanks.

**Comment by waylan** [comment]
> I copy and paste both links in browser URL bar 

This is your problem. If however, you display your HTML in a browser and click the link is works fine. For example, visit [BabelMark][1] and use the "preview" tab. This will display the HTML as it would look in a page. If you click the link it works fine.

[1]: http://johnmacfarlane.net/babelmark2/?normalize=1&text=ValeriyaSpeller+suggests+in+%5B**status+bar**%5D(https%3A%2F%2Fwww.google.ru%2Fsearch%3Fq%3Dstatus%2Bbar%26newwindow%3D1%26source%3Dlnms%26tbm%3Disch%26sa%3DX%26ved%3D0ahUKEwi-j9WygojTAhVGiSwKHfRhATYQ_AUIBigB%26biw%3D1173%26bih%3D729).

**Comment by Kristinita** [comment]
@waylan, I wrote example 1 for example. Please, to see examples 2—4. I can't fast open link in popular text editor — Sublime Text — and terminal — ConEmu.

1. Can you tell any reasons (others besides “because in Babelmark”) , why Markdown to HTML tools developers convert `&` to `&amp;`? This adds to the difficulties for users.
1. Can I personally set don't convert `&` to `&amp;` in URL's?

Thanks.

**Comment by waylan** [comment]
> Can you tell any reasons (others besides “because in Babelmark”) , why Markdown to HTML tools developers convert `&` to `&amp;`? This adds to the difficulties for users.

This decision was made over ten years ago (before I even knew what Markdown was), so no I can't tell you why. However, in all the years I'm been using Markdown you are the first person I've encountered who found it to be a problem (that I recall anyway). It is only a problem if you copy a URL from the generated source, which is an edge case. If you generate HTML and view it in the browser (the normal use case) it works fine.

However, I can speculate on how the current behavior came to be. The original reference implementation (`markdown.pl`) simply does a series of regex substitutions. The order in which those are done is very important. For example the code span regex must be the first inline regex run so that other regex don't match again Markdown syntax inside a code span. Another regex near the top of the list is for raw HTML (HTML entities included). My guess is that the regex for HTML entities was run before the regex for links and as there was no actual problem in usage, it was never considered a bug. Then, as Markdown gained popularity and various other implementations were created, they all copied the reference implementation's behavior.

Some believe that one of the biggest problems with Markdown is that much of its behavior is not actually defined in the rules, but is implied by the behavior of the reference implementation. However, the creator of Markdown has stated that he considers Markdown complete and will not entertain any changes. That is why (at least in part) [CommonMark] was created. As I understand it, the creators of CommonMark are attempting to create a Markdown fork for which there is a clearly defined specification for all behavior. However, I was curios and checked the CommonMark spec, and it does not address this specific edge case ([example 470] includes a query string, but only one key/value pair is used so there is  no `&` in the example and [example 472] includes an HTML entity, but not in a query string). I'm not sure if they simply missed it or if it was left out intentionally. You could always [ask] them. Although, I did [try it] and the behavior appears to be the same.

For the record, Python-Markdown is a Markdown parser, not a CommonMark parser. I find the original Markdown sufficient myself and have left others to create CommonMark implementations.

> Can I personally set don't convert `&` to `&amp;` in URL's?

You are free to create your own extension. Python-Markdown's extension API allows you to modify any and all parts of the parser. See the [tutorial] to get started.

[CommonMark]: http://commonmark.org/
[example 470]: http://spec.commonmark.org/0.27/#example-470
[example 472]: http://spec.commonmark.org/0.27/#example-472
[try it]: http://spec.commonmark.org/dingus/?text=%5Blink%5D(http%3A%2F%2Fexample.com%3Ffoo%3Dbar%26baz%3D42)%0A%0A
[ask]: http://talk.commonmark.org/
[tutorial]: https://github.com/waylan/Python-Markdown/wiki/Tutorial:-Writing-Extensions-for-Python-Markdown

**Comment by facelessuser** [comment]
As you mentioned, the main motivation behind this request was the behavior of a Sublime Text plugin and ConEmu not meeting your expectations. Maybe browser like logic should be added to those instead of trying to massage Markdown output to meet their expectations.  If a browser knows how to read that source, then those plugins/tools should probably have that support added as HTML source **is** for the browser.

**Comment by facelessuser** [comment]
At least for Sublime Text, I don't see why the author couldn't add a secondary, optional "open link" command for HTML source that could be bound to a different shortcut.  The reality, is that there is a difference in HTML between actual links and source links at times.
