### ISSUE TITLE
[Feature request] Resolve section_number conflict [Don't fix]

### ISSUE THREAD

**Issue by Kristinita** [Python-Markdown/markdown#560]
### 1. Summary

It would be nice, if I use [**section_number**](https://github.com/getpelican/pelican-plugins/tree/master/section_number) Pelican plugin, it will work with [**Table of Contents**](https://pythonhosted.org/Markdown/extensions/toc.html) extension.

### 2. Settings

For example,

Part of my `pelicanconf.py` file:

```python
MARKDOWN = {
    'extension_configs': {
        'markdown.extensions.toc': {'permalink': True},
    },
    'output_format': 'html5',
}

PLUGIN_PATHS = ['pelican-plugins']
PLUGINS = [
    'section_number',
]
```

I use `section_number` plugin with [**small patch**](https://github.com/getpelican/pelican-plugins/pull/883) for automatically add numbers in headers.

### 3. Steps to reproduce

I run `pelican content` command for build site.

### 4. Expected behavior

If I comment or delete `'markdown.extensions.toc': {'permalink': True},` line:

```html
<h3 id="optional">6.2. Optional<a class="headerlink" href="#optional" title="Permanent link">¶</a></h3>
```

![Expected](http://i.imgur.com/6aB9J4n.png)

### 5. Actual behavior

```html
<h3 id="optional">Optional<a class="headerlink" href="#optional" title="Permanent link">¶</a></h3>
```

![Actual](http://i.imgur.com/hs1q1VO.png)

### 6. Not helped

1. I move markdown settings with `'markdown.extensions.toc': {'permalink': True},` to the end of `pelicanconf.py` → I get same behavior.
1. [**headerid**](https://github.com/getpelican/pelican-plugins/tree/master/headerid) Pelican plugin don't work with Markdown.
1. [**HeaderAnchor**](http://facelessuser.github.io/pymdown-extensions/extensions/headeranchor/) Python Markdown extension deprecated. I don't find another extensions/tools to solve my problem.

### 7. Environment

**Operating system and version:**
Windows 10 Enterprise LTSB 64-bit EN
**Python:**
3.6.1
**Pelican:**
3.7.1
**Markdown:**
2.6.8

Thanks.

**Comment by facelessuser** [comment]
As far as the deprecated `HeaderAnchor` extension is concerned, I personally switched to using `permalink` option in `Toc` and use pure CSS to pull off the effect.  In the [documentation](http://facelessuser.github.io/pymdown-extensions/extensions/headeranchor/), you see the header links looking github-ish, but this is not done with `HeaderAnchors` anymore, but with [CSS](https://github.com/facelessuser/pymdown-extensions/blob/master/doc_theme/extra.css#L23).

As far as your issue with section numbers, this may be an issue that needs to be resolved in the `section_numbers` extension.  I'm pretty sure this is something outside of Python Markdown's control.  It may be that you need to modify `section_numbers` or create your own extension to provide the same functionality.

**Comment by waylan** [comment]
First of all, Pelican is is a third party project which happens to use Python-Markdown as a library. However, we don't have anything to do with Pelican ourselves. We can't help with anything that is not a Python-Markdown extension. Additionally, any third-party extensions which are not packaged with Python-Markdown should be addressed with the specific developer/project where they originated.

That said, you apparently are having some problem with the TOC extension, which is part of Python-Markdown. Everything else is outside this project and (without going to look it up) I don't know what they purport to do. Nevertheless, if I understand correctly, you want the permalinks on headers to only be visible when hovering over the header, but not at other times. Is that correct?

For that to work, you **must** have the permalinks in the document at all times. The trick is to hide them until they should be visible, detect when that is, and switch the "hidden" property off. Therefore, this is not something that can be done at the "Markdown" level. Well, except for generating the permalinks. Therefore, you want to leave the setting in place for the TOC extension to include the permalinks in the document. 

To hide/show the permalinks you need to make some alterations to your Pelican theme, which is out-of-scope for me to help you with. However, the basic idea is to use CSS (and/or JavaScript) to toggle the visible/hidden state of the permalinks. Each permalink has the class `headerlink` assigned to make this easier. @facelessuser linked to how he has accomplished that, which should be a good place to start.

**Comment by Kristinita** [comment]
> Nevertheless, if I understand correctly, you want the permalinks on headers to only be visible when hovering over the header, but not at other times. Is that correct?

No. 

Problem — if I use `markdown.extensions.toc`, I don't get numbers in headers in rendered HTML, generated by plugin `section_number`, see examples in 4 and 5 items of my post.

If I don't use `markdown.extensions.toc`, I get numbers in headers: `7`, `7.1`, `7.2`, `8` in example.

![Expected](http://i.imgur.com/6aB9J4n.png)

Thanks.

**Comment by facelessuser** [comment]
Do you know how and when section numbers get injected via this section number Pelican plugin?  The approach of how section numbers works could be very insightful to why this isn't working with Toc.

I don't necessarily think this is Toc's problem.  I suspect the way these two things work together might just be incompatible, but I haven't used Pelican, so I can't even begin guessing.

Writing a section number extension specifically for Python Markdown might be the best option than trying to figure out why Toc isn't playing nice (or why section numbers isn't playing nice) with the other.  This is personally the route I would go, and just write something native for Python Markdown.

**Comment by waylan** [comment]
I agree with @facelessuser. This is not something that we support out-of-the-box, but I'm not aware of any reason why it shouldn't work. Presumably, whatever method the Pelican plugin is using is being broken by the permalinks. You have two options: 1) address this with whoever created the Pelican plugin (ask them to include support for headers which include permalinks), or 2) create a third Python-Markdown extension which adds this support directly to Python-Markdown.

**Comment by Kristinita** [comment]
> This is personally the route I would go, and just write something native for Python Markdown.

@facelessuser, perhaps, better write package for Sublime Text?

### 1. Argumentation

Python Markdown extensions don't work with unsaved buffers. 1—10 times in a day I use unsaved buffers.

+ For Stack Overflow and Sublime Text Forum posts I use [**GhostText**](http://ru.stackoverflow.com/a/595371/199934) package.
+ For GitHub Issues (include this issue) I use [**GitHubIssue**](https://packagecontrol.io/packages/GitHubIssue) package.

In Sublime Text I don't find package, that add numbers in Markdown headers, I need write numbers manually.

Thanks.

**Comment by waylan** [comment]
This is not a feature that I have any need for personally. As I work on Python-Markdown in my spare time, I'm only going to work on features I need and/or care about. The extension API exists so that others can implement whatever features they want. @Kristinita you are free to create an extension which does what you want. I'm closing this as there is no action that I will be taking.

**Comment by facelessuser** [comment]
@Kristinita, If we're talking about 3rd party SublimeText plugins that have nothing to do with Python Markdown, such as GhostText and GithHubIssue (I don't think these even use Python Markdown), then yes, a Python Markdown extension is not going to help.

> Python Markdown extensions don't work with unsaved buffers.

You can send an unsaved buffers to Python Markdown.  Whatever you are using may not employ Python Markdown in that manner, but it can be done quite easily.  I assume you are talking about unsaved buffers in Sublime Text; I have personally sent unsaved buffers from Sublime Text to Python Markdown.

> In Sublime Text I don't find package, that add numbers in Markdown headers, I need write numbers manually.

I'm speaking strictly from a Python Markdown perspective.  Python Markdown is extensible; therefore, a section number extension **can** be written for it.  Since the main issue here is that Pelican's plugin is having difficulties being compatible with all of Python Markdown's extensions, you could write a new extension that is compatible.  Having something that integrates with Sublime Text and/or other Sublime Text packages is an entirely different topic.

I do realize though that not everyone who uses Python Markdown are programmers, so maybe this isn't something that is easily accessible to you.  I would consider raising this issue on the Pelican plugins issue page.  I feel like this is something they should reasonably be able to account for, but it is possible it might be out of scope of what they want to support.

Hopefully you will be able to find what you need.
