### ISSUE TITLE
Implement references like in pandoc

### ISSUE THREAD

**Issue by ghost** [Python-Markdown/markdown#570]
Can you please implement references like in [pandoc does](http://pandoc.org/MANUAL.html#citations). I have references in BibTeX file so it's very good to have this feature to me.

**Comment by waylan** [comment]
I work on this project in my (very limited) spare time and have no need for such a feature. Therefore I have no reason to implement it. However, we have created a complete [Extension API][1] so that anyone can add whatever features they desire. You are welcome to implement the feature yourself. You can get started by reviewing the [tutorial][2].

[1]: https://pythonhosted.org/Markdown/extensions/api.html
[2]: https://github.com/waylan/Python-Markdown/wiki/Tutorial:-Writing-Extensions-for-Python-Markdown
