### ISSUE TITLE
nl2br with html table problem

### ISSUE THREAD

**Issue by tankywoo** [Python-Markdown/markdown#574]
test markdown with wrong (no empty line between title and table):

```markdown
## title
<table>
<tr>
<td>123123</td>
</tr>
</table>
```

generate to:

```html
$ markdown_py -x nl2br test.md
<h2>title</h2>
<p><table><br />     <!-- redundant br -->
<tr><br />  <!-- redundant br -->
<td>123123</td><br />  <!-- redundant br -->
</tr><br />  <!-- redundant br -->
</table></p>
```

test markdown with right (empty line between title and table):

```markdown
## title

<table>
<tr>
<td>123123</td>
</tr>
</table>
```

generate:

```html
markdown_py -x nl2br test.md
<h2>title</h2>
<table>
<tr>
<td>123123</td>
</tr>
</table>
```

Although  the first case is not a good write way, but I tried GFM and found it can parse this right.

**Comment by facelessuser** [comment]
Based on [markdown spec](https://daringfireball.net/projects/markdown/syntax#html), Markdown should be surrounded by blank lines.

> The only restrictions are that block-level HTML elements — e.g. `<div>`, `<table>`, `<pre>`, `<p>`, etc. — must be separated from surrounding content by blank lines, and the start and end tags of the block should not be indented with tabs or spaces. Markdown is smart enough not to add extra (unwanted) `<p>` tags around HTML block-level tags.

If you change your code to the following, you will have no issues:

```
## title

<table>
<tr>
<td>123123</td>
</tr>
</table>
```

**Comment by waylan** [comment]
First of all, GFM is a CommonMark variant (not Markdown) and they follow a [different][1] set of rules than [we do][2] (@facelessuser quoted the relevant rule above).

The primary different here is that CommonMark does not require a blank line between the heading and the raw HTML. However, Markdown does require a a blank line. The missing blank line causes Markdown to not identify the table as a raw HTML block. Once that happens, all bets are off that any other behavior will be as you expect. The thing about Markdown is that the rules only discuss what happens when you have valid syntax. There are no rules about what happens when you provide invalid syntax. I'd say the actual output is a reasonable result. Each line is identified as inline raw HTML, which the nl2br extension sees no differently than inline Markdown. Thus, you get a `br` tag at the end of each line.

I'm closing this as there is no bug here.

[1]: https://github.github.com/gfm/
[2]: http://daringfireball.net/projects/markdown/syntax

**Comment by tankywoo** [comment]
@facelessuser @waylan, Thanks, I got it. 👍
