### ISSUE TITLE
Problems with using Attribute Lists for colspan and rowspan in tables

### ISSUE THREAD

**Issue by AndreWin** [Python-Markdown/markdown#587]
Hello!

I create documentation in mkdocs and use `markdown.extensions.tables` and `markdown.extensions.attr_list` extensions.

I created the following table:

```markdown
| A | B |
|:-:|:-:|
| 1 {rowspan=2}| 2 |
| 3 |
```
I got the following result:

![image](https://user-images.githubusercontent.com/7497378/31426154-d9a24352-ae6a-11e7-8fd9-700fe443b9db.png)

It seems to me, that table extension always generate the same td cells in each rows as in header. I'd like to turn off this feature. How can I quickly fix this?

Best regards,
Andrey.

**Comment by waylan** [comment]
Please see my [comment][1] to #74 for my position on any changes to the table syntax. I would also add that in addition to PHP Extra, our behavior matches the (very popular) GitHub Flavored Markdown which has its behavior defined in a formal [spec][2]. In fact, I just posted an [answer][3] to a question on StackOverflow about how to do rowspans on GitHub the other day. The same answer would apply to Python-Markdown. The one difference here is that you can provide your own extension (or use a third party extension) which alters the behavior as you see fit.

Regarding the fact that Attribute Lists do not work on tables, this is intentional. There are a number of elements which Attribute Lists cannot be defined for. For more info on that, see my [comment][4] to #312. Again, if you would like different behavior, you are free to develop your own extension and/or fork an existing one and modify it.

[1]: https://github.com/Python-Markdown/markdown/pull/74#issuecomment-3622297
[2]: https://github.github.com/gfm/#tables-extension-
[3]: https://stackoverflow.com/a/46648510/866026
[4]: https://github.com/Python-Markdown/markdown/issues/312#issuecomment-44227093
