### ISSUE TITLE
Allow spaces in image urls

### ISSUE THREAD

**Issue by sedrubal** [Python-Markdown/markdown#590]
Currently `markdown.markdown` does not recognize images with spaces in their url:

This is not working:
```py
>>> markdown.markdown('![](/test test.jpg)')
'<p>![](/test test.jpg)</p>'
```

The same without space is working:
```py
>>> markdown.markdown('![](/testtest.jpg)')
'<p><img alt="" src="/testtest.jpg" /></p>'
```

A possible workaround is to replace the space with `%20`, but this is ugly.

If you think this should work, I can try to fix it :wink:

**Comment by facelessuser** [comment]
URLs/URIs don't allow spaces.  The link syntax expects a valid URL/URI etc.  This is pretty universal with all Markdown parsers I've used.  If I try to enter your example here in GitHub, it won't even accept it, not because the image isn't found, but because it is invalid syntax.

![](/test test.jpg)

**Comment by waylan** [comment]
Actually, there is quite a bit of variety (see [Babelmark][1]), although most of the "old-school" implementations seem to agree. What I find most curious is that Python-Markdown has different behavior for links and images. Seems the behavior should be the same here. If we are changing anything, we should follow the lead of the "old-school" implementations (after all Python-Markdown fits that category).

[1]: http://johnmacfarlane.net/babelmark2/?normalize=1&text=!%5Bimage%5D(%2Ftest+test.jpg)%0A%0A%5Blink%5D(%2Ftest+test.html)

**Comment by facelessuser** [comment]
Interesting.  I didn't realize that normal links allowed spaces...I'd hate to break all the documents out there by reverting it though.  Especially since it has been like that for a while now...

**Comment by waylan** [comment]
Truth be told, I didn't realize links allowed spaces either. At least I don't ever recall that coming up before.

**Comment by facelessuser** [comment]
I have to say, I generally would lean to the the "old-school" behavior, but since normal links have had this functionality for some time now, and I'd hate to strip out functionality people are used to, it kind of sways me in favor of image links doing the same only for unification of behavior.  Had normal not already had this behavior, I would have voted no for this.

**Comment by waylan** [comment]
I'm torn. I understand we shouldn't break existing links, so changing the link behavior is out of consideration. But the image behavior is technically "correct," so I hesitate to alter it, even if it "unifies" the behavior. We probably should make the change. I'm just not crazy about it.

**Comment by facelessuser** [comment]
@waylan, understood.  I may throw to together a pull just to have it ready if we ultimately decide to pull the trigger on this.  If not, we can just close the pull.

**Comment by sedrubal** [comment]
We found this issue while translating HTML pages to markdown. In HTML it seems that image URLs are allowed to have spaces...

**Comment by waylan** [comment]
Actually, URLs are not allowed to have spaces. However, most modern browsers are smart enough to handle them with spaces and will do URL escaping before making a request with the URL. That wasn't always the case. Back when Markdown was new, you had to do the escaping yourself. Therefore, standard (old-school) Markdown does not allow spaces in URLs. Some Markdown implementations actually run URL escaping on URLs in links and images for you, but that is not in the rules (or done by the reference implementation), so that would also be a non-standard behavior.

**Comment by waylan** [comment]
For reference, the relevant part of the [URL spec][1] states:

> Spaces and control characters in URLs must be escaped for transmission in HTTP, as must other disallowed characters. 

The question is about where the escaping should be happening. The URL spec also states:

> The path is passed by the client to the server with any request, but is not otherwise understood by the client. 

Therefore, in the past, escaping was always assumed to be done by the document author. Today, many tools are a little smarter that the spec requires, so it becomes transparent to the end users and its easy to assume spaces don't need to be escaped. However, some tools are still not-so-smart (see command-line scripts and/or page scrapers) and using URLs with spaces can break things, which is why I'm hesitant to allow spaces in URLs.

[1]: https://www.w3.org/Addressing/URL/url-spec.txt

**Comment by facelessuser** [comment]
I've added a pull for this.

**Comment by waylan** [comment]
Following the continuation of this discussion in #592, I'm closing this as we will not be adding support for spaces in image URLs. It is clear that support for spaces in link URLs was accidental and would be removed if not for the fact that doing so could break existing documents.

**Comment by waylan** [comment]
FYI, we have revisited this issue and have added support for spaces in image URLs (for consistency) in #629.
