### ISSUE TITLE
inline html problem with <body> and <html> tags

### ISSUE THREAD

**Issue by daniele-niero** [Python-Markdown/markdown#603]
Let's consider this simple script:

``` python
import markdown
md = markdown.Markdown(output_format='html5')
html = md.convert("<div>Hello World!</div>")
print(html) 
```
this correctly outputs:

``` <div>Hello World!</div>```

However if the tag is `body` or `html` the output is:

``` <p><body>Hello World!</body></p>```

which seems wrong to me.

Am I missing something or have I found a bug?

**Comment by waylan** [comment]
See [this comment][1]  and [this one][2] for an explanation of how we determine which tags to treat as "block-level tags". As indicated in the rules (quoted in the above referenced comment) the default is to wrap all raw HTML in `p` tags. An exception exists only for a specific subset of tags (the so called "block-level tags") when all of the requirements of the rule are met.

Given the above, the question then, is whether the `body` and `html` tags should be included in that list of "block-level tags". I'm sure this has been discussed before, but I can't find it, so...

Markdown only outputs an HTML fragment. HTML fragments are expected to be inserted within a `body` tag to make a complete HTML document. Therefore, to include `html` or `body` tags in a Markdown document would result in an invalid HTML document. For that reason, we do not support using those tags in Markdown and will not consider doing so. Yes, the output results in an invalid HTML fragment, but that is the clue to tell the document author that they are doing something wrong. When the document author is using raw HTML, they are responsible for ensuring it is valid, not the Markdown parser.

Therefore, the `body` and `html` tags  do not meet the criteria to be listed among the  "block-level tags" which do not get wrapped in `p` tags. Even if we ignored that and included them in the list anyway, that would potentially allow a document author to use Markdown to generate a complete HTML document rather than a fragment, which is a use-case we do not support.

Finally, the Markdown rules define two types of HTML tags that are supported: "block level" and "span level". I think we can all agree that tags like `html` and `body` fit neither category. Therefore, they are not supported by Markdown at all. However, as Markdown is relatively dumb when it comes to raw HTML, any unknown tags get treated as span level tags.

[1]: https://github.com/Python-Markdown/markdown/issues/543#issuecomment-277325612
[2]: https://github.com/Python-Markdown/markdown/issues/543#issuecomment-277331342

**Comment by daniele-niero** [comment]
I do understand your point.
I guess the problem is that there isn't an official semantic for markdown. 

Do you know the CommonMark specification?
Look at here:
http://spec.commonmark.org/0.27/#html-block

I try always to follow this specification, however I understand that it is trying to become the standard, but it isn't yet the standard and probably your code is also older.

Do you think it will be a good reference for verdion 3?

**Comment by waylan** [comment]
> I guess the problem is that there isn't an official semantic for markdown.

IMO, Markdown as a sufficient definition with the original [rules][2] and needs nothing more until such time as the author of those rules decides otherwise. If there is any problem, its that Commonmark keeps trying to claim it is Markdown, which confuses people.

My position on CommonMark is summarized [here][1].

[2]: http://daringfireball.net/projects/markdown/syntax
[1]: https://github.com/Python-Markdown/markdown/issues/338#issuecomment-54697337

**Comment by daniele-niero** [comment]
It's fair. I am not an expert of markdown, both the language and your tool,
so mine were pure questions. Your answers make sense, thanks for replying

On 7 Dec 2017 20:01, "Waylan Limberg" <notifications@github.com> wrote:

I guess the problem is that there isn't an official semantic for markdown.

IMO, Markdown as a sufficient definition with the original rules
<http://daringfireball.net/projects/markdown/syntax> and needs nothing more
until such time as the author of those rules decides otherwise. If there is
any problem, its that Commonmark keeps trying to claim it is Markdown,
which confuses people.

My position on CommonMark is summarized here
<https://github.com/Python-Markdown/markdown/issues/338#issuecomment-54697337>
.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Python-Markdown/markdown/issues/603#issuecomment-350062515>,
or mute the thread
