### ISSUE TITLE
Deprecation Warnings

### ISSUE THREAD

**Issue by jkempinger-dv** [Python-Markdown/markdown#618]
I just updated to 2.6.10 and now I'm seeing DeprecationWarnings

```
...markdown/treeprocessors.py:275: FutureWarning: The behavior of this method will change in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.

...markdown/treeprocessors.py:276: FutureWarning: The behavior of this method will change in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.
```

This seems to be the same issue as #254, and changing lines 275 and 276 to

```
while parent is not None:
    if parent is not None:
```

eliminates these warnings.

**Comment by waylan** [comment]
Thanks for the report.

The fix is easy enough, but those lines were introduced in #598 very recently. Perhaps our CI tests should be catching that sort of thing (the warnings don't even show up in our [test log][1]). Maybe we should update our tests to check for that sort of thing.

[1]: https://travis-ci.org/Python-Markdown/markdown/jobs/304174819

**Comment by jkempinger-dv** [comment]
I'm using python 3.6.4 with PyInstaller.  I see the warnings when I run my built application.  I don't recall seeing the warnings when running the source files through the python interpreter on the CLI.  Let me know if you would like any other information/debugging about my setup!

**Comment by waylan** [comment]
Apparently, the Python interpreter has these set to be ignored by [default][0]. However, in other environments, they can still get issued. So we need to change the default when running our tests if we want to prevent introducing them.  Using Python [`-W`][1] flag or setting the [`PYTHONWARNINGS`][2] env variable should do the trick. According to [this][3], setting either to `default` (or `d` for short) will override any ignored warnings.

I'm thinking of adding the following line to the `tox.ini` file:

    setenv = PYTHONWARNINGS = error::DeprecationWarning,default::PendingDeprecationWarning

That way `PendingDeprecationWarning` get listed (but don't cause the tests to fail) and `DeprecationWarning` cause the tests to fail.

What is not clear to me is why we don't already get the warnings. We do get depreciation warnings raised from the Markdown lib, so why not from the standard libs? Or is nose specifically changing the defaults for the tested libs, but not the standard libs? I'll have to experiment.

[0]: https://docs.python.org/3/library/warnings.html?highlight=warn#default-warning-filters
[1]: https://docs.python.org/3/using/cmdline.html#cmdoption-w
[2]: https://docs.python.org/3/using/cmdline.html#envvar-PYTHONWARNINGS
[3]: https://docs.python.org/3/library/warnings.html?highlight=warn#updating-code-for-new-versions-of-python

**Comment by mitya57** [comment]
It looks like the `FutureWarning` exception is only [raised](https://github.com/python/cpython/blob/3.6/Lib/xml/etree/ElementTree.py#L208) with the pure Python version of ElementTree.

When using the [C implementation](https://github.com/python/cpython/blob/master/Modules/_elementtree.c), the `if parent:` check ends up in [PyObject_IsTrue](https://github.com/python/cpython/blob/3.6/Objects/object.c#L1226) call, which in turns [ends up](https://github.com/python/cpython/blob/3.6/Modules/_elementtree.c#L3760) in `element_length` check without raising any warning.

> I'm thinking of adding the following line to the tox.ini file:
>
>     setenv = PYTHONWARNINGS = error::DeprecationWarning,default::PendingDeprecationWarning

I don’t think this would work. With this variable, I immediately get an exception on `import nose`.

After I change it to `error::DeprecationWarning::markdown`, it gets better, but the `safe_mode/*` tests fail because the `safe_mode` setting is deprecated.

**Comment by waylan** [comment]
> It looks like the `FutureWarning` exception is only raised with the pure Python version of ElementTree.

Ahh, that's why the warning seems to be inconsistent. Users who see it are using the pure Python lib but all our tests run on the C implementation. Perhaps we need to run our tests twice, once with the C implementation and once with the pure Python implementation of ElementTree. Not sure how to force that though.

> After I change it to `error::DeprecationWarning::markdown`, it gets better, but the `safe_mode/*` tests fail because the `safe_mode` setting is deprecated.

I was afraid of that. I was thinking we could use `default` for `markdown` and `error` for everything else. But if we immediately get an exception on `import nose`, that won't work either (unless we also define a nose specific rule). I suppose as a lowest common denominator, we can simply set it to `default` so that all the warnings get included in the logs. It won't cause the tests to fail, but at least we can see the warnings. Although, I suspect nose already does that. We just aren't seeing the warnings due to use of the C implementation of ElementTree which doesn't issue the warnings.

**Comment by waylan** [comment]
So I did some testing and I can't get any warnings to appear, even when I force the pure Python implementation of ElementTree. I also did not encounter any problems with nose like @mitya57. 

I decided to define the warning config in Python in the testing framework as follows:

```dif
--- a/tests/__init__.py
+++ b/tests/__init__.py
@@ -2,6 +2,7 @@ import os
 import markdown
 import codecs
 import difflib
+import warnings
 try:
     import nose
 except ImportError as e:
@@ -179,4 +180,10 @@ def generate_all():


 def run():
+    # Warnings should cause tests to fail...
+    warnings.simplefilter('error')
+    # Execpt for the warnings that shouldn't
+    warnings.filterwarnings('default', category=PendingDeprecationWarning)
+    warnings.filterwarnings('default', category=DeprecationWarning, module='markdown')
+
     nose.main(addplugins=[HtmlOutput(), Markdown()])
```

I tried a few different variations and only got any different behavior when removing the "markdown" override. In that case, Markdown's DeprecationWarnings would cause the tests to fail.

**Comment by mitya57** [comment]
> So I did some testing and I can't get any warnings to appear, even when I force the pure Python implementation of ElementTree.

How exactly do you force the pure Python implementation? If I just comment out this line:

https://github.com/python/cpython/blob/a70d5ff992e5e123a3fa6f0e7f672026db8ed1f7/Lib/xml/etree/ElementTree.py#L1654

from my `/usr/lib/python3.6/xml/etree/ElementTree.py`, I get the expected failures with `-Werror::FutureWarning`.

Also the [PyPy test](https://travis-ci.org/Python-Markdown/markdown/jobs/324864321) in #619 gets these warnings.

> I also did not encounter any problems with nose like @mitya57.

For reference, my error was this:

```pytb
Traceback (most recent call last):
  File "./run-tests.py", line 3, in <module>
    import tests
  File "/home/dmitry/upstream/Python-Markdown/tests/__init__.py", line 6, in <module>
    import nose
  File "/usr/lib/python3/dist-packages/nose/__init__.py", line 1, in <module>
    from nose.core import collector, main, run, run_exit, runmodule
  File "/usr/lib/python3/dist-packages/nose/core.py", line 12, in <module>
    from nose.loader import defaultTestLoader
  File "/usr/lib/python3/dist-packages/nose/loader.py", line 21, in <module>
    from nose.importer import Importer, add_path, remove_path
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 12, in <module>
    from imp import find_module, load_module, acquire_lock, release_lock
  File "/usr/lib/python3.6/imp.py", line 33, in <module>
    DeprecationWarning, stacklevel=2)
DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
```

Note that nose is currently [unmaintained](https://nose.readthedocs.io/en/latest/#note-to-users), so it might be a good idea to switch to [nose2](https://github.com/nose-devs/nose2) or another framework.

**Comment by waylan** [comment]
> How exactly do you force the pure Python implementation? If I just comment out this line:

Oh right. I forgot ElementTree auto-overrides with the C implementation now. It didn't always do that. That explains why I'm not seeing the warnings.

> Note that nose is currently unmaintained, so it might be a good idea to switch to nose2 or another framework.

I was not aware of that. Good to know.

**Comment by waylan** [comment]
> Also the PyPy test in #619 gets these warnings.

Right, PyPy uses the pure Python implementation only. So as long as we run our tests through PyPy, we will always get a test run with the pure Python implementation. I'm happy with that. Looks like we have a working solution for testing this.

**Comment by waylan** [comment]
I finally have a working solution in #619. Thanks to everyone for the help and feedback. That seemed like a lot of work (mostly research) for such a small change. But if it help us avoid similar regressions in the future, it was worth it to get it right.
