### ISSUE TITLE
ValueError on legacy attributes

### ISSUE THREAD

**Issue by cbeauchesne** [Python-Markdown/markdown#643]
Another strange markdown that causes an exception 

    {@{=}

Tested on markdown 2.6.11 and python 3.6.2

**Comment by facelessuser** [comment]
In the future, please post relevant errors. I went ahead and reproduced:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\<user>\Documents\GitHub\markdown\markdown\core.py", line 374, in markdown
    return md.convert(text)
  File "C:\Users\<user>\Documents\GitHub\markdown\markdown\core.py", line 260, in convert
    output = self.serializer(root)
  File "C:\Users\<user>\Documents\GitHub\markdown\markdown\serializers.py", line 282, in to_xhtml_string
    return _write_html(ElementTree(element).getroot(), format="xhtml")
  File "C:\Users\<user>\Documents\GitHub\markdown\markdown\serializers.py", line 202, in _write_html
    qnames, namespaces = _namespaces(root, default_namespace)
  File "C:\Users\<user>\Documents\GitHub\markdown\markdown\serializers.py", line 268, in _namespaces
    add_qname(key)
  File "C:\Users\<user>\Documents\GitHub\markdown\markdown\serializers.py", line 228, in add_qname
    uri, tag = qname[1:].split("}", 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

What's interesting is that it appears qname is an XML thing.  But by default we should be parsing HTML, so I'm a bit confused. Aside from that, the parsing should gracefully move on if it doesn't match the expected form, but for some reason it is not.  I'll have to look into this more as I'm not very familiar with qnames.

**Comment by facelessuser** [comment]
Never mind, default is xhtml not html...this surprises me a little that xhtml is the default...

**Comment by facelessuser** [comment]
It hadn't occurred to me that you could set an attribute outside of `attr_list` extension with the syntax `{@id=123}`.  But this is why we are heading down that path.  We end up with an attribute of `{=""`.  We get this attribute because of the very poor regex of `ATTR_RE = re.compile(r"\{@([^\}]*)=([^\}]*)}")  # {@id=123}` which is extremely lax, but maybe `{` is somehow an acceptable character because we then begin parsing when we see it starts with `{`:

```py
        try:
            if qname[:1] == "{":
                uri, tag = qname[1:].split("}", 1)
                prefix = namespaces.get(uri)
                if prefix is None:
                    prefix = _namespace_map.get(uri)
                    if prefix is None:
                        prefix = "ns%d" % len(namespaces)
                    if prefix != "xml":
                        namespaces[uri] = prefix
                if prefix:
                    qnames[qname] = "%s:%s" % (prefix, tag)
                else:
                    qnames[qname] = tag  # default element
            else:
                if default_namespace:
                    raise ValueError(
                        "cannot use non-qualified names with "
                        "default_namespace option"
                        )
                qnames[qname] = qname
        except TypeError:  # pragma: no cover
            _raise_serialization_error(qname)
```

Unfortunately, we split on `}` and try to get a uri and tag, but since our key is just `{`, we fail as we don't have enough to unpack.

So, I would have to look of the spec sheet on this notation and probably would want to either create a more suitable regex for this to prevent bad attribute names, or provide a way to gracefully handle this scenario without failing.

Quickfix if you are not trying to set an attribute, just escape your `{`: `\{@{=}`.

**Comment by cbeauchesne** [comment]
Thank you for the analysis, and sorry for the poor bug report.

Don't worry about a quickfix, it's not a use case I have : I've extensivly tested my parser with a fuzzing campain to find errors in my extensions, and I've discovered this weird pattern (and also toc issue). FYI, bleach also won an issue mozilla/bleach#352 😊

**Comment by waylan** [comment]
So, this is a very old bit of code which is controlled by the [enable_attributes][1] feature. You can turn it off with `enable_attributes=False`. Curious to see if that avoids the error. In any event, the syntax has never been documented anywhere, but support remains as some very old documents by some of the oldest users of the lib still contain the syntax. Originally, it was on all the time. IIRC, in version 2.0 I added the `enable_attributes` keyword to provide the ability to turn it off (but did not change the default). I intend to change the default in version 3.0. However, I haven't yet moved 0005d7a1c from the md3 branch to master yet (tests need updated to new framework).

> default is xhtml not html...this surprises me a little that xhtml is the default

Yeah, the reference implementation outputs XHTML, so we do by default as well. As a reminder, Markdown was first created when XHTML was the new hotness. The original rules haven't been updated since, so the default is still XHTML. As it really doesn't matter in the HTML5 world if we output XHTML or HTML style tags, I see no reason to change the default. 

However, the "qname" stuff in the serializer is not really ever used (for example, see test coverage of that bit of code). The serializer is actually borrowed (with permission) from ElementTree with a few modifications to make it work better for our needs. We could rip the "qname" stuff out. I don't think it would do any harm. I just never got around to it.

[1]: https://python-markdown.github.io/reference/#enable_attributes

**Comment by facelessuser** [comment]
> You can turn it off with enable_attributes=False. Curious to see if that avoids the error.

I imagine it would, but I'd have to check.

> As it really doesn't matter in the HTML5 world if we output XHTML or HTML style tags, I see no reason to change the default.

There's no problem with it, it just surprised me is all.

> However, the "qname" stuff in the serializer is not really ever used (for example, see test coverage of that bit of code). The serializer is actually borrowed (with permission) from ElementTree with a few modifications to make it work better for our needs. We could rip the "qname" stuff out. I don't think it would do any harm. I just never got around to it.

That seems like it would be a reasonable solution.  We process them, but don't do anything with them, so I don't see why we would need to actually parse them.

**Comment by cbeauchesne** [comment]
Yes, for my use case, best is to set enable_attributes to False, as we don't use this feature. Thank you very much, for the help, and for this great project.

**Comment by waylan** [comment]
> We could rip the "qname" stuff out. I don't think it would do any harm. I just never got around to it.

Turns out there is a legitimate reason to support them, which has been handled in #681. We can ignore that going forward on this issue.
