### ISSUE TITLE
Support for swapping regex implementations?

### ISSUE THREAD

**Issue by aero31aero** [Python-Markdown/markdown#687]
For our particular usecase, we need to use Unicode word-boundary support that isn't provided by the `re` module. However, the `regex` module is API compatible with `re` and has better support for Unicode.

Is there a way to use `regex` for our Inline Patterns instead of `re`?

Link: https://pypi.org/project/regex/

**Comment by waylan** [comment]
This is certainly not possible with inline patterns in Markdown version 2.x. However, due to the work in #629, you may be able to find a solution in version 3.0 which is currently in development on the master branch. @facelessuser might have some more specific guidance for you. And we both would appreciate some feedback on the recent changes.

**Comment by facelessuser** [comment]
As a generalized way to swap regular expression engines, I don't think there is a way without forking Markdown Preview.  In general, on Python 3, `re` should use Unicode alphanumerics when using `\b`,  but that doesn't technically mean that is exactly the same thing as using Unicode word boundaries.

There are lots of places where `re` gets used, and to swap them out with `regex` would require you to search for all cases in which we reference `re`.  And then if you are using third party extensions, you'd have to fork some of them if they are doing regular expression search and replace directly in the extension instead of just providing a pattern to Markdown.

Due to the variety of ways `re` may be used, it simply isn't a matter of changing the engine in one place.  For some extensions that is certainly possible, but others, you'd almost have to have a regex abstraction API and have all extensions use it when they are performing in extension matching.

I'm not entirely sure of what scenario you are specifically having trouble with.  There may be a way to override a specific inline patterns in such a way you could essentially get what you desire, but I'd have to better understand what specific issues you are having, and even then, the solution may not be worth the trouble.

**Comment by waylan** [comment]
> due to the work in #629, you may be able to find a solution in version 3.0 

Note that I said that "you may be able to find a solution", which solution may or may not involve using a different regex engine. The work in #629 also permits string parsing without using regular expressions at all, so depending on what you are trying to do, you may not need a regex engine at all. But without more information, it's impossible to say if that will meet your needs.

**Comment by facelessuser** [comment]
Thanks @waylan, I think you summed up better what I was trying to say.

**Comment by aero31aero** [comment]
Thanks for the quick replies.

Our usecase is matching regex like: `(?:\b)(?P<id>[0-9]{2,8})(?:\b)`
for strings like `Hello #123 World`
but not for `Hello#123 World`  or `Hello #123World`.

In `re`, this works fine in English and languages that use white space characters for separators but breaks in Japanese where `チケットは#123です` should be a valid match.

Is there a release coming up soon? I'll try to see if #629  helps us.

**Comment by waylan** [comment]
> Is there a release coming up soon?

Yes, when its ready. As we work on this in our spare time as volunteers, I can't give a specific timetable except to say when everything in the [milestone] is done. 

[milestone]: https://github.com/Python-Markdown/markdown/milestone/4

**Comment by waylan** [comment]
> In `re`, this works fine in English and languages that use white space characters for separators but breaks in Japanese where `チケットは#123です` should be a valid match.

Personally I'm okay with that failing. Markdown relies heavily on white space for its syntax. Anywhere in the existing syntax, white space characters would need to be used irrespective of how word boundaries are determined in a given language. That being the case, I would expect the same behavior for any extensions. But perhaps I am bias due to my lack of experience with such languages.

**Comment by andersk** [comment]
Note, in case this was a perceived compatibility concern, that the `regex` package has the same default behavior for `\b` as Python’s `re`. It only uses the Unicode word boundary algorithm with its new `WORD` (`w`) flag, which can be set for the entire pattern (`flags=regex.WORD`) or scoped to a particular part of a pattern (`(?w:\b)(?P<id>#[0-9]+)(?w:\b)`).

**Comment by waylan** [comment]
> Markdown relies heavily on white space for its syntax. Anywhere in the existing syntax, white space characters would need to be used irrespective of how word boundaries are determined in a given language. That being the case, I would expect the same behavior for any extensions. 

Given the above, I see no need to make any special accommodations for the stated use case and am closing this as wontfix.
