### ISSUE TITLE
Conflict between Markdown and math quote marks

### ISSUE THREAD

**Issue by GekkaSaori** [Python-Markdown/markdown#702]
Hi. I am trying to insert math quote marks in a paragraph, and it doesn't make sense.

For example, if I use
```md
for string $``abcbc"$ we have $endpos(``bc")=2,\,4$ ...
```
and here is what I get in Python-Markdown:
![not working](https://user-images.githubusercontent.com/19746684/44438124-4bf6ce00-a5f0-11e8-8d7a-799dae84778d.png)
expected behavior (from StackEditor):
![default](https://user-images.githubusercontent.com/19746684/44438425-92006180-a5f1-11e8-8f4a-f4d77d2570ab.png)

Sounds like the parser thinks the quote marks in the formula is some code.

Wondering if the parser could be improved to escape the fomula parts, or something like escaping character could be added. Or should we let MathJax parse the formula first?

Thanks in advance.

**Comment by waylan** [comment]
Mathjax and Markdown syntax conflict. Therefore you need to use an extension to ensure that the math is recognized as such and the rest of the Markdown parser ignores it. Multiple math extensions are listed in the [wiki](https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions).

**Comment by mitya57** [comment]
Also when using MathJax, please make sure to disable the [tex2jax preprocessor](http://docs.mathjax.org/en/latest/options/preprocessors/tex2jax.html), otherwise it can render unwanted content (such as explicitly escaped delimiters) as math.

My python-markdown-math extension’s documentation provides [an example](https://github.com/mitya57/python-markdown-math#usage) of how to do that in the `<head>` of your document.
