### ISSUE TITLE
Change the default blockquote marker

### ISSUE THREAD

**Issue by meskarune** [Python-Markdown/markdown#703]
Is there a way for me to reset the blockquote marker so that instead of a greater than bracket it is a parenthesis? Or if not reset then add support for another option?

```
> You are wrong. Look at what you said:
>> The skey is green
> It's obviously purple!

) You are wrong. Look at what you said:
)) The skey is green
) It's obviously purple!
```
The reason I want to do this is because I want to run an html sanitizer on markdown before converting the markdown to html. This way I can ensure no scripts or iframes, etc are in the text, only safe html. However the sanitizer changes the single blockquote `>` marker into `&gt;` and I cannot find a way around this. I'm suing python-bleach.

**Comment by waylan** [comment]
You should never run an HTML sanitizer **before** the Markdown parser, only **after** the text is passed through Markdown. For a clear explanation of why, please see [Markdown and XSS][1].

Note that the documentation also [recommends][3] passing your Markdown text to Markdown first, then to Bleach. That being the case, Markdown syntax will never actually get passed to Bleach and you don't need to change the syntax. And not changing the syntax means that your documents will be portable to other systems if you should ever desire to do so.

That said, the [extension API][4] permits you to change any part of the syntax you want for whatever reason.

As this appears to be a support question, rather than a bug report or feature request, I'm closing this.

[1]: https://michelf.ca/blog/2010/markdown-and-xss/
[3]: https://python-markdown.github.io/change_log/release-2.6/#safe_mode-deprecated
[4]: https://python-markdown.github.io/extensions/api/
