### ISSUE TITLE
How to calculate the priority?

### ISSUE THREAD

**Issue by neurobin** [Python-Markdown/markdown#719]
Previously, the add method used to calculate the priority and call the register method and we just had to pass a location string `_begin`, `_end` etc. As, the add method is now deprecated, how do I calculate the priority to pass to the register method?

**Comment by waylan** [comment]
In situations where it doesn't really matter whether one extension runs before or after another, remember that if multiple items are assigned the same priority, they all are run in the order in which they are added. Therefore, in most cases, assigning a priority which matches another extension is not likely to matter. In other words, you are probably putting more thought into it that is necessary. However, if you have a known conflict, you have the precision control available to guarantee that the conflict is avoided regardless of which order the user loads the two extensions. 

Simply select a number which falls within the range. The builtin items all step by increments of 10 and the builtin extensions mostly use a priority half-way between them (numbers divisible by 5). However, a few extensions are known to need to be very early/late so they are assigned a priority much closer to the item before/after them (eg: 12 instead of 15). The less likely there will be items inserted before/after an item, the closer that items priority should be to the item before/after it.

Regarding items inserted as the begging or end, any number higher or lower than the highest or lowest should be fine. Again, the builtin extensions mostly use a number divisible by 5 (5 higher/lower than the first/last item).

**Comment by neurobin** [comment]
Let's say I have an extension that needs to be the first preprocessor to be processed. I see the highest priority 30 for `NormalizeWhitespace`. Now, I can't just choose a number based on that, because it's not dynamic. Let's say I choose 35 which will work for now, but in a later update you add another one with 40 which will break mine.

I can't choose a much higher number either. For example, a higher number like `9999` would work as long as someone else doesn't decide to put `99999`. And the thing is, user will have no control over it. With the add method `_begin`, a user can just load the extension earlier or later (to get the right priority) and get the right behavior.

> Regarding items inserted as the begging or end, any number higher or lower than the highest or lowest should be fine

I want to know, how can I get the highest or lowest..

**Comment by waylan** [comment]
You are still overthinking it. Don't worry so much about what future extensions might do.

> With the add method `_begin`, a user can just load the extension earlier or later (to get the right priority) and get the right behavior.

I never saw that as an acceptable solution. It should never matter which order the user loads extensions. And to add complexity, the order of execution was opposite of the order extensions were loaded. My assumption is that users will always get this wrong and therefore I never relied on it. In my extensions, I would check if another extension with a known conflict was already loaded and acted accordingly.

The new way is much simpler. I can set the priority on my extension to not conflict with any known extensions. Now that I have set my priority, then any future extensions which conflict with mine are responsible to set their priority to not conflict with mine. If all extension devs respect that convention, there should be no problems. 

As a reminder, you can use floats so there is an infinite number of possible priorities even when not at the beginning or end. Therefore, even with multiple known conflicts, an extension can always be inserted exactly where it needs to be--without requiring the user to load things in any specific order.

**Comment by neurobin** [comment]
Well, I like this now. Setting the priority myself seems I have more control over it. Thanks for the explanation and for a great project like this.

Regards,
Jahid.
