### ISSUE TITLE
angle brackets cause non-well-formed XHTML output

### ISSUE THREAD

**Issue by glyph** [Python-Markdown/markdown#733]
If I specify `xhtml` output, I would expect well-formed XHTML output, regardless of input.

However, as this short program demonstrates, this is not always the case:

```python3
import markdown
document = "<this is not well-formed xhtml>"
xhtml = markdown.markdown(document, output_format="xhtml")
from xml.etree.cElementTree import XML
xml = XML(xhtml)
```

I realize that Markdown is supposed to "pass through" angle brackets, in order to allow for custom elements or HTML formatting to be used, so simply quoting them by default isn't necessarily an option.  But could something be done to at least emit valid output, self-closing the tags and adding attribute values, when the XML output option is selected?

**Comment by waylan** [comment]
> I realize that Markdown is supposed to "pass through" angle brackets, in order to allow for custom elements or HTML formatting to be used, so simply quoting them by default isn't necessarily an option. 

Exactly. Markdown has very limited knowledge of (X)HTML and does not contain a true (X)HTML parser. Nor does it need to. Anything between angle brackets is passed through as raw HTML. **It is the authors responsibility to ensure that any raw (X)HTML in the source document results in valid output.** So, to answer your question...

> could something be done to at least emit valid output, self-closing the tags and adding attribute values, when the XML output option is selected?

No, unless you want to build something yourself. You could create a third party extension which validates raw HTML. Although, personally, I would just run Markdown's output through a validator/tidier.

As an aside, in the past I had attempted to adapt a true HTML parser to parse the raw HTML within Markdown, but ran into problems/conflicts with Markdown's syntax. For example, Markdown natively includes support for angle brackets to denote [automatic links][1] and those would trip up an HTML parser. While perhaps not an insurmountable obstacle, it demonstrates that proper parsing of raw HTML within Markdown is more complex than it may appear on the surface.

[1]: https://daringfireball.net/projects/markdown/syntax#autolink

**Comment by facelessuser** [comment]
Just an FYI, not many parsers do much better: https://johnmacfarlane.net/babelmark2/?text=%3Cthis+is+not+well-formed+xhtml%3E.

In general, if the angle brackets aren't part of some recognizable syntax (Markdown or some Markdown extensions), you should escape them just like you do in any HTML document.

**Comment by glyph** [comment]
For what it's worth, what I'm complaining about here isn't that the *input* isn't being parsed according to my taste, it's that the Markdown library claims to emit XHTML, but it doesn't.  I don't want to *validate* the raw HTML, what I want to do is integrate it into the Markdown parse tree in such a way that whatever the result is, is actually well-formed.  (I don't care at all about validity.)

**Comment by glyph** [comment]
To put it a different way: if I need an HTML5 parser to make sense of the output no matter what, then I don't quite understand what the point of the "output format" switch is.

**Comment by waylan** [comment]
The output format only applies to the generated output, not raw HTML. In actual practice, it means you get `<br />` instead of `<br>` (same goes for `hr`, `img` etc.). Therefore, if you have no raw HTML and your output format is set to `xhtml`, then the output is a valid XHTML fragment.

However, once you include raw HTML, then the validity of the raw HTML is solely the responsibility of the document author. We would not want to muck up something that the author carefully crafted, valid or not. And that's the point, how do we know if something that appears invalid is intentional? Validating raw HTML is outside the scope of a Markdown parser.

I will point out that the reference implementation (`markdown.pl`) also outputs XHTML fragments (it doesn't even have an `html` option). And it handles raw HTML in the same manner. A strict reading of the rules suggests that XHTML should be the only supported output format<sup>1</sup>, and, in fact, originally, Python-Markdown only output XHTML fragments. We added `html` later for people who didn't want the XHTML style tags in their HTML documents.

<sup>1</sup> For example, all examples of the line break tag use `<br />` in the [Paragraphs and Line Breaks](https://daringfireball.net/projects/markdown/syntax#p) section of the Rules.
