### ISSUE TITLE
Wrong block receives attributes with attr_list

### ISSUE THREAD

**Issue by bitstein** [Python-Markdown/markdown#779]
I am trying to create blockquotes that use Bootstrap 4 classes for proper rendering. However, the attr_list is giving an inner paragraph block element the attribute rather than the entire blockquote.

Input:
```
> Some things are in our control and others not.
>
> <footer class="blockquote-footer">Epictetus, <em>The Enchiridion</em></footer>
{: .blockquote}
```

Expected output:
```
<blockquote class="blockquote">
  <p>Some things are in our control and others not.</p>
  <footer class="blockquote-footer">Epictetus, <em>The Enchiridion</em></footer>
</blockquote>
```

Actual output:
```
<blockquote>
<p>Some things are in our control and others not.</p>
<p class="blockquote"></p><footer class="blockquote-footer">Epictetus, <em>The Enchiridion</em></footer><p></p>
</blockquote>
```

**Comment by waylan** [comment]
This is expected behavior. Issues #227 and #312 discuss the expected behavior for lists and tables respectively.

Regarding [lists][1] I explained that:

> ...the markdown syntax has no concept of a ul or ol. They are simply implied by the fact that we have list items.

And [tables][2]:

> ...how would one differentiate between attributes defined on a row, or on a table. The syntax only defines the cells, the rows and table are inferred.

It is not possible to assign attributes to elements which don't actually exist in the document. Of course, that is not exactly true for blockquotes. The problem, however, is that lazy blockquotes are completely valid. Consider this first paragraph of and example in the Markdown [rules][3]: 

```md
> This is a blockquote with two paragraphs. Lorem ipsum dolor sit amet,
consectetuer adipiscing elit. Aliquam hendrerit mi posuere lectus.
Vestibulum enim wisi, viverra nec, fringilla in, laoreet vitae, risus.
```

That is one paragraph which is wrapped in a blockquote. It does not matter that the second and third lines do not start with a angle bracket (`>`). Now let's add an `attr_list` to that:

```md
> This is a blockquote with two paragraphs. Lorem ipsum dolor sit amet,
consectetuer adipiscing elit. Aliquam hendrerit mi posuere lectus.
Vestibulum enim wisi, viverra nec, fringilla in, laoreet vitae, risus.
{: .blockquote}
```

Does that `attr_list` apply to the paragraph or the blockquote? It is not clear. One could argue for some variation which differentiated an attr_list applied to the blockquote and one applied to the paragraph, but the differences would be non-obvious. And that more-or-less leaves us where we are with lists and tables. And that consistency if fine by me.

From a technical standpoint, the way the extension works is that Markdown parses the document as normal, which results in the following HTML:

```html
<blockquote>
  <p>
    This is a blockquote with two paragraphs. Lorem ipsum dolor sit amet,
    consectetuer adipiscing elit. Aliquam hendrerit mi posuere lectus.
    Vestibulum enim wisi, viverra nec, fringilla in, laoreet vitae, risus.
    {: .blockquote}
  </p>
</blockquote>
```

Then, the extension steps through the document and applies the `attr_list` to its parent element. Of course, in this case, that would be the paragraph, not the blockquote. In other words, the extension has no way of knowing if the line with the `attr_list` originally started with a `>` or not, so there is no way to change behavior based on that. Therefore, I'm inclined to not make such a change.

[1]: https://github.com/Python-Markdown/markdown/issues/227#issuecomment-20223738
[2]: https://github.com/Python-Markdown/markdown/issues/312#issuecomment-44227093
[3]: https://daringfireball.net/projects/markdown/syntax#blockquote
