### ISSUE TITLE
Proposal for extension to apply description/summary tags to header/content

### ISSUE THREAD

**Issue by craigphicks** [Python-Markdown/markdown#795]
*Would this proposal fit with the framework of python markdown extensions?   Is there anything objectionable about it?*

## Proposed markdown extension to enable header to be description summary and content to be description body

This style has some moderate popularity and utility, but AFAIK there is no extension for it yet.

In this explanation:
 - Variables are denoted with `{{variable}}`
 - Optionals are denoted with `[[option]]`
 - The brackets are not literal.

The [Attribute Lists extension](https://python-markdown.github.io/extensions/attr_list/) is required.

    {: [[attributes]] }

placed on same line as header, or on it's own line after a block.

## Start the description block.

To designate a description block including the header title as summary add attribute `description-summary` after the summary text.
```
### Title {: description-summary }
```

### Mark the end of summary

To designate the end of the summary block to be the header itself add property `summary-end` to the header
```
### Title {: description-summary summary-end }
```

To designate the end of the summary block to come after a some block of text add property `summary-end` after that text
```
### Title {: description-summary }
Some summary text
{: summary end }
```

## End of description block

By default, the end of the description block is automatic and comes just before the next header of equal or higher level, or the end of file, whichever comes first.
```
### Title {: description-summary summary-end }
Last line of description block text, description end is automatic.
### Next header
```

To end the description manually add attribute `description-end` like this -
```
### Title {: description-summary summary-end }
Last line of description block text.
{: description-end }
```

**Comment by mitya57** [comment]
There is nothing in your proposal that you cannot implement in a third-party extension. If you make it then please add a link to our [wiki](https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions) so that other users are aware of it.

We want to keep our own extension set as minimal as possible, and everything that can be done as a third-party extension should better be done as such.

Also, at least one extension already exists for `<details>`/`<summary>` tags. See [pymdownx.details](https://facelessuser.github.io/pymdown-extensions/extensions/details/).
