### ISSUE TITLE
Parsing >>>>>>… takes quadratic time and eventually crashes with recursion error

### ISSUE THREAD

**Issue by andersk** [Python-Markdown/markdown#799]
```pycon
>>> import markdown, timeit
>>> num, dur = timeit.Timer(lambda: markdown.markdown(">" * 100)).autorange(); dur / num
0.004344235559692607
>>> num, dur = timeit.Timer(lambda: markdown.markdown(">" * 200)).autorange(); dur / num
0.016907797248859425
>>> num, dur = timeit.Timer(lambda: markdown.markdown(">" * 300)).autorange(); dur / num
0.05682634799741208
>>> markdown.markdown(">" * 331)
…
RecursionError: maximum recursion depth exceeded while calling a Python object
```

Same results in 3.0.1 and master.

**Comment by waylan** [comment]
I'm curious where this is coming from. My recollection was that we ignore `>` unless we first have `<`.

In any event as per the discussion in #789, I don't care about the performance issue. But we should address the `RecursionError`.

**Comment by facelessuser** [comment]
This might be related to block quotes if I had to guess.

**Comment by waylan** [comment]
Ah, right, infinently nested block quotes. Except that they require a space. The token is `[greaterthan][space]` together. Without the space, the blockquote processor should ignore it.

**Comment by andersk** [comment]
I’m not sure which specification you aim to follow (if any), but both Markdown.pl and CommonMark agree that the space after `>` is optional in the blockquote syntax. In any event, the same behavior can be observed with `> > > > > > …`.

**Comment by mitya57** [comment]
Python-Markdown does not require a space between `>`s too:
```python
>>> print(markdown.markdown(">>>foo"))
<blockquote>
<blockquote>
<blockquote>
<p>foo</p>
</blockquote>
</blockquote>
</blockquote>
```

**Comment by waylan** [comment]
Sorry. I guess I mis-rembered that. So yeah, infinitely nested blockquotes.

I'm not sure how to address this. When the block parser refactor in 2.0 was done, I removed most of the recursion, but there are a few places it remains. And those few locations in the code will only ever hit the recursion limit with contrived input. On the one hand I want to say: " don't do that" but  I realize it is untrusted users who are the problem here.

I don't think we can just not support this contrived input. As it turns out, most implementations [handle this][1] pretty consistently with shorter strings of `>`s. Although, they do [start to diverge][2] with longer strings (I did not check every iteration to find where the divergence starts).

[1]: http://johnmacfarlane.net/babelmark2/?normalize=1&text=%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E
[2]: http://johnmacfarlane.net/babelmark2/?normalize=1&text=%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E

**Comment by MythicManiac** [comment]
A simple option could be to allow for maximum nesting depth setting (if that's not already the case somewhere). I can't immediately think of any use cases for over 300 nested block quotes, unless you render your work email chains into markdown for some reason.

Though I suppose that still leaves the issue if your maximum depth is above the recursion error threshold

**Comment by waylan** [comment]
> I can't immediately think of any use cases for over 300 nested block quotes, unless you render your work email chains into markdown for some reason.

This is the problem. Years ago (before GitHub even existed) we got a bunch of bug reports because someone was trying to pass plaintext version of the complete works of Shakespeare through our parser. The document was not Markdown formatted and we were hitting recursion limits due to the weird syntax.

Additionally, we promise our users that we won't crash their server. If a random user can submit plain text to your site and that crashes your server, you won't want to use our lib anymore. Therefore, we must always assume the worst sorts of input. Sometimes that means things are less performant in the simple case. Its a tradeoff.

**Comment by waylan** [comment]
> A simple option could be to allow for maximum nesting depth setting

As I understand it, on different systems Python's maximum recursion depth may be different based on the available resources. If someone has a valid need for a higher nesting depth, then that should just work for them with no need to adjust a setting. I think perhaps the solution is to catch the `RecursionError` and simply return the unparsed levels as plan text. That ensures the maximum level of nesting possible is always supported and avoids an error being raised. 

The down side is that things get really slow before the error is raised. But that is a tradeoff I'm willing to make when the user is trying to parse contrived input.

**Comment by MythicManiac** [comment]
I'm not sure how impactful can the latency grow in reality, but it might be worth adding an optional setting regardless in case your normal use cases don't consist of immense nesting levels. Making it enabled by default might not be necessary, though I personally wouldn't mind that either.

I'd gladly limit the maximum recursion depth to say, 30 or even 20 even, because I'm rendering user input and if someone exceeds that they're either doing something stupid or trying to abuse the system. So at least for my use case it would make far more sense to restrict max depth rather than continuing indefinitely until a recursion error, given the performance impact it has.

**Comment by waylan** [comment]
The problem with catching the `RecursionError` is that by that time we are already too deep. Even a single additional function call could cause the error to be raised again. Therefore, ideally we should catch the issue shortly before the error, but not too close to it. However, as one level of the nesting depth in the syntax may result in multiple levels of Python's stack, we can't directly associate the nesting depth with the stack depth. And while we could make an approximate guess, future changes to the code could alter that.

I came up with a easy fix which cuts off nesting at approximately 100 levels from Python's stack depth limit:

```diff
diff --git a/markdown/blockprocessors.py b/markdown/blockprocessors.py
index 60baca1..88ebb62 100644
--- a/markdown/blockprocessors.py
+++ b/markdown/blockprocessors.py
@@ -276,7 +276,7 @@ class BlockQuoteProcessor(BlockProcessor):
     RE = re.compile(r'(^|\n)[ ]{0,3}>[ ]?(.*)')
 
     def test(self, parent, block):
-        return bool(self.RE.search(block))
+        return bool(self.RE.search(block)) and not util.nearing_recursion_limit()
 
     def run(self, parent, blocks):
         block = blocks.pop(0)
diff --git a/markdown/util.py b/markdown/util.py
index a8db7bd..5dc144a 100644
--- a/markdown/util.py
+++ b/markdown/util.py
@@ -26,6 +26,7 @@ from functools import wraps
 import warnings
 import xml.etree.ElementTree
 from .pep562 import Pep562
+import inspect
 
 try:
     from importlib import metadata
@@ -156,6 +157,10 @@ def code_escape(text):
     return text
 
 
+def nearing_recursion_limit():
+    """Return true if current stack depth is withing 100 of maximum limit."""
+    return sys.getrecursionlimit() - len(inspect.stack(0)) < 100
+
 """
 MISC AUXILIARY CLASSES
 =============================================================================
```

Basically, when we detect a blockquote, we check the current stack depth and if it is within 100 of the limit, we consider the block of text to not be a blockquote. That results in the text being considered a paragraph. The result would look something like this significantly truncated example:

```text
<blockquote>
<blockquote>
<p>&gt;&gt;&gt;&gt;</p>
</blockquote>
</blockquote>
```

And now for the problem. Here are the terrible performance numbers:

```python
>>> import timeit
>>> num, dur = timeit.Timer(lambda: markdown.markdown(">" * 100)).autorange(); dur / num
1.2720757999999819
>>> num, dur = timeit.Timer(lambda: markdown.markdown(">" * 200)).autorange(); dur / num
4.7593806999999515
>>> num, dur = timeit.Timer(lambda: markdown.markdown(">" * 300)).autorange(); dur / num
10.332307999999955
```

Without the fix I'm getting the following for comparison:

```python
>>> num, dur = timeit.Timer(lambda: markdown.markdown(">" * 100)).autorange(); dur / num
0.0034761609999999976
>>> num, dur = timeit.Timer(lambda: markdown.markdown(">" * 200)).autorange(); dur / num
0.012274940000000002
>>> num, dur = timeit.Timer(lambda: markdown.markdown(">" * 300)).autorange(); dur / num
0.03034806000000003
```

While the "fix" works, performance is so terrible that it's not a reasonable solution. Apparently the call to `inspect.stack` is the issue. This [Stackoverflow answer][1] provides a bunch or alternate substitutions to calling `inspect.stack`, but I'm not sure we want to use any of those. Any suggestions for alternate solutions are welcome.

[1]: https://stackoverflow.com/a/47956089/866026

**Comment by waylan** [comment]
As an aside, an easy way to test this might be to decrease the recursion limit for a single test case. Perhaps using something like this [context manager](https://stackoverflow.com/a/50120316/866026):

```python
class recursionlimit:
    def __init__(self, limit):
        self.limit = limit
        self.old_limit = sys.getrecursionlimit()

    def __enter__(self):
        sys.setrecursionlimit(self.limit)

    def __exit__(self, type, value, tb):
        sys.setrecursionlimit(self.old_limit)

with recursionlimit(20):
    # test code here
```

**Comment by MythicManiac** [comment]
@waylan out of curiosity, how fast can you hit the recursion limit if you don't use inspect but "test" it by intentionally causing fast recursion? Here's some preliminary testing I did and it seems to be reasonably fast in comparison:

```python
def a():
 a()

def recurse():
 try:
  a()
 except:
  pass
```

```python
>>> num, dur = timeit.Timer(lambda: [recurse() for _ in range(100)]).autorange(); dur / num
0.01735958499999981
>>> num, dur = timeit.Timer(lambda: [recurse() for _ in range(100)]).autorange(); dur / num
0.021130189999999514
>>> num, dur = timeit.Timer(lambda: [recurse() for _ in range(200)]).autorange(); dur / num
0.034520720000000435
>>> num, dur = timeit.Timer(lambda: [recurse() for _ in range(300)]).autorange(); dur / num
0.05057582000000025
```

Not that I'd think this is a good idea, since this method will take longer the higher your recursion limit is

**Comment by waylan** [comment]
@MythicManiac I'm not sure I understand the relevance of that.

Obtaining the current limit is easy with `sys.getrecursionlimit()`. Its finding were we are in the stack that is the slow part.

**Comment by waylan** [comment]
Basically the solution I came up with is using the recursion limit as a sort of nesting depth limit. But given it is so expensive to determine where we are in the stack, it is not practical. We might need to actually set a nesting depth and then track the levels to cut it off. I was hoping to avoid that though.

**Comment by MythicManiac** [comment]
So here's a bit more elaborate snippet:
```python
def recurse(current_depth):
    try:
        return recurse(current_depth + 1)
    except:
        return current_depth

def get_remaining_recursion():
  return recurse(0)

import timeit
num, dur = timeit.Timer(lambda: [get_remaining_recursion() for _ in range(100)]).autorange()
print(dur / num)
num, dur = timeit.Timer(lambda: [get_remaining_recursion() for _ in range(100)]).autorange()
print(dur / num)
num, dur = timeit.Timer(lambda: [get_remaining_recursion() for _ in range(200)]).autorange()
print(dur / num)
num, dur = timeit.Timer(lambda: [get_remaining_recursion() for _ in range(300)]).autorange()
print(dur / num)
```

This outputs
```
0.01548541
0.01447132
0.026666679999999988
0.04390339999999995
```

There might be some trick to jump up the stack even faster, but this seems like a surprisingly fast method of getting the remaining stacks size

**Comment by waylan** [comment]
I just tried this:

```python
def _get_stack_depth(size=2):
    """Get stack size for caller's frame.
    """
    frame = sys._getframe(size)

    for size in count(size):
        frame = frame.f_back
        if not frame:
            return size

def nearing_recursion_limit():
    """Return true if current stack depth is withing 100 of maximum limit."""
    return sys.getrecursionlimit() - _get_stack_depth() < 100
```

Which results in these times for me:

```python
>>> num, dur = timeit.Timer(lambda: markdown.markdown(">" * 100)).autorange(); dur / num
0.004146074000000013
>>> num, dur = timeit.Timer(lambda: markdown.markdown(">" * 200)).autorange(); dur / num
0.015264364999999992
>>> num, dur = timeit.Timer(lambda: markdown.markdown(">" * 300)).autorange(); dur / num
0.040780999999999776
```

Given my unmodified times, that doesn't seem to add any noticeable time at all.

**Comment by waylan** [comment]
However, if I do this:

```python
def get_remaining_stack_frames(depth=0):
    """ Return remaining number of stack frames before limit it hit."""
    try:
        return get_remaining_stack_frames(depth + 1)
    except RecursionError:
        return depth

def nearing_recursion_limit():
    """Return true if current stack depth is withing 100 of maximum limit."""
    return get_remaining_stack_frames() < 100
```
 then my times are:

```python
>>> num, dur = timeit.Timer(lambda: markdown.markdown(">" * 100)).autorange(); dur / num
0.013232544999999974
>>> num, dur = timeit.Timer(lambda: markdown.markdown(">" * 200)).autorange(); dur / num
0.0269508400000003
>>> num, dur = timeit.Timer(lambda: markdown.markdown(">" * 300)).autorange(); dur / num
0.04743795999999989
```

<del>The difference is negligible.</del> However, the example which counts up (to the max) is slower (relatively) that the example which counts down (the stack) for smaller size documents. As smaller documents are the norm, I think that is probably the more sensible way to go.

<ins>Whoops, my first attempt at both had the line which called the code commented out. I have since edited this comment and the last one to provide accurate results. The previous solution is noticeably better than this one.</ins>
