### ISSUE TITLE
Mardown not parsed inside HTML tags

### ISSUE THREAD

**Issue by Nivl** [Python-Markdown/markdown#80]
It seems that the parser doesn't parse inside HTML tags:

f.in

``` mardown
    \<table>
      \<th>**BOLD**
      \<td>*Italic*
    \</table>
```

python2 -m markdown f.in -f f.out

f.out

``` html
\<table>
  \<th>**BOLD**
  \<td>*Italic*
\</table>
```

F.out should contain <b>BOLD</b> instead of **BOLD**, and <i>Italic</i> instead of *Italic*

It works well with 2.0.3.

**Comment by waylan** [comment]
This is not a bug. In fact, it was a bug in 2.0 which has since been fixed. Therefore, I'm closing this as wontfix.

Check your sample input here: http://daringfireball.net/projects/markdown/dingus

The relevant part of the [syntax rule](http://daringfireball.net/projects/markdown/syntax#html) states:

> Note that Markdown formatting syntax is not processed within block-level HTML tags. E.g., you can’t use Markdown-style _emphasis_ inside an HTML block.

If you'd like to have markdown syntax processed inside raw HTML blocks, then use the [Extra](https://github.com/waylan/Python-Markdown/blob/master/docs/extensions/extra.md) extension. The feature is currently a little buggy (see issue #52) and therefore undocumented, but it's patterned after [PHP Markdown Extra](http://michelf.com/projects/php-markdown/extra/#markdown-attr)'s behavior. That documentation will  tell you how to use it. Just run python-markdown with the 'extra' extension.
