### ISSUE TITLE
Tables runs first before Inline processor

### ISSUE THREAD

**Issue by eunchan** [Python-Markdown/markdown#81]
I made internal page link extention for my site.
syntax looks like this

```
[[link_name | anchor title]]
```

It runs well with python-markdown 2.0.3. but in 2.1.1 when i made multiple page link with list, it is converted to table.

for example,
- [[link1 | test 1]]
- [[link2 | test 2]]

converted to tables not page link. 

I thought it was because of OrderedDict, thus i changed extention register code with '_begin'. but it doesn't affect anything.

**Comment by waylan** [comment]
Yes, block level processors all run before any inline patterns run. That is by design. If you want to introduce a new inline syntax, then you need to make sure it does not conflict with an existing block level syntax. You have a few options:
1. Alter you syntax so it doesn't look like a table to the parser.
2. Not use the table extension with your extension.
3. Fork the table extension and rewrite it so it doesn't conflict.

But there's nothing for me to fix here. I'm closing this wontfix.
