### ISSUE TITLE
Disable parts of markdown syntax

### ISSUE THREAD

**Issue by tapia** [Python-Markdown/markdown#811]
I know this question has been asked before in #179, but it was 6 years ago, so I think it's worth a try asking again.

I'd like to disable some parts of the markdown syntax in my app. In particular, but not only, I'd like to disable the embedded HTML. Is it possible somehow?

**Comment by waylan** [comment]
The answer is mostly the same as it was for #179. The one difference is that `safe_mode` was fully deprecated in version 3.0. In fact, the [release notes][1] provide a few suggested alternatives for dealing with raw HTML. I expect you'll find what you are looking for there.

Finally, I will note that we recommend using an HTML sanitizer (like Bleach) rather than disabling raw HTML, as disabling raw HTML does not make Markdown secure. You still need a sanitizer if you are parsing Markdown from untrusted sources. See [Markdown and XSS][2] for an analysis of the security vulnerabilities of Markdown syntax itself. While that article is written by the developer of PHP Markdown and concentrates on PHP solutions, the principles apply equally to Python-Markdown.

If you are looking to disable parts of the Markdown syntax for reasons other than security, then the [Extension API][3] is available to alter anything you would like. For the foreseeable future, the Extension API will be the only way to alter the behavior of the parser.

[2]: https://michelf.ca/blog/2010/markdown-and-xss/
[1]: https://python-markdown.github.io/change_log/release-3.0/#safe_mode-and-html_replacement_text-keywords-deprecated
[3]: https://python-markdown.github.io/extensions/api/

**Comment by geoffroy-noel-ddh** [comment]
Hi, I have a related question. Is there a way to selectively enable core constructs. For instance I would like to convert links and headings but not blockquotes or emphasis. Is that possible?

**Comment by waylan** [comment]
@geoffroy-noel-ddh yes, the [Extension API][1] can alter any part of the parser.

[1]: https://python-markdown.github.io/extensions/api/

**Comment by geoffroy-noel-ddh** [comment]
Do you have more specific examples of that? I can see how to add extensions but I'm not sure how to remove all the core syntax and add them one at a time. Say if I want to start with just links (and perhaps add other core constructs later), what's the approach? Is it as simple as passing a list of names/constants or would I have to override a lot of functions and reuse the built-in patterns?

**Comment by waylan** [comment]
You might find this [tutorial][1] in the wiki to be helpful. However, be aware that it has not yet been updated for version 3.x. Regardless, the basic concepts still stand.

The primary difference between 2.x and 3.x is that 3.x uses the new [Registry][2]. So, rather than using `del md.inlinePatterns['strong_em']` to remove a processor as demonstrated in the tutorial, you would do `md.inlinePatterns.deregister('strong_em')`.

Of course, if you wanted to rewrite most of the parser, you might find it more efficient to subclass the `markdown.Markdown` class and override the [build_parser][3] method. In this way, you can build up the parts you want, rather than having the default parser built up, only to tear it back down.

[1]: https://github.com/Python-Markdown/markdown/wiki/Tutorial:-Writing-Extensions-for-Python-Markdown
[2]: https://python-markdown.github.io/extensions/api/#registry
[3]: https://github.com/Python-Markdown/markdown/blob/master/markdown/core.py#L104

[1]: https://github.com/Python-Markdown/markdown/wiki/Tutorial:-Writing-Extensions-for-Python-Markdown

**Comment by geoffroy-noel-ddh** [comment]
@waylan thanks for taking the time to reply, that's very useful.
