### ISSUE TITLE
Two raw HTML blocks without blank lines between

### ISSUE THREAD

**Issue by balupton** [Python-Markdown/markdown#830]
Given:

```
The command-line client ships alongside the daemon. Usage information for all commands, including sub-commands, is available via the --help flag.

<style>pre { background: inherit !important; word-wrap: inherit !important;  white-space: pre-wrap !important; }</style>

## textile [&lt;flags&gt;]

<p><pre>Textile is a set of tools and trust-less infrastructure for building censorship resistant and privacy preserving applications</pre></p>
<table>
	<tr><th>Flag</th><th>Description</th></tr>
	<tr><td><code>--help</code></td><td><pre>Show context-sensitive help (also try --help-long and --help-man).</pre></td></tr>
	<tr><td><code>--help-long</code></td><td><pre>Generate long help.</pre></td></tr>
	<tr><td><code>--help-man</code></td><td><pre>Generate a man page.</pre></td></tr>
	<tr><td><code>--completion-bash</code></td><td><pre>Output possible completions for the given args.</pre></td></tr>
	<tr><td><code>--completion-script-bash</code></td><td><pre>Generate completion script for bash.</pre></td></tr>
	<tr><td><code>--completion-script-zsh</code></td><td><pre>Generate completion script for ZSH.</pre></td></tr>
	<tr><td><code>--api=&#34;http://127.0.0.1:40600&#34;</code></td><td><pre>API Address to use</pre></td></tr>
	<tr><td><code>--api-version=&#34;v0&#34;</code></td><td><pre>API version to use</pre></td></tr>
	<tr><td><code>--debug</code></td><td><pre>Set the logging level to debug</pre></td></tr>
</table>

## textile help [&lt;command&gt;]

<p><pre>Show help.</pre></p>
<table>
	<tr><th>Argument</th><th>Description</th></tr>
	<tr><td><code>[&lt;command&gt;]</code></td><td><pre>Show help on command.</pre></td></tr>
</table>

## textile account

<p><pre>Manage a wallet account</pre></p>
```

The latter two headers are not converted to h elements. If one changes it to:

```
The command-line client ships alongside the daemon. Usage information for all commands, including sub-commands, is available via the --help flag.

<style>pre { background: inherit !important; word-wrap: inherit !important;  white-space: pre-wrap !important; }</style>

## textile [&lt;flags&gt;]

<p><pre>Textile is a set of tools and trust-less infrastructure for building censorship resistant and privacy preserving applications</pre></p>
<table>
	<tr><th>Flag</th><th>Description</th></tr>
	<tr><td><code>--help</code></td><td><pre>Show context-sensitive help (also try --help-long and --help-man).</pre></td></tr>
	<tr><td><code>--help-long</code></td><td><pre>Generate long help.</pre></td></tr>
	<tr><td><code>--help-man</code></td><td><pre>Generate a man page.</pre></td></tr>
	<tr><td><code>--completion-bash</code></td><td><pre>Output possible completions for the given args.</pre></td></tr>
	<tr><td><code>--completion-script-bash</code></td><td><pre>Generate completion script for bash.</pre></td></tr>
	<tr><td><code>--completion-script-zsh</code></td><td><pre>Generate completion script for ZSH.</pre></td></tr>
	<tr><td><code>--api=&#34;http://127.0.0.1:40600&#34;</code></td><td><pre>API Address to use</pre></td></tr>
	<tr><td><code>--api-version=&#34;v0&#34;</code></td><td><pre>API version to use</pre></td></tr>
	<tr><td><code>--debug</code></td><td><pre>Set the logging level to debug</pre></td></tr>
</table>

<p></p>

## textile help [&lt;command&gt;]

<p><pre>Show help.</pre></p>
<table>
	<tr><th>Argument</th><th>Description</th></tr>
	<tr><td><code>[&lt;command&gt;]</code></td><td><pre>Show help on command.</pre></td></tr>
</table>

<p></p>

## textile account

<p><pre>Manage a wallet account</pre></p>
```

Then they are.

**Comment by waylan** [comment]
Thanks for the report. This is a weird one. It appears that the raw HTML parser is failing to find the end of the raw HTML block and consuming the rest of the document. Here is the minimum example I found which exhibits the problem:

```
<p><pre>Raw HTML</pre></p>
<table></table>

## Header
```

The above results in this output:

```html
<p><pre>Raw HTML</pre></p>
<table></table>

## Header
```

Note that this requires all of the following:

1. The `<p>` must have a `<pre>` nested in it.
2. There must be no blank line between the `<p>` and `<table>`.
3. I tried a `<p>` element instead of a `<table>` and the problem did not persist. I did not try any other elements yet.
4. The actual contents of the `<table>` seem to not matter, thus they are excluded in the above example.
5. It does not matter if the `<table>` is on multiple lines or one line. The problem persists either way.

Given number 2 above, as a workaround, you can add a blank line between each of the your raw HTML block level elements (add a blank line between your `<p>` and `<table>` elements). This should not be surprising as the [rules][1] state that each block level raw HTML element must be surrounded by blank lines. However, in practice, [all other implementations][2] don't require the blank line so we shouldn't either. This is a bug.

Presumably we missed this bug as we most likely only ever tested with two `<p>` tags. We also likely did not tests with a `<pre>` nested in a `<p>`. Actually, I'm not sure, but is a `<pre>` tag even valid in a `<p>`? It is certainly unusual.

[1]: https://daringfireball.net/projects/markdown/syntax#html
[2]: https://johnmacfarlane.net/babelmark2/?normalize=1&text=%3Cp%3E%3Cpre%3ERaw+HTML%3C%2Fpre%3E%3C%2Fp%3E%0A%3Ctable%3E%0A%3C%2Ftable%3E%0A%0A%23%23+Header

**Comment by waylan** [comment]
I have a suspicion that this could be related to #780. The result is different, but the tag counting alogarithm is wrong in both cases.

**Comment by facelessuser** [comment]
I suspect you are right...not looking forward to unraveling this 😬

**Comment by waylan** [comment]
This issue doesn't exist in #803. Of course, that is incomplete, but our efforts might be better utilized by finishing that than by addressing each of these individual edge cases in the existing code base.

**Comment by facelessuser** [comment]
That would honestly be my preferred route. Getting a nice clean implementation that is easier to debug would be great.
