### ISSUE TITLE
Unescaping of backslash escapes fail in html attributes

### ISSUE THREAD

**Issue by powertomato** [Python-Markdown/markdown#84]
I'm using mimetex to generate latex formulas which often contain functions beginning with backslashes. I embed the formulas with `![a formula](mimetex.cgi?\\frac{2}{3})` (Latex code in this case would be `\frac{2}{3}`). Instead of getting an:

```
<img alt="a formula" src="mimetex.cgi?\frac{2}{3]" />
```

I receive following output:

```
<img alt="a formula" src="mimetex.cgi?%02klzzwxh%3A0000%03frac%7Bx%7D%7By%7D" />
```

I'm not sure if I'm using it correct, but shouldn't `"\\"` result in a single `"\"`?

**Comment by waylan** [comment]
First, I will mention that at least in the example given, you shouldn't need to escape the backslash. Escaping only works on a specifically defined set of characters. If your backslash is not followed by one of those chars, then you don't need to escape it. The escapable chars are defined [here](https://github.com/waylan/Python-Markdown/blob/master/markdown/__init__.py#L76).

The escaping is working fine. However, the unescaping is not happening because you are escaping text that ends up in a html attribute. I've updated the title to reflect the real problem. 

The way the parser works is that escaped text (a backslash followed by an escapable char) is replaced by a hash (not really a hash, but similar), then the parser runs, then unescaping happens where the hash is replaced by the original char less the backslash. The important thing to note is that only the text of the html document gets unescaped, not the contents of attributes. Serialization of the Element tree happens first and that garbles (escapes) the hashes so they don't get recognized and swapped back out. Perhaps this should happen during serialization???

Thanks for the report.

**Comment by powertomato** [comment]
Thanks for the reply and explaination (and the correction I was struggling to explain what I mean). Actually I discovered this as I was writing an extension so I could just use `![math](latex-code-here)` for formulas and I don't need to url-escape them. You mentioned that you use sort of hashes for this. As a dirty hack I now replace that "hash" to get my formulas correct:

```
def handleMatch(self, m):
    latexcode=m.group(2).replace("\x02klzzwxh:0000\x03","\\")
    ...
```

Would that be save until this is resolved?

**Comment by waylan** [comment]
Something wasn't adding up to me so I went and tried to duplicate your problem. I can't seem to. What version of markdown are you using? The current version is 2.1.1.

**Comment by powertomato** [comment]
Oh I completly forgot to update before reporting... I was using 2.0.3 on both server and my development computer. It seems to work in 2.1.1. Thanks for your help. Sorry for wasting your time.
