### ISSUE TITLE
UL nested in OL produces non-nested HTML

### ISSUE THREAD

**Issue by bendavis78** [Python-Markdown/markdown#878]
The following markdown:

```
1. Item one
   * foo
   * bar
   * baz
2. Item two
```

produces the following HTML:

```
<ol>
<li>Item one</li>
<li>foo</li>
<li>bar</li>
<li>baz</li>
<li>Item two</li>
</ol>
```

Using `Markdown==3.1.1`

**Comment by waylan** [comment]
It appears that you indented the nested items by three spaces. However, Python-Markdown requires 4 spaces of indent for nested content (as [documented][1] under "Indentation/Tab Length"). In fact, if you add the extra space to each nested item, you will find you get the expected behavior.

Regarding the matter of ordered and unordered lists, see the note on "Consecutive Lists" at the above link. If that behavior bothers you, then you can use the [Sane Lists][2] extension. However, you will still need 4 spaces of indent.

As no bug has been reported, I am closing this.

[1]: https://python-markdown.github.io/#differences
[2]: https://python-markdown.github.io/extensions/sane_lists/
