### ISSUE TITLE
Preceding return character and spaces break fenced code blocks

### ISSUE THREAD

**Issue by mbarringer** [Python-Markdown/markdown#887]
I'm generating a Markdown file using a program ([Dokka](https://github.com/Kotlin/dokka)) which starts a fenced code blocks with three backticks at the beginning of one line, and for whatever reason, adds a return character and two spaces before the ending three backticks on another line. So the raw Markdown looks like

>     ```
>     Some code
>
>        ```

That's seemingly valid Markdown, at least every Markdown editor I've tried handles it fine. But the fenced_code and superfences extensions render the HTML as

```
<p>```
Some Code</p>
<p>```</p>
```

If I remove either the return character or the two spaces, the HTML is generated correctly:

```
<p><code>Some Code</code></p>
```

It is reproducible with this Markdown file:

[index.md.txt](https://github.com/Python-Markdown/markdown/files/3905078/index.md.txt)

And what pip tells me is version 3.1.1 of Python-Markdown.

**Comment by waylan** [comment]
Yeah, that is expected behavior. You need to remove the spaces. I would suggest determining why your editor is adding them. Many code editors include shortcuts which add extra indentation when it thinks you need it so you don't have to type it manually. Presumably your editor incorrectly thinks this is one of those places. If you work out why, you may be able to disable that automation.

As an aside, I checked [Babelmark][1] and was surprised how many implementations are so lax about this. However, I see that Python-Markdown and PHP Markdown Extra, the two implementations which first introduced Fenced Code Blocks, agree in behavior. In other words. We got it right. Everyone else got it wrong by being less strict.

[1]: https://johnmacfarlane.net/babelmark2/?normalize=1&text=%60%60%60%0ASome+code%0A%0A+++%60%60%60
