### ISSUE TITLE
Nested links

### ISSUE THREAD

**Issue by ThiefMaster** [Python-Markdown/markdown#89]
```
[<http://www.foo.bar>](http://www.google.com)
```

This results in nested `<a>` tags:

```
<p><a href="http://www.google.com"><a href="http://www.foo.bar">http://www.foo.bar</a></a></p>
```

The `<url>` should not create a new link if it's inside another link.
Fixing that would also fix the problems in the urlize extension.

I tried creating a treeprocessor which removes `a` elements inside `a` elements but wasn't successful - I'm sure it's possible though.

**Comment by waylan** [comment]
My gut reaction was "Why would you do that?" In all seriousness, I think that this is a case of bad markdown input. Bad input can return unexpected results. Check how other implementations handle this case. For one, markdown.pl has the same behavior as Python-Markdown.

As an implementation detail, the way to do this would be in the various link related InlinePatterns. However, each InlinePattern would need to be aware of the parent (i.e., an `a` tag cannot contain another `a` tag) - something which is not possible right now. And given that ElementTree Elements are not aware of their parents, this would require a major re-factor to get working properly. A re-factor I'm not opposed to, but it is not in the foreseeable future right now.

**Comment by ThiefMaster** [comment]
Yeah, it is indeed crappy markdown - but when you change the regex to not require `<>` around urls it's much more likely to happen.

**Comment by waylan** [comment]
@ThiefMaster you have a point. However, that is not standard markdown syntax. Which is why the urlize extension needs to come up with it's own stand-alone solution outside of the rest of the markdown parser IMO. Don't misunderstand me, if someone wanted to do the work on a re-factor of InlinePatterns to be parent aware, I'd be happy to merge that in (and even mentor its development), but the urlize extension would then need to utilize that on it's own.

That is one of the reasons why I'm an advocate for using the third party library [Bleach](https://github.com/jsocol/bleach) rather than the urlize extension if you really want that behavior. It is more aware of valid and invalid html than the markdown parser is. The markdown parser just assumes you are passing in properly nested markdown and can't be expected to account for every variation that third party extensions may introduce.

Hmm, a thought just occurred to me that perhaps the linkify method of Bleach could be re-implemented as a parent-aware TreeProcessor (TreeProcessors are just passed the tree - they can do whatever they want with it). That doesn't address the issue raised here. It's just a suggestion for anyone who wants to tackle the urlize problem in general. Please follow up with any discussion of this on the appropriate ticket or the mailing list.
