### ISSUE TITLE
Buggy parsing of empty link text 

### ISSUE THREAD

**Issue by follower** [Python-Markdown/markdown#9]
When a link is written like this:

```
[](http://example.com/)
```

the HTML is generated as:

```
<a href="http://example.com/" />
```

By way of comparison GitHub generates it as:

```
<a href="http://example.com/"></a>
```

And renders it as:

[](http://example.com/)

Interestingly, WebKit seems to handle the `<a href="" />` form _really_ badly in the rendering and element inspector. It leaves the link open to the start of the next anchor tag and adds multiple extra tags in the inspector.

**Comment by waylan** [comment]
Thanks for the report. This is a side effect of using ElementTree -
which is an xml library, not a html library. There is no easy way to
fix this either, aside from writing our own serializer. Although, if
you set output_format="html" (rather than the default "xhtml") this
solves the problem. Not sure what I'm going to do about this problem.

On Thu, May 19, 2011 at 4:36 PM, follower
reply@reply.github.com
wrote:

> When a link is written like this:
> 
>    [](http://example.com/)
> 
> the HTML is generated as:
> 
>    <a href="http://example.com/" />
> 
> By way of comparison GitHub generates it as:
> 
>    <a href="http://example.com/"></a>
> 
> And renders it as:
> 
> [](http://example.com/)
> 
> Interestingly, WebKit seems to handle the `<a href="" />` form _really_ badly in the rendering and element inspector. It leaves the link open to the start of the next anchor tag and adds multiple extra tags in the inspector.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/waylan/Python-Markdown/issues/9

## 

---

\X/ /-\ `/ |_ /-\ ||
Waylan Limberg
