### ISSUE TITLE
Question: how could i suppress messages from python-markdown ?

### ISSUE THREAD

**Issue by poulpoulsen** [Python-Markdown/markdown#900]
hello,
i use python-markdown as my markdown inside emacs.
every preview contains the messages from python-markdown, that all modules successfully loaded.

`
here is the code:
python3 -m markdown -x plantuml_markdown -x mdx_superscript -x mdx_subscript
`
if i  run that from shell without emacs, there are also the messages.
that is annoying, because the generated html contains this.

is there a way to suppress it?
i tried it with >/dev/null
but with no luck.

Any ideas?
Regards
Poul

**Comment by waylan** [comment]
As `--help` documents, the command line script offers four options:

- `-q/--quiet`: Suppresses all messages. 
- the default (no flag set): Output critical messages only.
- `-v/--verbose`: Output warning, error and critical messages.
- `-n/--noisy`:  Output debug, info, warning, error and critical messages.

So try using the `--quiet` flag. That said, messages about modules being loaded should only ever be info or debug messages, so you should only see them with `--noisy`. Are you sure the message isn't coming from emacs?

And if the message is coming from Python-Markdown, then it would be written to `stderror`, not `stdout`. Are you sure you redirected `stderror` to `dev/null`?

Also check the third party extensions. Do the messages still appear if you don't include an extension? If not, then the issue is with that extension.

**Comment by poulpoulsen** [comment]
hello,
i inserted the flag, but there is no difference.
if i start it like
`
python3 -m markdown -x plantuml_markdown -x mdx_superscript -x mdx_subscript
`
or like
`
python3 -m markdown -x plantuml_markdown -x mdx_superscript -x mdx_subscript --quiet
`
there is no difference.
`
Successfuly imported extension module "plantuml_markdown".
Successfully loaded extension "plantuml_markdown.PlantUMLMarkdownExtension".
Successfuly imported extension module "mdx_superscript".
Successfully loaded extension "mdx_superscript.SuperscriptExtension".
Successfuly imported extension module "mdx_subscript".
Successfully loaded extension "mdx_subscript.SubscriptExtension".
`
and it is clear for me, that those messages doesn't popup if no extension is loaded.

Therefore i dont know, what to do.
any help appreciate.

Regards
Poul

**Comment by waylan** [comment]
Which version of Markdown are you using? What does `python -m markdown --version` report?

**Comment by poulpoulsen** [comment]
it reported:
__main__.py 3.0.1

**Comment by poulpoulsen** [comment]
because i use python3, the command exactly is: python3 -m markdown --version.

**Comment by waylan** [comment]
While not the most recent version, the behavior should be the same. I don't understand how you are getting those messages as they are clearly `debug` messages. In fact, I can't replicate the problem locally.

**Comment by poulpoulsen** [comment]
Can i check, if any debug variable is on?
