### ISSUE TITLE
Emphasis with spaces

### ISSUE THREAD

**Issue by arikrupnik** [Python-Markdown/markdown#910]
This seems to be one of the areas where different Markdown processors disagree. Are these liteal asterisks, or is the phrase `69 and then ` emphasized? GitHub Markdown says literal asterisks, PM says emphasis.
```
He dialed *69 and then *23, and then hung up.
```
According to Babelmark, a large minority of implementations agree with PM: https://johnmacfarlane.net/babelmark2/?text=He+dialed+*69+and+then+*23%2C+and+then+hung+up.

I'm curious if this is a deliberate choice, or an artifact of other architectural decisions.

**Comment by facelessuser** [comment]
The pattern for emphasis has always been pretty simple. This is just not a case that has been an active concern in the default implementation.

With that said, personally, I don't like that emphasis triggers on this. This was one of my motivations in implementing my own emphasis: https://facelessuser.github.io/pymdown-extensions/extensions/betterem/

```py
>>> markdown.Markdown(extensions=['pymdownx.betterem']).convert('He dialed *69 and then *23, and then hung up.')
'<p>He dialed *69 and then *23, and then hung up.</p>'
```

**Comment by arikrupnik** [comment]
Thank you, @facelessuser. Silly question: I have PM 3.1.1; pip install pymdown-extensions seems to want 3.2. Can I install a version that would work with 3.1.1?
```
$ sudo pip install pymdown-extensions
[sudo] password for ari: 
Collecting pymdown-extensions
  Downloading https://files.pythonhosted.org/packages/07/a7/a96f233052e3cfe7cfc4ace0008c2d424f2949ca68a1c7815749f4f81242/pymdown_extensions-6.3-py2.py3-none-any.whl (198kB)
    100% |████████████████████████████████| 204kB 1.8MB/s 
Collecting Markdown>=3.2 (from pymdown-extensions)
  Could not find a version that satisfies the requirement Markdown>=3.2 (from pymdown-extensions) (from versions: 1.7, 2.0, 2.0.1, 2.0.2, 2.0.3, 2.1.0, 2.1.1, 2.2.0, 2.2.1, 2.3, 2.3.1, 2.4, 2.4.1, 2.5, 2.5.1, 2.5.2, 2.6, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.6.6, 2.6.7, 2.6.8, 2.6.9, 2.6.10, 2.6.11, 3.0, 3.0.1, 3.1, 3.1.1)
No matching distribution found for Markdown>=3.2 (from pymdown-extensions)
```

**Comment by facelessuser** [comment]
Yeah, 6.2.1 should work fine for you.

**Comment by arikrupnik** [comment]
Thanks! The extension loads and does what you say it does.

**Comment by waylan** [comment]
This is a little tricky. The [original rules][1] (what we use) only state:

> But if you surround an * or _ with spaces, it’ll be treated as a literal asterisk or underscore.

Which indicates that the token must have a space both before and after it to be treated as a literal character. However, the reference implementation (`markdown.pl`) only requires a space after an "opening" token or a space before a "closing" token to treat it as a literal character.

While I understand the logic behind it, that feels a little too much like magic to me. Of course, if the rules explicitly defined that behavior, we would follow it, but from a reading of the rules most people wouldn't recognize that as the expected behavior. Therefore, IMO, it would be surprising to see that behavior.

That said, personally, I always backslash escape (`\*`) an asterisk when I want a literal character, even when I know Markdown will not mistake it for an emphasis delimiter. It's just good practice and avoids surprises.

[1]: https://daringfireball.net/projects/markdown/syntax#em

**Comment by facelessuser** [comment]
Yeah, the rules are very unclear, and I admit my implementation is very opinionated. It works for me, but maybe not everyone.

I have no problem with the default being the way it is. It's been like that a loooong time.

**Comment by arikrupnik** [comment]
@waylan, I hear you on the magic. That actually answers my original question about deliberate choice. I've had this sign hanging over every single one of my desks since 2006:
![nomagic](https://user-images.githubusercontent.com/1756197/74372415-348d4100-4da0-11ea-9644-e785b65c908e.jpg)

Sometimes I think back to when I first heard of MD, and how it was going to be such a simple syntax to parse, not like that XML with all its quirky rules!
