### ISSUE TITLE
non-blocklevel elements in BLOCK_LEVEL_ELEMENTS

### ISSUE THREAD

**Issue by fin** [Python-Markdown/markdown#92]
Hey there.

Let me quote from [John Gruber's original Markdown Syntax](http://daringfireball.net/projects/markdown/syntax)

> Span-level HTML tags — e.g. `<span>`, `<cite>`, or `<del>` — can be used anywhere in a Markdown paragraph, list item, or header.

Imagine my confusion when I saw that Python-Markdown has 'del' and its sibling 'ins' in its BLOCK_LEVEL_ELEMENTS list.

Background:
I am working on a [diff highlighting library](https://github.com/luminousflux/overdiff/) that has some special syntax support for Markdown.

**Comment by waylan** [comment]
Markus,

I have no idea why `<ins>` and `<del>` are listed as block level tags.
I just checked and they have been since the very [first commit](https://github.com/waylan/Python-Markdown/blob/041ebad2652de431152d603f6133fa62596f0b48/markdown.py) back
on March 11, 2006 - some time before I joined the project. And the old
[change log](https://github.com/waylan/Python-Markdown/blob/b3e0359421ee0a649975ca29635ac8c0d7cf7641/docs/change_log.txt) makes no mention of it.

That said, I'm curious as to how this is causing a problem for you.
The way the raw html parser works is that the block level tags "must
be separated from surrounding content by blank lines, and the start
and end tags of the block should not be indented with tabs or spaces."
(see the [syntax rules](http://daringfireball.net/projects/markdown/syntax#html)).

If all of those requirements are not met, then any tags identified in
the BLOCK_LEVEL_ELEMENTS var will be ignored by the raw block parser
and they will instead be treated as inline html. I mention this
because it is a subtlety of how the parser works that may not be
immediately apparent by reading the code.

Could there be an edge case where this results in the "wrong behavior"
for `ins` or `del`? Perhaps. Do you have an example edge case? Do any
tests fail if `ins` and `del` are removed from the
BLOCK_LEVEL_ELEMENTS var? If so, are those tests wrong, or do we need
a different workaround to accommodate multiple edge cases?

**Comment by fin** [comment]
thanks for your quick answer!

> That said, I'm curious as to how this is causing a problem for you.

I'll check out the test cases later; this is an example where the current implementation is doing things obviously wrong:

``` Python
In [1]: import markdown

In [2]: test = '<ins>Hello there</ins> fellow coder, this is a simple example of Python-Markdown doing something terribly wrong, in [my](http://fin.io) opinion'

In [3]: markdown.markdown(test)
Out[3]: u'<ins>Hello there</ins>\n\n<p>fellow coder, this is a simple example of Python-Markdown doing something terribly wrong, in <a href="http://fin.io">my</a> opinion</p>'
```

**Comment by fin** [comment]
I tried removing `<ins>` and `<del>` from BLOCK_LEVEL_ELEMENTS, it doesn't seem to make any difference in the tests behavior.

**Comment by waylan** [comment]
> I tried removing `<ins>` and `<del>` from BLOCK_LEVEL_ELEMENTS, it doesn't seem to make any difference in the tests behavior.

With no failing tests and no documented reason to leave them in, I see
no reason to keep them. I'll remove them first chance I get - or a
merge request would probably get applied more quickly (hint hint).
