### ISSUE TITLE
Issue #53 (fenced code blocks in lists) is locked

### ISSUE THREAD

**Issue by analog-cbarber** [Python-Markdown/markdown#927]
Fenced code blocks in lists still don't work, nine years after this bug was filed:

https://github.com/Python-Markdown/markdown/issues/53

As a result the same bug afflicts mkdocs and other projects using this package.

What is the status of this bug? Why is it locked?

Is there some workaround for mkdocs users?

**Comment by facelessuser** [comment]
Honestly, people who want nested fence usually use [SuperFences](https://facelessuser.github.io/pymdown-extensions/extensions/superfences/). That is the short answer.

Python Markdown was based on the old spec from: https://daringfireball.net/projects/markdown/. Python Markdown's `fenced_code` extension was written to allow fences in the top level.

So I wrote SuperFences to work around these issues. In order to get `fenced_code` to work, it would have to adopt some of the general conventions that are employed in SuperFences. Now, I want to stress, that while SuperFences works great, the approach is not ideal. There have been plans to rework the block processor which is the big hold up for doing it proper, but that has not happened yet, I won't go into details, but there is quite a bit of work to be done there.

**Comment by analog-cbarber** [comment]
Thanks. That works for me.

Specifically I conda installed `pymdown-extensions` and added the following to my `mkdocs.yml`:

```yaml
markdown_extensions:
  - pymdownx.superfences:
     highlight_code: false
```

**Comment by waylan** [comment]
The reason for the block is stated in the last comment there. No other developments have happened since then. By locking the discussion, clearly bringing it to another issue is not desired.
