### ISSUE TITLE
Trouble with fenced code blocks, `fenced_code` enabled!

### ISSUE THREAD

**Issue by nickmccullum** [Python-Markdown/markdown#951]
Hey!

I am trying to use Python-Markdown on my blog, which is a Django project with a members-only login area. 

My fenced code blocks are not rendering properly to HTML, and I am hoping you can help me figure out why.

Here is the function I am using to render my Markdown files to HTML:

```python
def markdown(value):
from django import template
from django.template.defaultfilters import stringfilter

import markdown as md

register = template.Library()

@register.filter()
@stringfilter
def markdown(value):
    # return md.markdown(value, extensions=['markdown.extensions.fenced_code'])
    return md.markdown(value, extensions=['fenced_code'])
```
Here is the code cell in my Markdown file:

````
```python
class Person:
	def __init__ (x, age):
		x.age = age
```
````

And here is how it is rendering in my browser:

```
    <p>```python</p>
<p>class Person:</p>
<pre><code>def __init__ (x, age):  
x.age = age
</code></pre>
<p>```</p>

```
I have tried everything I could think of and haven't been able to determine the issue. Any ideas?

**Comment by waylan** [comment]
Are you sure your filter is being called by Django? I see you have an extra line at the beginning of your code `def markdown(value):` which would cause in ImportError. I'm not sure if that was simply a copy/paste error or if that exists in your actual code. If it is in your code, then your code would never get imported and would never be used. If you are not seeing any import error, then I wonder that Django is even attempting to use your code.

My point is that you need to first establish that your filter is being used rather than some other preexisting filter with the same name (It's been years since I used Django so I don't know what's included by default these days). If you replace the call to Markdown with a placeholder text string, then that placeholder string should appear in your page. If it does not, then you have a configuration problem. However, if it does, then the issue is with Markdown.

**Comment by nickmccullum** [comment]
I'm not sure why this is, but it seems to work with 2 extensions but not one:  

```python
from django import template
from django.template.defaultfilters import stringfilter

import markdown as md

register = template.Library()

@register.filter()
@stringfilter
def markdown(value):
# return md.markdown(value, extensions=['markdown.extensions.fenced_code'])
return md.markdown(value, extensions=['fenced_code', 'codehilite'])
```

Maybe it's because I specified the language after each first set of triple-backticks?

**Comment by nickmccullum** [comment]
In any case, you can close this issue now.
