### ISSUE TITLE
HTML escaping 

### ISSUE THREAD

**Issue by aero-wubook** [Python-Markdown/markdown#974]
Hi,
Maybe not a direct issue with `markdown`. But searching the source code didn't find more tips, so I better ask.

Compare this two cases:

```
>>> markdown.markdown('<b>R&B</b>')
'<p><b>R&amp;B</b></p>'
```

```
>>> markdown.markdown('<b>R&B;</b>')
'<p><b>R&B;</b></p>'
```

While the first one returns the HTML content escaped, the second does not. It seems that it takes "R&B;" as an identity, and does not escape it.

My expected output, in the second case, would be:

```
>>> markdown.markdown('<b>R&B;</b>')
'<p><b>R&amp;B;</b></p>'
```

How could I tweak this? How/where does `markdown` perform this HTML escaping?

Using tools like [html.escape](https://docs.python.org/3.8/library/html.html#html.escape) does not do the job, cause it escapes the entire string (HTML tags <> too).

Thanks!

**Comment by waylan** [comment]
Actually it is *not* escaping. Markdown sees `&B;` as an HTML entity. The default behavior is to not escape raw HTML. As HTML entities are raw HTML, it passes it through unaltered.

Note that [Babelmark][1] shows this behavior split two ways. All the old-school Markdown parsers (including the reference implementation) follow the same behavior, while the new commommark parsers follow your expected behavior. As Python-Markdown is not a commonmark parser, there is no bug here. The behavior is exactly as it should be.

[1]: https://johnmacfarlane.net/babelmark2/?normalize=1&text=R%26B%3B%0A%0AR%26B
