### ISSUE TITLE
MS Teams URL not parsed correctly

### ISSUE THREAD

**Issue by theotherp** [Python-Markdown/markdown#983]
I opened a [ticket](https://github.com/zulip/zulip/issues/15216) for the zulip chat program because MS Teams URL like thise `https://teams.microsoft.com/l/meetup-join/19%3A56f51235432123cb123412345d7ab3e7f@thread.tacv2/1231290290456?context={"Tid"%3A"17f10123-ef48-460d-8456-4c00c5e1b70d"%2C"Oid"%3A"9b95652f-c123-456d-af2e-890fd45623a3"}` are not correctly displayed as link. They use Python-Markdown. According to [Babelmark2](https://johnmacfarlane.net/babelmark2/?text=https%3A%2F%2Fteams.microsoft.com%2Fl%2Fmeetup-join%2F19%253A56f51235432123cb123412345d7ab3e7f%40thread.tacv2%2F1231290290456%3Fcontext%3D%7B%22Tid%22%253A%2217f10123-ef48-460d-8456-4c00c5e1b70d%22%252C%22Oid%22%253A%229b95652f-c123-456d-af2e-890fd45623a3%22%7D) [marked](https://github.com/markedjs/marked) can parse the URL (and others can as well).

**Comment by facelessuser** [comment]
Python Markdown follows the original Markdown spec and does not translate bare HTML links. If you'd like to translate the link, simply wrap it in angle brackets: `<mylink>`. With extensions, this can be done, for instance, the [MagicLink](https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/) extension allows this. It doesn't fully detect the link, just like some that are referenced in your Bablemark2 example. This is due to its current rule set. I don't think it currently allows the link to end in certain characters like `}`, so it will cut off before that.

**Comment by waylan** [comment]
As @facelessuser stated, the default behavior is for Python-Markdown to follow the behavior documented in the [original syntax rules][1]. Those rules require plain URL links to be wrapped in `<>`. Babelmark demonstrates thatPython-Markdown matches the reference implementation `markdown.pl` in this regard.

Of course our extension API is available for a third party extension to change that behavior. However, that must be handled by a third party extension. If your chat program is using an extension, then a bug should be raised with the developers of that extension. If they are not using an extension, then you should request that they add one. In any case, this is not something we can address here.

[1]: http://daringfireball.net/projects/markdown/syntax
