### ISSUE TITLE
Missing usage/examples

### ISSUE THREAD

**Issue by flying-falcon** [Python-Markdown/markdown#998]
Hi,
This repo is missing usage docs.

**Comment by waylan** [comment]
The documentation is available at https://python-markdown.github.io/.

If you mean we don't example of Markdown, well that is because the documentation for Markdown is at https://daringfireball.net/projects/markdown/syntax. No point in repeating that here. That said, we do provide examples in the documentation for our various extensions.

What documentation are we missing?

**Comment by flying-falcon** [comment]
Basically I was looking for simple usage docs, which I couldn't find.
```
from markdown import markdown
markdown(data)
```

**Comment by waylan** [comment]
The first section of this page seems to have exactly what you are looking for: https://python-markdown.github.io/reference/
